### ISSUE TITLE
Nach Update - Agent liefert keine Ergebnisse

### ISSUE THREAD

**Issue by MaAr389** [it-novum/openITCOCKPIT#1003]
Hallo, 
heute wurde das System aktualisiert (4.0.0) und um einige zu überwachende Systeme ergänzt. 
Bei einem Server funktioniert es tadellos, dass die Daten per Push an den Nagios-Server übermittelt werden. 

Bei 90 % der Server kommt folgende Fehlermeldung z.B. beim "System Load" - "UNKNOWN: No data received from agent" oder beim "Total CPU Percentage" - "((No output on stdout) stderr: Error: Unknown option `format`.)

Die Configs sehen folgendermaßen aus
`[default]
address = 192.168.10.221
port = 3333
interval = 30
try-autossl = false
verbose = false
stacktrace = false
config-update-mode = false
auth = 
customchecks = C:\Program Files\it-novum\openitcockpit-agent\customchecks.cnf
temperature-fahrenheit = false
dockerstats = false
qemustats = false
cpustats = true
processstats-including-child-ids = false
netio = true
diskio = true
winservices = true
diskstats = false
netstats = false
sensorstats = false
processstats = false
[oitc]
hostuuid = 
url = 
apikey = 
interval = 60
enabled = false
`

Im Voraus vielen Dank für Hilfe!

Gruß

**Comment by binsky08** [comment]
Hallo @MaAr389,

du sprichst davon, dass "Daten per Push an den Nagios-Server übermittelt werden".
Nur damit wir uns richtig verstehen, du möchtest den openITCOCKPIT Agent im Push Modus verwenden?

Die von dir angegebene Konfiguration entspricht jedoch der eines Agent im Pull Modus.
Laut der Konfiguration startet der Agent seinen lokalen Webserver auf der IP Adresse 192.168.10.221.
Zu diesem kann sich dann ein openITCOCKPIT verbinden.
Falls diese Konfiguration der Versuch war einen Push Modus (Agent verbindet sich zum openITCOCKPIT) zu konfigurieren, gibt es da leider einige Fehler.

Bitte stelle sicher, dass du die aktuelle Version von openITCOCKPIT und Agent (1.0.2) installiert hast.

Um eine Fehlkonfiguration als Fehlerursache auszuschließen, gehe bitte in deinem openITCOCKPIT zur Agent Konfiguration, wähle den entsprechenden Host aus und lasse dir eine vollständige Konfiguration durch das Frontend erstellen.
![grafik](https://user-images.githubusercontent.com/30630233/84479560-75845c00-ac93-11ea-86c0-c1e6ba6a0bab.png)
Im Anschluss erhältst du dort auch Hinweise zum weiteren Vorgehen. Sprich wo sich die Konfiguration auf deinem System befinden sollte und wie der Agent nach dessen Änderung neu gestartet werden kann.

Sollte das Problem danach auch weiterhin auftreten:
- Gibt es bestimmte Services (z.B. nur bei System Load), bei denen der Fehler auftritt?
- Wie alt ist deine v4 (circa) und wurde sie frisch installiert oder ein Upgrade von einer v3 durchgeführt?

Bei weiteren Unklarheiten zur Konfiguration kann dir vielleicht unsere Doku weiterhelfen:
[https://docs.it-novum.com/display/ODD/openITCOCKPIT+Agent#openITCOCKPITAgent-Konfiguration](https://docs.it-novum.com/display/ODD/openITCOCKPIT+Agent#openITCOCKPITAgent-Konfiguration)

**Comment by MaAr389** [comment]
Hallo @binsky08 , 
ich muss mich korrigieren, du hast Recht. Es ist die Pull-Methode. 
Aktuelle Version des Agent ist die Version 1.0.0.

Der Server hält die aktuellste Version 4 beta. Ich weiß momentan nicht, wo ich den Versionsstand einsehen kann. 

Vermutlich liegt es mit der Version des Agents zusammen, dass das nicht funktioniert. Werde ich am Montag direkt testen und mich wieder melden. 

Vielen Dank und ein schönes Wochenende!

**Comment by MaAr389** [comment]
Hallo,
ich habe jetzt die Konfiguration für einen Server in den Push-Modus versetzt. Der Agent ist ist der neusten Version installiert, leider ohne Erfolg. 

Übrigens, es war eine frische Installation, kein Upgrade.

config.cnf
`[default]
address = 192.168.10.202
port = 3333
interval = 30
try-autossl = false
verbose = false
stacktrace = false
config-update-mode = false
auth = 
customchecks = C:\Program Files\it-novum\openitcockpit-agent\customchecks.cnf
temperature-fahrenheit = false
dockerstats = false
qemustats = false
cpustats = true
sensorstats = false
processstats = false
processstats-including-child-ids = false
netstats = true
diskstats = true
netio = true
diskio = true
winservices = true
systemdservices = false
wineventlog = false
alfrescostats = false
alfresco-jmxuser = monitorRole
alfresco-jmxpassword = change_asap
alfresco-jmxaddress = 0.0.0.0
alfresco-jmxport = 50500
alfresco-jmxpath = /alfresco/jmxrmi
alfresco-jmxquery = 
alfresco-javapath = /usr/bin/java

[oitc]
hostuuid = e1e2a670-fedc-45f5-a677-d57990ac0134
url = https://192.168.10.209
apikey = xyz
interval = 60
enabled = true
`
customchecks.cnf
`[default]
# max_worker_threads should be increased with increasing number of custom checks
# but consider: each thread needs (a bit) memory
max_worker_threads = 8

[Laufwerk_C]
command = powershell.exe -File "C:\scripts\DiskFree_C.ps1"
interval = 60
timeout = 5
enabled = true
`

![output](https://user-images.githubusercontent.com/27082197/84628894-bd042580-aee9-11ea-8f36-09d931688ccc.JPG)

**Comment by binsky08** [comment]
Hallo @MaAr389,

wenn du den Agent im Push Modus konfiguriert hast, sollte openITCOCKPIT eigentlich keinen OITC_AGENT_ACTIVE Service mehr anlegen.

Bite prüfe noch mal folgende Schritte:
1. Export ausführen (ist der OITC_AGENT_ACTIVE Service danach weg / funktioniert es vielleicht generell schon?)
2. Gehe zur Agent Konfiguration, wähle den Host, wähle Push-Mode, drücke Next (ohne Konfiguration, die hast du ja schon), drücke Next und warte, ob dir verfügbare Checks angezeigt werden. Wenn nicht, erreicht der Agent dein openITCOCKPIT vermutlich nicht. Wenn ja, dann drücke Next und führe noch ein mal Schritt 1 durch.
3. Wenn alles nichts bringt, Host löschen, neu anlegen, Schritt 2 ausführen.

**Comment by MaAr389** [comment]
Hallo @binsky08 
Fehler behoben. Ich habe die Server entfernt und alle neu hinzugefügt. 
Nun melden alle System ordnungsgemäß.
