### ISSUE TITLE
Refresh configuration beendet sich nicht

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1004]
sudo systemctl stop naemon
sudo systemctl stop gearman-job-server
sudo systemctl restart gearman_worker
sudo systemctl restart sudo_server

sudo systemctl start gearman-job-server
sudo systemctl start naemon

Konnte das Problem auch nicht lösen. Es bleibt bei:

![Bildschirmfoto vom 2020-06-14 13-44-00](https://user-images.githubusercontent.com/44997840/84592338-3990f880-ae45-11ea-997e-d002d0bd6fb4.png)

**Comment by nook24** [comment]
Hi, der Status vom "Configuration refresh" wird in der Datenbank gespeichert. Wenn der komplette Status zurückgesetzt werden soll am besten wie folgt vorgehen:

1. Den oitc `gearman_worker` stoppen. (Dieser schreibt unter anderem die Konfigurationsdateien):
```
sudo systemctl stop gearman_worker
```

2. Mit `gearadmin --status` schauen, ob noch Jobs in der `oitc_gearman` Queue liegen.
Wenn keine Jobs in der Queue liegen, sollte die Ausgabe so aussehen:
```
oitc_gearman	0	0	0           # Jobs    Aktiv    Anzahl Worker
```

3. Wenn Jobs in der Queue liegen, diese zur Sicherheit erst einmal in den Müll werfen. Dafür folgendes Kommando ausführen, bis keine Jobs mehr da sind:
```
gearman -w -c 1 -t 1000 -f oitc_gearman > /dev/null
```

4. Die `exports` Tabelle in der Datenbank leeren
```
mysql --defaults-extra-file=/etc/mysql/debian.cnf -e "TRUNCATE TABLE openitcockpit.exports;"
```

5. Den `gearman_worker` wieder starten:
```
sudo systemctl start gearman_worker
```

Hoffe das hilft dir weiter.

**Comment by infofrs** [comment]
Damit wird der Export erfolgreich beendet. Aber: Jeder neue Export hängt sich trotzdem gleich wieder auf..
![image](https://user-images.githubusercontent.com/44997840/84750273-5cddb400-afbb-11ea-9409-813dce5110b9.png)

**Comment by nook24** [comment]
Dann am besten einmal den gearman_worker im Vordergrund starten, um eventuelle Fehler zu sehen und nochmal einen Export starten.
```
sudo systemctl stop gearman_worker

sudo oitc gearman_worker
```

**Comment by infofrs** [comment]
![error_export](https://user-images.githubusercontent.com/44997840/84778273-0dab7980-afe3-11ea-91fb-3f18d2e4885c.JPG)

**Comment by binsky08** [comment]
Hallo @infofrs,

bitte kontrolliere mal mit folgendem Befehl, ob die 2 benötigten Pakete für die Checkmk Integration installiert sind. Falls nicht, diese bitte installieren.
`apt policy openitcockpit-checkmk openitcockpit-module-checkmk`

Wenn beide Pakete schon installiert sind, tritt der Fehler auf Grund veralteter Systemeinstellungen für Checkmk auf. Diese kannst du über folgende Befehle beheben.

```
INIFILE=/opt/openitc/etc/mysql/mysql.cnf
mysql --defaults-extra-file=${INIFILE} -e "UPDATE commands SET command_line = 'PYTHONPATH=/opt/openitc/check_mk/lib/python OMD_ROOT=/opt/openitc/check_mk python /opt/openitc/check_mk/var/check_mk/oitc_precompiled/\$HOSTNAME\$.py' WHERE name = 'check_mk_active';"
mysql --defaults-extra-file=${INIFILE} -e "UPDATE systemsettings SET value = 'PYTHONPATH=/opt/openitc/check_mk/lib/python OMD_ROOT=/opt/openitc/check_mk OMD_SITE=1 /opt/openitc/check_mk/bin/check_mk' WHERE \`key\` = 'CHECK_MK.BIN';"
mysql --defaults-extra-file=${INIFILE} -e "UPDATE systemsettings SET value = '/opt/openitc/check_mk/etc/check_mk/' WHERE \`key\` = 'CHECK_MK.ETC';"
mysql --defaults-extra-file=${INIFILE} -e "UPDATE systemsettings SET value = '/opt/openitc/check_mk/var/check_mk/' WHERE \`key\` = 'CHECK_MK.VAR';"
```

Starte danach bitte wieder den gearman_worker im Vordergrund (wie von nook24 beschrieben) und führe einen Export durch. Sollten keine Fehler mehr zu sehen sein, kannst du den gearman_worker Service mit `systemctl start gearman_worker` wieder starten.

**Comment by infofrs** [comment]
Passt jetzt. Die Pakete waren alle in richtiger Version installiert.
Das Update in der Datenbank brachte den Erfolg. Habe die Exportqueue noch gelöscht und dann via sudo oitc gearman_worker einen Export durchgeführt was nun erfolgreich war. Gearman_Worker läuft jetzt wieder normal und der Export ist sauber durchgelaufen 2 mal.
