### ISSUE TITLE
checkmk Module sorgt für Systemcrash

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1007]
Gegeben ist eine laufende Version 4.0.3 wo alle Services und der oITC Agent sauber funktionieren.
Scenario:
apt-get install openitcockpit-module-checkmk

Danach in der GUI:

Attention! Could not connect to SudoServer. External commands may not work. Please try to reload this page.!
Lauch Config  beendet sich nach Start anschliessend nicht mehr.

Sudo_Server_Service läuft auf Server die ganze Zeit.

**Comment by binsky08** [comment]
Hallo @infofrs,

bitte prüfe mal, ob folgende Pakete installiert sind und in welcher Version:
`apt policy openitcockpit-module-checkmk openitcockpit-checkmk openitcockpit-module-mk`
openitcockpit-module-mk darf nicht installiert sein. Die anderen beiden müssen installiert sein.

Danach bitte mal das hier ausprobieren: [https://github.com/it-novum/openITCOCKPIT/issues/1004#issuecomment-643937452](https://github.com/it-novum/openITCOCKPIT/issues/1004#issuecomment-643937452)
Am Ende jedoch den Service **nicht starten**, sondern `sudo oitc gearman_worker` manuell starten.
Danach einmal übers Frontend exportieren. Sollten dabei Fehler auftreten, sollten diese nun in der Konsole zu sehen sein.
Diese dann bitte hier mal posten.

**Comment by infofrs** [comment]
Leider gleiches Ergebnis. Installiert ist:
![image](https://user-images.githubusercontent.com/44997840/85512769-8bcada00-b5fa-11ea-90c3-2403e51ca6c0.png)

Der Refresh beendet sich weiter hin nicht:
![image](https://user-images.githubusercontent.com/44997840/85512854-a56c2180-b5fa-11ea-9f1e-4b7ddb590ee4.png)

**Comment by binsky08** [comment]
Hallo @infofrs,

schade, dass das keine Wirkung gezeigt hat.
Probiere das Ganze bitte nochmal, aber starte gearman_worker mit folgendem Kommando:
`OITC_DEBUG=1 sudo -E oitc gearman_worker`

**Comment by infofrs** [comment]
Output wie folgt:

![image](https://user-images.githubusercontent.com/44997840/85701850-1df7de80-b6de-11ea-990f-a62bb4218008.png)

**Comment by binsky08** [comment]
Hallo @infofrs,

der Fehler sollte eigentlich schon längst nicht mehr auftauchen.
Der Grund ist vmtl eine ältere Erstinstallation der v4 oder ein Problem während des Upgrades der v3 auf die v4.
Es scheint so, als wären in dem System noch die alten Checkmk Pfade eingetragen.
Um diese zu korrigieren, führe auf der Konsole bitte folgende Kommandos mit root Berechtigung aus.

```
INIFILE=/opt/openitc/etc/mysql/mysql.cnf
mysql --defaults-extra-file=${INIFILE} -e "UPDATE mkagents SET command_line = REPLACE(command_line, '/opt/openitc/nagios/3rd/check_mk/agents/special/agent_vsphere', '/opt/openitc/check_mk/share/check_mk/agents/special/agent_vsphere --no-cert-check');"
mysql --defaults-extra-file=${INIFILE} -e "UPDATE commands SET command_line = 'PYTHONPATH=/opt/openitc/check_mk/lib/python OMD_ROOT=/opt/openitc/check_mk python /opt/openitc/check_mk/var/check_mk/oitc_precompiled/\$HOSTNAME\$.py' WHERE name = 'check_mk_active';"
mysql --defaults-extra-file=${INIFILE} -e "UPDATE systemsettings SET value = 'PYTHONPATH=/opt/openitc/check_mk/lib/python OMD_ROOT=/opt/openitc/check_mk OMD_SITE=1 /opt/openitc/check_mk/bin/check_mk' WHERE \`key\` = 'CHECK_MK.BIN';"
mysql --defaults-extra-file=${INIFILE} -e "UPDATE systemsettings SET value = '/opt/openitc/check_mk/etc/check_mk/' WHERE \`key\` = 'CHECK_MK.ETC';"
mysql --defaults-extra-file=${INIFILE} -e "UPDATE systemsettings SET value = '/opt/openitc/check_mk/var/check_mk/' WHERE \`key\` = 'CHECK_MK.VAR';"

oitc checkmkNagiosExport --init
```

Vermutlich selbes Problem: https://github.com/it-novum/openITCOCKPIT/issues/1004

**Comment by infofrs** [comment]
Bingo. Es ist eine der ersten V4 Testinstallationen überhaupt welche geupdatet wurde. Keine Migration von V3. Habe die mysql Tabelle wie beschrieben bereinigt und der EXport läuft nun sauber wie gewünscht. Danke
