### ISSUE TITLE
How to enable remote access to mysql db on itc host?

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1010]
Content of mysql config is like:

root@OITCV4:/opt/openitc/etc/mysql# cat mysql.cnf
; Automatically generated for openITCOCKPIT scripts. DO NOT TOUCH!
[client]
database = openitcockpit
host = localhost
user = openitcockpit
password = xxx
port = 3306

How to change host to ip address or hostname instead of localhost?

**Comment by binsky08** [comment]
Hi,

the three files /opt/openitc/etc/mysql/{bash.conf/dump.cnf/mysql.cnf} contain the same mysql connection data in different formats for different cases.
So if you want to change some connection data, you have to update all three files!
You also need to make sure that the files do not change format after being edited.
