### ISSUE TITLE
Grafana update check should be disabled

### ISSUE THREAD

**Issue by Skywalker-11** [it-novum/openITCOCKPIT#1011]
Currently the grafana container regularly checks if updates are available for grafana. This is only a check that can be displayed in the grafana web gui but doesn't actually update anything. As grafana is provided as a container image  and should be updated that way the update check should be disabled by setting `check_for_updates = false` 

https://github.com/it-novum/openITCOCKPIT/blob/bc97bc0e04f4ceae0376a27e400f65bcf8e235e6/src/config_templates/graphing/grafana/grafana.ini#L138

**Comment by nook24** [comment]
Good idea, thanks.

**Comment by nook24** [comment]
Done in latest release also Grafana version got bumped to 7.1
