### ISSUE TITLE
Warning Error during v4 upgrade

### ISSUE THREAD

**Issue by binsky08** [it-novum/openITCOCKPIT#1016]
I recently updated my openITCOCKPIT 3 (latest version) to 4 and received a warning error.
`Warning Error: Invalid argument supplied for foreach()`

![image](https://user-images.githubusercontent.com/30630233/88290796-92cb3200-ccf7-11ea-83e4-dae81e578b70.png)

Nevertheless the update was successful :)

**Comment by nook24** [comment]
Good to read that your upgrade was successful.
This line/code re enables the users for the web interface. So just in case someone found this issue in the future and can not login after this error message, here is the documentation on how to resolve this issue manually.

https://docs.it-novum.com/display/ODE/Upgrade+openITCOCKPIT+3.x+to+openITCOCKPIT+4.x#UpgradeopenITCOCKPIT3.xtoopenITCOCKPIT4.x-Cantloginafterpasswordreset

**Comment by m4ximum** [comment]
this is possibly caused by the parse_ini_file method in the pre_v4_upgrade script which fails on special chars (eg. in password) when parsing the mysql.cnf file

**Comment by nook24** [comment]
Looks like i accidentally reopened this issue with my commit...
