### ISSUE TITLE
 Could not detect system health status. 

### ISSUE THREAD

**Issue by some-git-user** [it-novum/openITCOCKPIT#1018]
Laut WebUi wird der "System Health" Status nicht erkannt.
![image](https://user-images.githubusercontent.com/65288184/88532512-05445680-d005-11ea-83c2-84bdfc413d24.png)

Der shell Befehl "oitc system_health" meldet aber keine Probleme:

$ oitc system_health
Fetch system health information...   Ok

**Comment by m4ximum** [comment]
Hallo @some-git-user,
Welches betriebssystem verwendest du und ist dies eine neuinstallation oder migration von version 3 ?

**Comment by some-git-user** [comment]
Das System wurde vor ein paar Monaten frisch als Version 4 auf Ubuntu 18.04 installiert.
Die Health-Anzeige hatte auch bis vor kurzem funktioniert. 
Der Fehler tritt erst seit einem Openitcockpit-Update über "apt update" auf.
Welches Update genau, kann ich aber nicht sagen.

**Comment by nook24** [comment]
Kannst du bitte einmal den Befehl `oitc cronjobs -f` als root Benutzer ausführen und schauen, ob dabei Fehler auftreten?

**Comment by some-git-user** [comment]
Der Befehl lieferte keine Fehlermeldungen zurueck. Nach dem Aufruf funktioniert aber auch die Anzeige in der WebUI wieder :+1:

**Comment by nook24** [comment]
Dann wird der Cronjob bei dir nicht ausgeführt. openITCOCKPIT 4 nutzt dafür einen Systemd Timer. Schau am besten einmal ob dieser aktiviert ist `systemctl status oitc_cronjobs.timer`. Die Ausgabe sollte so aussehen:
```
[10:36][0][root@srvoitcmonitoring02:~]# systemctl status oitc_cronjobs.timer
● oitc_cronjobs.timer - Timer for openITCOCKPIT cronjobs
   Loaded: loaded (/lib/systemd/system/oitc_cronjobs.timer; enabled; vendor preset: enabled)
   Active: active (waiting) since Thu 2020-07-23 11:31:57 CEST; 3 weeks 3 days ago
  Trigger: Mon 2020-08-17 10:38:00 CEST; 14s left
```

**Comment by some-git-user** [comment]
Ja, der Service laeuft:
● oitc_cronjobs.timer - Timer for openITCOCKPIT cronjobs
   Loaded: loaded (/lib/systemd/system/oitc_cronjobs.timer; enabled; vendor preset: enabled)
   Active: active (waiting) since Mon 2020-08-17 10:10:14 CEST; 45min ago
  Trigger: Mon 2020-08-17 10:57:00 CEST; 52s left

Laut `journalctl -u oitc_cronjobs.timer` lief dieser auch immer mit (Started Timer for openITCOCKPIT cronjobs)

**Comment by nook24** [comment]
Hm... `Active: active (waiting) since Mon 2020-08-17 10:10:14 CEST; 45min ago` also der Timer wurde auf jedenfall heute einmal neu gestartet.
Du kannst das ganze ja einmal im Auge behalten, ob die Cronjobs jetzt richtig ausgeführt werden. Wenn ja hatte sich Systemd da eventuell verschluckt.

Wann ein Cronjob zuletzt ausgeführt wurde kannst du auch in der openITCOCKPIT Oberfläche sehen:
![Bildschirmfoto 2020-08-17 um 11 08 34](https://user-images.githubusercontent.com/9019992/90378793-1ae3f380-e07a-11ea-889f-d64636d53cb5.png)

`SystemHealth` zum Beispiel soll jeden Minute ausgeführt werden. Wenn alles passt, kannst du das Issue dann schließe :)

**Comment by some-git-user** [comment]
Das lag vermutlich an `apt dist-upgrade`, dass ich heute frueh ausgefuert habe. Wollte pruefen ob die Health-Anzeige nach einem oitc-Update noch funktioniert.
In der Cronjob-Uebersicht sieht alles gut aus;

Aber eine Sache ist mir noch im "Debugging" aufgefallen:

![Screenshot_20200817_112157](https://user-images.githubusercontent.com/65288184/90380122-f721ad00-e07b-11ea-92d9-d4692c42cdbc.png)

Laut Health-Anzeige ist aber alles in Ordnung?

**Comment by nook24** [comment]
Hi @some-git-user die Queue `statusngin_comments` wird nicht genutzt und sollte eigentlich garnicht da sein. Diese verschwindet dann mit dem nächsten Update: https://github.com/it-novum/openITCOCKPIT/commit/1152758e78804cddab04412a5d9c10f5a06fa62f
