### ISSUE TITLE
Can´t send notifications after v4 upgrade

### ISSUE THREAD

**Issue by binsky08** [it-novum/openITCOCKPIT#1019]
After upgrading openITCOCKPIT 3 to version 4, it is not able to send notifications. (e.g. email and push not working)

It seems that there is a rights problem with `/opt/openitc/frontend/tmp/nagios/cache/nagios/{persistent,models}`

![grafik](https://user-images.githubusercontent.com/30630233/88540114-b3a2c880-d012-11ea-827d-0ca0863e4d64.png)

If you set group to nagios, the problem will be fixed for a short time (Push notifications work again)
`chgrp -R nagios /opt/openitc/frontend/tmp/nagios && chmod -R g+w /opt/openitc/frontend/tmp/nagios`

**Comment by m4ximum** [comment]
@binsky08 is there anything you have done manually on the filesystem before and after the upgrade? Ive set up an v3 with working notifications and upgraded it to v4. Its working well so far even with www-data:www-data permissions.
Which user and group was it before you changed the group to nagios ?

**Comment by binsky08** [comment]
No, it was www-data:www-data before.
After changing folder rights to 777 and sending a new notification a file with nagios:nagios was created.

**Comment by m4ximum** [comment]
we will keep an eye on it but by now we are not able to reproduce this behavior
