### ISSUE TITLE
apt source for version 3.7.2

### ISSUE THREAD

**Issue by chppppp** [it-novum/openITCOCKPIT#1022]
Hi!! I am looking for an apt source for 3.7.2 specifically. The apt source published on your site only contains 3.7.3. 

Any help is appreciated. thanks so much.

**Comment by Skywalker-11** [comment]
The source code is available at the GitHub release page:
[https://github.com/it-novum/openITCOCKPIT/releases/tag/openITCOCKPIT-3.7.2](https://github.com/it-novum/openITCOCKPIT/releases/tag/openITCOCKPIT-3.7.2)

**Comment by chppppp** [comment]
hi @Skywalker-11 thanks for the response. Any chance this lives in an apt repo? i have become a pretty lazy sysadmin and i love being able to maintain everything via apt. I am running ubuntu 18.04. 

thanks so much!

**Comment by chppppp** [comment]
plus, apt pulls all the dependencies which is very useful for a fresh build of openitcockpit

**Comment by support-itn** [comment]
hello chppppp,

version 3.7.2 can no longer be installed via apt. version 3.7.3 is almost identical, a few security aspects have been incorporated and a grafana bug has been fixed. 

see Blogpost and find the v3 at https://openitcockpit.io/download_server/#v3
