### ISSUE TITLE
mysqldump: Error: Access denied

### ISSUE THREAD

**Issue by some-git-user** [it-novum/openITCOCKPIT#1023]
Beim Update über "apt upgrade" erscheint folgende Fehlermeldung:

```
...
Setting up openitcockpit-common (4.0.4-20200804051101bionic) ...
Setting up openitcockpit (4.0.4-20200804051101bionic) ...
Setting up openitcockpit-module-map (4.0.4-20200804051101bionic) ...
Setting up openitcockpit-module-grafana (4.0.4-20200804051101bionic) ...
Processing triggers for openitcockpit (4.0.4-20200804051101bionic) ...
Create mysqldump of your current database

mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces

---------------------------------------------------------------
Convert MySQL Tables from utf8_general_ci to utf8mb4_general_ci...
Running openITCOCKPIT Core database migration
...
```
Das Update läuft aber weiter.
Kann diese Meldung ignoriert werden?

**Comment by m4ximum** [comment]
Hallo, 
der fehler ist uns bisher nicht bekannt. Wurden die rechte des mysql users nachträglich verändert ?

**Comment by some-git-user** [comment]
Die Rechte wurden nicht angepasst.
Habe eben mal einen Dump von der Konsole aufgerufen:

`mysqldump -uopenitcockpit -p openitcockpit`

Dieser startet und liefert keine Fehlermeldung.

**Comment by m4ximum** [comment]
Scheinbar hat sich mit dem update auf mysql version 5.7.31 etwas an der Benutzung von mysqldump verändert.
Hier zu sehen unter Security Notes: https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-31.html 
vielen dank fürs melden!
Wir arbeiten an der Lösung des problems
