### ISSUE TITLE
"User Defined Macros" empty after package update

### ISSUE THREAD

**Issue by exa-mk** [it-novum/openITCOCKPIT#1026]
After Debian/Ubuntu package updates the "User Defined Macros" ($USER2$, $USER3$, etc.) become empty and the checks in custom pathes fail. After a manual click on the "refresh configuration" button it works again.

**Comment by m4ximum** [comment]
The fix to this behavior will be provided in the next version of openITCOCKPIT

**Comment by exa-mk** [comment]
Just upgraded to 4.0.5. Problem still exists.
