### ISSUE TITLE
Performance data size limit on oITCv4

### ISSUE THREAD

**Issue by Skywalker-11** [it-novum/openITCOCKPIT#1032]
I noticed that the size of the performance data for a service seems to be limited to 1024 characters although the service command creates more output.
Is it possible to increase this limit? I think I remember oITC v3 having a higher limit for this

**Comment by nook24** [comment]
You can increase the length of the `perfdata` column in the `statusengine_servicestatus` table. At least for now it will not get overwritten by an update.

**Comment by Skywalker-11** [comment]
Thanks, that seems to work
