### ISSUE TITLE
Enable active checks option on host not working

### ISSUE THREAD

**Issue by binsky08** [it-novum/openITCOCKPIT#1041]
I have a host that is not reachable from my openITCOCKPIT instance.
So I turned off the "Enable active checks" option.
![grafik](https://user-images.githubusercontent.com/30630233/90241461-6359a200-de2b-11ea-9d88-cd7a767df4c7.png)

Unfortunately the check is still being carried out.
![grafik](https://user-images.githubusercontent.com/30630233/90241766-014d6c80-de2c-11ea-873b-b7987bcb1875.png)

**Comment by jabdr** [comment]
This is the freshness check. Currently there is no way to disable it for hosts. (=> feature request)

As a workaround you could add check_none as host command (like the service command) and set 0 as ARG1. Then the command just returns ok.

**Comment by binsky08** [comment]
Yes, using check_none was my solution, but disabling "Enable active checks" is described with "If disabled the check command won't be executed....". It's just confusing when it doesn't.

**Comment by nook24** [comment]
We should add an `Enable freshness check` option for hosts like we have for services.
![Bildschirmfoto 2020-08-17 um 09 42 55](https://user-images.githubusercontent.com/9019992/90370696-1ca7ba00-e06e-11ea-880b-cdf2943705ef.png)

**Comment by nook24** [comment]
Tracked by ITC-2387
