### ISSUE TITLE
Mattermost Module: two_way does not stick

### ISSUE THREAD

**Issue by Tampa** [it-novum/openITCOCKPIT#1042]
This may be the result of the install not going smoothly on my testsystem, but enabling two_way in the Mattermost module will write to database, but upon page reload the checkbox is not ticked anymore. Somehow it cannot fetch this from the database, but all other settings appear correctly.

**Comment by nook24** [comment]
This will be fixed with the next release

**Comment by nook24** [comment]
Resoved with Version 4.0.5: https://github.com/it-novum/openITCOCKPIT/releases/tag/openITCOCKPIT-4.0.5
