### ISSUE TITLE
Unable to login after upgrade to openITCOCKPIT v4

### ISSUE THREAD

**Issue by W7T2A** [it-novum/openITCOCKPIT#1045]
Hi,
after upgrading my OITC 3.x environment to 4.x I get the following error message when I try to login:

2020-08-19 10:36:33 Error: [Cake\Core\Exception\Exception] AclNode::node() - Couldn't find Aros node identified by "Array
(
    [Aros0.model] => Usergroups
    [Aros0.foreign_key] => 1
)
" in /opt/openitc/frontend/vendor/cakephp/acl/src/Model/Table/AclNodesTable.php on line 185
Request URL: /users/login
Referer URL: https://xxx/users/login
Client IP: xxx.xxx.xxx.xxx

Due to the reason that I was unable login and always get "invalid user / password" after upgrade I've already proceed the steps in wiki (resetting user pws & set all accounts to active = 1).
But unfortunately now I'm getting 500 error with message above.

**Comment by ibering** [comment]
Hi @W7T2A,

Please execute following statement:

`UPDATE aros SET model="Usergroups";`

Best regards

Irina

**Comment by W7T2A** [comment]
Thanks @ibering 
that fixed my login issue.

I've got one more error message related to statusengine:

error: [MissingDatasourceConfigException] The datasource configuration "legacy" was not found in database.php
Aug 19 12:36:36 yms.schneemenschen.local statusengine[23622]: error: Exception Attributes: array (
Aug 19 12:36:36 yms.schneemenschen.local statusengine[23622]: error:   'config' => 'legacy',
Aug 19 12:36:36 yms.schneemenschen.local statusengine[23622]: error: )
Aug 19 12:36:36 yms.schneemenschen.local statusengine[23622]: error: Stack Trace:
Aug 19 12:36:36 yms.schneemenschen.local statusengine[23622]: error: #0 /opt/openitc/statusengine2/cakephp/lib/Cake/Model/ConnectionManager.php(91): ConnectionManager::_getConnectionObject('legacy')
Aug 19 12:36:36 yms.schneemenschen.local statusengine[23622]: error: #1 /opt/openitc/statusengine2/cakephp/lib/Cake/Model/Model.php(3646): ConnectionManager::getDataSource('legacy')
Aug 19 12:36:36 yms.schneemenschen.local statusengine[23622]: error: #2 /opt/openitc/statusengine2/cakephp/lib/Cake/Model/Model.php(1162): Model->setDataSource('legacy')
Aug 19 12:36:36 yms.schneemenschen.local statusengine[23622]: error: #3 /opt/openitc/statusengine2/cakephp/lib/Cake/Model/Model.php(3673): Model->setSource('objects')
Aug 19 12:36:36 yms.schneemenschen.local statusengine[23622]: error: #4 /opt/openitc/statusengine2/cakephp/app/Console/Command/StatusengineLegacyShell.php(3205): Model->getDataSource()
Aug 19 12:36:36 yms.schneemenschen.local statusengine[23622]: error: #5 /opt/openitc/statusengine2/cakephp/app/Console/Command/StatusengineLegacyShell.php(3238): StatusengineLegacyShell->createChild(Array)
Aug 19 12:36:36 yms.schneemenschen.local statusengine[23622]: error: #6 /opt/openitc/statusengine2/cakephp/app/Console/Command/StatusengineLegacyShell.php(273): StatusengineLegacyShell->forkWorker()
Aug 19 12:36:36 yms.schneemenschen.local statusengine[23622]: error: #7 /opt/openitc/statusengine2/cakephp/lib/Cake/Console/Shell.php(462): StatusengineLegacyShell->main()
Aug 19 12:36:36 yms.schneemenschen.local statusengine[23622]: error: #8 /opt/openitc/statusengine2/cakephp/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('-w', Array)
Aug 19 12:36:36 yms.schneemenschen.local statusengine[23622]: error: #9 /opt/openitc/statusengine2/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
Aug 19 12:36:36 yms.schneemenschen.local statusengine[23622]: error: #10 /opt/openitc/statusengine2/cakephp/app/Console/cake.php(47): ShellDispatcher::run(Array)
Aug 19 12:36:36 yms.schneemenschen.local statusengine[23622]: error: #11 {main}

Any tipps how to fix?

**Comment by ibering** [comment]
Which OS are you on? If it's Debian Buster there was a package missing in the Repository which could cause issues during the Upgrade. Your system also wants to use Statusengine2 which had ben replaced by Statusengine3. Is the package `openitcockpit-statusengine3-worker` installed on your system?
Did you noticed any error messages while the upgrade was running? Did your MySQL password stored at `/etc/openitcockpit/mysql.cnf` contain any special characters?

My guess build be that the UPGRADE script (https://github.com/it-novum/openITCOCKPIT/blob/development/bin/scripts/UPGRADE.sh) had any errors on your system. You could try to execute the script manually.

**Comment by W7T2A** [comment]
Ya indeed I'm running Debian Buster.
After manually installing openitcockpit-statusengine3-worker and execute UPGRADE.sh script everything working as expected now.

Thanks for your help!
