### ISSUE TITLE
container permission issue with service template groups

### ISSUE THREAD

**Issue by exa-mk** [it-novum/openITCOCKPIT#1046]
i have containers like the following:
`/root`
`/root/department1`
`/root/department1/team1`
`/root/department1/team2`
etc.

all my own service templates are in `/root/department1`, all my actual hosts as well as their hostsgroups are in `/root/department1/team1`. now i created a service template group (STG) to apply a service check to all hosts of a hostgroup. when i create the STG (in the `/root/department1` container) it doesn't offer me the checkbox to add the service. 

only if the service template is completely up in the `/root` container it offers me to add the checks. i think this might be a bug checking permissions within the container hierarchy.

**Comment by nook24** [comment]
Resoved with Version 4.0.5: https://github.com/it-novum/openITCOCKPIT/releases/tag/openITCOCKPIT-4.0.5
