### ISSUE TITLE
agent qemu-check dependency issue

### ISSUE THREAD

**Issue by exa-mk** [it-novum/openITCOCKPIT#1052]
The qemu check in the openitcockpit-agent executes a `ps` command piped trough an `awk` script. Unfortunately the `awk` script only works with `gawk`- not with `mawk` which is the default `awk` at least in current Debian (and therefore also e.g. Proxmox) systems.
Maybe add a dependency into the deb package or check for the right awk before and issue a warning?

**Comment by nook24** [comment]
Internal issue: https://project.it-novum.com/browse/OA-18

**Comment by nook24** [comment]
`gawk` get added as dependency on linux systems

https://github.com/it-novum/openitcockpit-agent/commit/f88eeb3dd2c6c9883ffdcc3891e1d2b98444a85c
https://github.com/it-novum/openitcockpit-agent/commit/b277423f54897ed74753793d1bca159da4ecd005

This change will be available with openITCOCKPIT Agent 1.0.5
