### ISSUE TITLE
agent missing windows_services

### ISSUE THREAD

**Issue by exa-mk** [it-novum/openITCOCKPIT#1053]
Yesterday I tried the agent on Windows systems for the first time. In general it works fine, but it seems to miss some windows services, e.g. NTDS, KDC - is this a permissions problem?

Also some services (e.g. W32Time) always return red even if running correctly. Maybe the matching on the running binary is not the best choice, as many services use the same inbuilt helper binaries (e.g. `lsass.exe` or `svchost.exe`) - I'd suggest changing this to the actual service shortnames.

**Comment by Terminator81** [comment]
I can confirm this 

About half of the services are not recognized

**Comment by m4ximum** [comment]
Hello, @exa-mk and @Terminator81 
there was an filter function in openITCOCKPIT itself which filtered out many services, this behavior has now been changed and will be part of the upcoming version. Also there will be a new Agent version soon wich gives more information about processes like "svchost.exe"
