### ISSUE TITLE
openITCOCKPIT Agent Discovery should only list running services

### ISSUE THREAD

**Issue by Terminator81** [it-novum/openITCOCKPIT#1055]
is it possible to display only the running services in the configuration?

here would be the corresponding powershell query

`Get-Service | select -property name,starttype,status,DisplayName | ?{$_.Status -like 'Running'}`

maybe with a switch? for the customers who still want to monitor the inactive services (the sense of this is not apparent to me)

**Comment by Terminator81** [comment]
are you working on this too?

**Comment by nook24** [comment]
It's in the backlog for now, first priority is to resolve the connectivity issues.

**Comment by nook24** [comment]
This will be added with the releases of the openITCOCKPIT Monitoring Agent 3.0

**Comment by nook24** [comment]
Today we launched the public beta of the openITCOCKPIT Monitoring Agent 3.0. Please see this blog post for more information:
https://openitcockpit.io/2021/2021/04/14/openitcockpit-monitoring-agent-3-0-public-beta/

Version 3.0 should resolve your issue. Please report any issues with Version 3.x into this issue: https://github.com/it-novum/openitcockpit-agent-go/issues/47
