### ISSUE TITLE
Checkmk discovery not able to add heartbit_crm processes

### ISSUE THREAD

**Issue by lintuxido** [it-novum/openITCOCKPIT#1059]
When running checkmk discovery, it able to discover cluster services but saying to create new service as mentioned below,
"More services available
Before you are able to monitor the following services, it is required that an appropriate service template has been created. "

![2020-09-17 17_52_08-Monitoring powered by openITCOCKPIT](https://user-images.githubusercontent.com/29276308/93470401-7cb0ab00-f90f-11ea-8e11-f6e4cded21a2.png)

I am not able to create heartbeat crm service :(, could you please guide how can I add crm cluster services in monitoring. 
I have checked it in Check_MK RAW edition tool and it was working fine there but not working in OpenITCOCKPIT, I know that I have to create service to monitor it but not able to create service, I want to know which template, command and parameters I should have to use to get it work.

**Comment by ibering** [comment]
Hi @lintuxido,

It is described in detail on this page ;)

https://openitcockpit.io/beginners/10-monitoring-through-snmp_via_check_mk/

Section: **Create missing service templates for Checkmk**

Best regards 
Irina

**Comment by lintuxido** [comment]
@ibering - Thanks for sharing the details, will check and try to get it done. :)

**Comment by nook24** [comment]
Hi @lintuxido 
Was the documentation helpful for you? If yes i would ask you to close down the issue. Otherwise please let us know.

**Comment by lintuxido** [comment]
Hi @nook24,

Yes, it was helpful. Able to create template and add heartbeat_crm services in monitoring.

You may close the incidence, thanks for the help.
