### ISSUE TITLE
Suchfeld Frontend

### ISSUE THREAD

**Issue by 7845258** [it-novum/openITCOCKPIT#1060]
Hi,

Wir haben openITCOCKPIT in der Version 4.0.5 auf Ubuntu 20.04.1 LTS am laufen.
Installiert nach der Anleitung:  https://openitcockpit.io/download_server/

Problem:
Die Suche geht nicht, gibt man einen Suchbegriff, im Suchfeld (oben beim Frontend, Tippe zum Suchen) ein dreht der Punktkreis, aber leider kein Suchergebnis.

Mit verschiedenen Browsern und mit Cache leeren versucht, leider ohne Erfolg, die Suche bleibt immer erfolglos.

Danke für die Hilfe.

**Comment by nook24** [comment]
Hallo @7845258 dies passiert wenn als Sprache nicht englisch ausgewählt wurde. Der Fehler wurde hier behoben: https://github.com/it-novum/openITCOCKPIT/commit/c0bcaf693aa7575bc1d5cc64bcdc87ef2d9f34ca und der Patch wird mit der nächsten Version ausgerollt.

**Comment by 7845258** [comment]
@nook24 Perfekt, vielen Dank.
