### ISSUE TITLE
agent / avoid backslash in autogenerated check names

### ISSUE THREAD

**Issue by exa-mk** [it-novum/openITCOCKPIT#1062]
E.g. the disk usage check are created with the "mountpoint" in the service name, which means especially under windows something like "C:\\". If this service check name is passed to e.g. a custom notification script then it won't run properly because the backslash \ is interpreted as an escape sequence.

Please remove trailing backslashes from autogenerated service check names and/or replace then with slashes or sth similar.

**Comment by nook24** [comment]
Hi @exa-mk, 
the recommended method is to pass the service UUID `$SERVICEDESC$` to your notification script and query the service name from the database. This also avoids issues with `&`, `|` etc...

```bash
#!/bin/bash

ServiceUUID=$1

ServiceName=$(mysql --defaults-file=/opt/openitc/etc/mysql/mysql.cnf -e "SELECT IF(services.name IS NULL, servicetemplates.name, services.name) AS servicename FROM services INNER JOIN servicetemplates ON servicetemplates.id = services.servicetemplate_id WHERE services.uuid='${ServiceUUID}'" -B -s 2>/dev/null)

echo $ServiceName;
```

![Bildschirmfoto 2020-09-30 um 07 45 02](https://user-images.githubusercontent.com/9019992/94647781-7fd56f00-02f1-11eb-8d02-da133022c8cd.png)

**Comment by exa-mk** [comment]
@nook24 : I didn't do this so far to keep my notifications easy and simple with no further dependencies, but I agree that's a solution.
nevertheless I'd suggest to at least remove trailing backslashes 'C:\\' - as windows mountpoints usually are root directories and a service named "Disk Usage C:" is as good as 'Disk Usage C:\\'.

for other special characters you're also right but I don't see them appearing in any service name - especially not an autogenerated one.

**Comment by nook24** [comment]
With Version 3.x of the Agent, Windows Disks will create as `C:` like Windows Explorer also display drives.

**Comment by nook24** [comment]
Today we launched the public beta of the openITCOCKPIT Monitoring Agent 3.0. Please see this blog post for more information:
https://openitcockpit.io/2021/2021/04/14/openitcockpit-monitoring-agent-3-0-public-beta/

Version 3.0 should resolve your issue. Please report any issues with Version 3.x into this issue: https://github.com/it-novum/openitcockpit-agent-go/issues/47
