### ISSUE TITLE
docker checks only works with ce versions

### ISSUE THREAD

**Issue by exa-mk** [it-novum/openITCOCKPIT#1074]
According to the code the agent docker check does run:
```
# docker stats --no-stream --format "stats;{{.ID}};{{.Name}};{{.CPUPerc}};{{.MemUsage}};{{.MemPerc}};{{.NetIO}};{{.BlockIO}};{{.PIDs}}"
```
On a host with docker-ce 19.x the output is "correct"...
```
stats;f41d9f7b0e01;guacamole;0.48%;234MiB / 3.83GiB;5.97%;16.1GB / 34.6GB;129MB / 0B;53
```
... to be compared with the output of the following command:
```
# docker container list -a -s --format "cl;{{.ID}};{{.Status}};{{.Size}};{{.Image}};{{.RunningFor}};{{.Names}}"
cl;f41d9f7b0e01;Up 3 weeks;1.82GB (virtual 2.31GB);guacamole/guacamole;4 months ago;guacamole
```

However, if you use docker 1.13.x (e.g. shipped with CentOS 7) the output of the first command looks like this...
```
stats;0cca22dfa1e85a2504f11e818fbbd044bd2f64126aed844c53bd6974e2639934;guacamole;1.40%;260.6 MiB / 3.856 GiB;6.60%;47.7 MB / 3.84 GB;239 MB / 0 B;63
```
...so the agent struggles matching the long ids with the short ones from the second command and therefore the docker check fails.

**Comment by nook24** [comment]
Today we launched the public beta of the openITCOCKPIT Monitoring Agent 3.0. Please see this blog post for more information:
https://openitcockpit.io/2021/2021/04/14/openitcockpit-monitoring-agent-3-0-public-beta/

Version 3.0 should resolve your issue. Please report any issues with Version 3.x into this issue: https://github.com/it-novum/openitcockpit-agent-go/issues/47
