### ISSUE TITLE
after update to openitc 4.1.0 the agent overview page is weird

### ISSUE THREAD

**Issue by exa-mk** [it-novum/openITCOCKPIT#1078]
after updating my openitc server from 4.0.5 to 4.1.0 the agent overview page is kind of weird:
it shows every agent host multiple times and even the previously trusted ones are only shown trusted once (at the end of the now >20 pages list) and all other appearances are untrusted.

btw: a sorting possibility on this page would also be appreciated.

**Comment by nook24** [comment]
Hi @exa-mk that was my bad :(

Here's a patch: https://github.com/it-novum/openITCOCKPIT/commit/56eb6ede158da98200ebcb5284227667d080762e
There will also be a new release available soon, which resolves the issue.
