### ISSUE TITLE
Agent connection timed out

### ISSUE THREAD

**Issue by binsky08** [it-novum/openITCOCKPIT#1081]
Seit mittlerweile 3 Stunden (06:11 Uhr) meldet openITCOCKPIT (4.0.5) für den Service OITC_AGENT_ACTIVE
`
UNKNOWN: cURL error 28: Connection timed out after 10000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
`.
Auch ein manueller Aufruf der Agent API Url führt zu einer Netzwerk-Zeitüberschreitung.

Interessant ist, dass das Problem ca 11-12 Stunden nachdem ich den Agent aktualisiert habe, aufgetaucht ist.
Vorher Version 1.0.4, keine Probleme.
Jetzt Version 1.0.6, nach 12 Stunden kaputt.

Agent System: Debian 10

Service status inklusive der letzten Syslog Einträge (09:35 Uhr):
```
# systemctl status openitcockpit-agent
● openitcockpit-agent.service - openITCOCKPIT Monitoring Agent
   Loaded: loaded (/lib/systemd/system/openitcockpit-agent.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-10-26 19:13:36 CET; 14h ago
     Docs: https://openitcockpit.io
 Main PID: 1601 (openitcockpit-a)
    Tasks: 5 (limit: 4915)
   Memory: 107.1M
   CGroup: /system.slice/openitcockpit-agent.service
           ├─1601 /usr/bin/openitcockpit-agent-python3.linux.bin --config /etc/openitcockpit-agent/config.cnf
           └─1625 /usr/bin/openitcockpit-agent-python3.linux.bin --config /etc/openitcockpit-agent/config.cnf

Okt 27 09:12:58 *hostname* openitcockpit-agent-python3.linux.bin[1601]: run systemdservices
Okt 27 09:12:58 *hostname* openitcockpit-agent-python3.linux.bin[1601]: run dockerstats
Okt 27 09:12:58 *hostname* openitcockpit-agent-python3.linux.bin[1601]: Start docker status check with timeout of 30s at 1603786286
Okt 27 09:12:58 *hostname* openitcockpit-agent-python3.linux.bin[1601]: run systemdservices
Okt 27 09:12:58 *hostname* openitcockpit-agent-python3.linux.bin[1601]: run dockerstats
Okt 27 09:12:58 *hostname* openitcockpit-agent-python3.linux.bin[1601]: Start docker status check with timeout of 30s at 1603786317
Okt 27 09:12:58 *hostname* openitcockpit-agent-python3.linux.bin[1601]: run systemdservices
Okt 27 09:12:58 *hostname* openitcockpit-agent-python3.linux.bin[1601]: run dockerstats
Okt 27 09:12:58 *hostname* openitcockpit-agent-python3.linux.bin[1601]: Start docker status check with timeout of 30s at 1603786348
Okt 27 09:12:58 *hostname* openitcockpit-agent-python3.linux.bin[1601]: run systemdservices
```

**Comment by binsky08** [comment]
Nachtrag:
Das Problem ist bei 3 von 3 Installationen (Debian 10 und Ubuntu 20.04) des Agents aufgetreten, immer ca. 10-15 Stunden nach dem Update auf die aktuelle Version (1.0.6)

**Comment by nook24** [comment]
Guten Morgen @binsky08 Danke für die Info.

**Comment by nook24** [comment]
Hallo @binsky08 
Tritt das Problem nach einem Neustart eigentlich erneut auf? Ich hatte deinen ersten Post so verstanden, dass nach einem einmaligen Neustart des Agenten das Problem behoben war.
Ich habe nochmal ein Debian Buster zu unserer Testumgebung hinzugefügt. Mal abwarten was passiert. Die Ubuntu Systeme (darunter auch 20.04) liefern im Pull und Push Modus seit über 8 Tagen durchgehend Daten.

Die Version 1.0.4 ist nur in unserem internen Archiv. Ich habe dir die Datei angehängt.
[openitcockpit-agent_1.0.4_amd64.deb.zip](https://github.com/it-novum/openITCOCKPIT/files/5492640/openitcockpit-agent_1.0.4_amd64.deb.zip)

**Comment by binsky08** [comment]
Interessant, ich habe derzeit ein System (Ubuntu 20), bei dem ich alle ca. 12 Stunden den Agent Service manuell neu starte (seit 3 Tagen).
Bei anderen Systemen, tritt das Problem nur sporadisch auf.

**Comment by nook24** [comment]
Wir haben heute die Public Beta für den openITCOCKPIT Monitoring Agent 2.0 gestartet.

Um die Stabilität weiter verbessern zu können, würden wir uns freuen, wenn du bei der Testphase mitmachst. Besonders wenn du im Moment von Verbindungsprobleme betroffen bist.

Alle Informationen und eventuelle Fehler können hier gefunden und gemeldet werden: https://github.com/it-novum/openitcockpit-agent/issues/43

**Comment by nook24** [comment]
Today we launched the public beta of the openITCOCKPIT Monitoring Agent 3.0. Please see this blog post for more information:
https://openitcockpit.io/2021/2021/04/14/openitcockpit-monitoring-agent-3-0-public-beta/

Version 3.0 should resolve your issue. Please report any issues with Version 3.x into this issue: https://github.com/it-novum/openitcockpit-agent-go/issues/47
