### ISSUE TITLE
openitc updates overwriting config files

### ISSUE THREAD

**Issue by exa-mk** [it-novum/openITCOCKPIT#1082]
I set some custom configs... e.g.:
- /opt/openitc/etc/carbon/carbon.conf: 
```WHISPER_FALLOCATE_CREATE  = False``` (because I exported the whisper data files to a CephFS for space reasons)
- /opt/openitc/frontend/config/gearman.php:
```        'worker'     => 50,``` (because with the default of 5 workers the jobs are piling up and never get done (~300 hosts, ~9000 services)

On every update the settings get overwritten. Can you please change your updates to not reset custom set values?

**Comment by nook24** [comment]
Hi @exa-mk 
`WHISPER_FALLOCATE_CREATE` can be set via `Config file editor` => `/opt/openitc/docker/container/graphing/docker-compose.yml`

The amount of workers for the gearman worker is unfortunately missing at the moment. I will create a Feature Request for this.

**Comment by exa-mk** [comment]
@nook24 :
Thanks a lot. Never used the config file editor... too much of a console guy ;)
Maybe you also want to add `pm.max_children` from _/etc/php/7.4/fpm/pool.d/oitc.conf_ into your Feature Request?

**Comment by nook24** [comment]
Tracked by ITC-2437 and ITC-2438

**Comment by nook24** [comment]
Fixed with openITCOCKPIT 4.2
