### ISSUE TITLE
Everytime after adding a new service or host I loose all my grafana graphs - oITC 4.1.1 CE

### ISSUE THREAD

**Issue by MaLi187** [it-novum/openITCOCKPIT#1084]
Hi,

I dont know since when this happens, but I realized this a couple days ago. After renewing the configuration i.e. adding a new host or service I have blank grafana graphs. I would add some logs, but I can't find any errors.

Regards,
Matthias

**Comment by exa-mk** [comment]
It seems, I have the same issue. The data is there (as you can see in the service overview page) but Grafana is showing only empfy graphs:
![image](https://user-images.githubusercontent.com/69202794/98652590-2888dc80-233c-11eb-94ef-dd413a0f49a5.png)
![image](https://user-images.githubusercontent.com/69202794/98652653-42c2ba80-233c-11eb-9c22-b76951ccb148.png)

**Comment by MaLi187** [comment]
I even loose the graphs in the service overview, but in the history I still have all of the performance data. At around 7:40 I was renewing the config.

![image](https://user-images.githubusercontent.com/74232705/98653634-8c5fd500-233d-11eb-8e43-72d2c004cfda.png)

![image](https://user-images.githubusercontent.com/74232705/98653937-efea0280-233d-11eb-93ff-494c1471ec8c.png)

**Comment by ibering** [comment]
Hi @MaLi187,
Hi @exa-mk 

can you reproduce this bug on our [demo system](https://demo.openitcockpit.io/)

Best regards
Irina

**Comment by exa-mk** [comment]
@ibering : Yes:

![image](https://user-images.githubusercontent.com/69202794/98665780-65f56600-234c-11eb-9811-25274c5c7e69.png)

**Comment by ibering** [comment]
Can you please paste the link of the host you edited?

mysql host works for me:
![Bildschirmfoto 2020-11-10 um 12 03 55](https://user-images.githubusercontent.com/9592910/98666170-e9af5280-234c-11eb-9f5a-0f6956e53153.png)


https://demo.openitcockpit.io/#!/hosts/browser/12

**Comment by MaLi187** [comment]
> Hi @MaLi187,
> Hi @exa-mk
> 
> can you reproduce this bug on our [demo system](https://demo.openitcockpit.io/)
> 
> Best regards
> Irina

No, I can't. Are there any logs I can check about grafana? On my system not on the demo

**Comment by MaLi187** [comment]
The only thing I tried a couple days ago, was to get a UDP/Port check to work. It was working in the console but wasn't in oITC, I think after trying to get it to work the grafana problem startet. But this is only vague assumption.

The check was looking like this 
`./check_udp -H 1.2.3.4 -p 1194 -s $38$01$00$00$00$00$00$00$00 -e ^@^@^@^@^@ -M ok -t 5`

**Comment by exa-mk** [comment]
@ibering :
I didn't edit anything, just opened the Grafana tab. 
But it seems in my case to be a browser issue with Firefox, because Chrome is working.

**Comment by AndiMacTen** [comment]
Thank you very much for reporting the same issue. I was going to open a ticket regarding this soon. Today my our performance data got lost right at the moment when a colleague added a new service. That's a pity since I need the graphs for reporting.

**Comment by nook24** [comment]
Could you please provide a detailed step by step description how to reproduce the issue? Are you using the Docker Grafana or an external Grafana installation?
Please also add detailed information about your used browser and OS.

I was not able to reproduce this issue by creating a new host or service.
Tested with:
- Firefox 82.0.2 on macOS 10.15.7
- Google Chrome 86.0.4240.193 on macOS 10.15.7
- openITCOCKPIT 4.1.1 (https://demo.openitcockpit.io/)

Also check the browsers dev console for errors: (Please make sure display errors is enabled):
![Bildschirmfoto 2020-11-10 um 12 57 42](https://user-images.githubusercontent.com/9019992/98671374-70b3f900-2354-11eb-884d-191ac542f92d.png)

My Grafana Version is 7.2.2. You can check this by pressing ESC in the Grafana frame to open the menus
![Bildschirmfoto 2020-11-10 um 12 58 52](https://user-images.githubusercontent.com/9019992/98672173-ac9b8e00-2355-11eb-9646-42286c2fb0a2.png)

**Comment by MaLi187** [comment]
Succesfully reproduced. Take a look to your demo.

What I did:
- Created the check I mentioned and deleted it again (Don't think that it is needed)
- Changed the language to German and the reloaded the config, after that all was gone

**Comment by nook24** [comment]
Looks like deleting services is a bad idea 😟
The system will drop all performance data of the host. We will fix this.

**Comment by AndiMacTen** [comment]
I just sent more information regarding this to your support team. Feel free to contact me in case you are not able to reproduce on your end.

**Comment by MaLi187** [comment]
Not only of the hosts where the service got deleted, all services of all hosts loose the performance data graphs. Luckily only the graphs and not the performance data it self.

**Comment by nook24** [comment]
Build of a hotfixed version is running:
![status](https://drone.openitcockpit.io/buildStatus/icon?job=openitcockpit-packages%2Fstable&style=flat-square)

**Comment by nook24** [comment]
openITCOCKPIT 4.1.2 got released which resolves the issue

**Comment by MaLi187** [comment]
Thank you very very much for the quick solution. One question, is it possible to get the old lost perf data back to grafana?

Regards

**Comment by nook24** [comment]
Best case scenario would be to restore a backup of `/var/lib/graphite/whisper/openitcockpit`.

Otherwise you could hack a script which fetches the records from the `statusengine_servicechecks` table.
By default it will only keep the service checks of the last two weeks.

You could use our [PerfdataParser.php](https://github.com/it-novum/openITCOCKPIT/blob/development/src/Statusengine/PerfdataParser.php) and send the data back to Graphite/Carbon like so: https://github.com/it-novum/random-metric-generator/blob/master/src/itnovum/metrics/generator/Backends/Graphite.php

**Comment by MaLi187** [comment]
I think it is not resolved completley, today I lost all the graphs again. This time, I think it was after renewing the config and disabling/deleting a maintenance window.

**Comment by MaLi187** [comment]
> I think it is not resolved completley, today I lost all the graphs again. This time, I think it was after renewing the config and disabling/deleting a maintenance window.

Forget it, was a mistake from my side.
