### ISSUE TITLE
Upgrade from 3.7.3 not work

### ISSUE THREAD

**Issue by matfil92** [it-novum/openITCOCKPIT#1087]
I've follow the guide for upgrade from version 3 to version 4. 

I've followed from debian 9 and from ubuntu 18 and 16 but I've always same problem.
I've followed step by step without any error till the step on where change password. 
The web interface not work and if I try to reset password I've this error.

Anyone have this issue?
root@mon1:~# /opt/openitc/frontend/system/usr/bin/oitc reset_password --print --enable
PHP Warning:  file_get_contents(/opt/openitc/etc/mysql/mysql.cnf): failed to open stream: No such file or directory in /opt/openitc/frontend/src/itnovum/openITCOCKPIT/Database/MysqlConfigFileParser.php on line 9
PHP Notice:  Undefined index: host in /opt/openitc/frontend/config/datasource.php on line 11
PHP Notice:  Undefined index: user in /opt/openitc/frontend/config/datasource.php on line 18
PHP Notice:  Undefined index: password in /opt/openitc/frontend/config/datasource.php on line 19
PHP Notice:  Undefined index: database in /opt/openitc/frontend/config/datasource.php on line 20
PHP Notice:  Undefined index: host in /opt/openitc/frontend/config/datasource.php on line 48
PHP Notice:  Undefined index: user in /opt/openitc/frontend/config/datasource.php on line 50
PHP Notice:  Undefined index: password in /opt/openitc/frontend/config/datasource.php on line 51
PHP Notice:  Undefined index: database in /opt/openitc/frontend/config/datasource.php on line 52
Exception: Connection to Mysql could not be established: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)
In [/opt/openitc/frontend/vendor/cakephp/cakephp/src/Database/Driver.php, line 140]

2020-11-15 20:04:53 Error: [Cake\Database\Exception\MissingConnectionException] Connection to Mysql could not be established: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) in /opt/openitc/frontend/vendor/cakephp/cakephp/src/Database/Driver.php on line 140
Stack Trace:
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Database/Driver/Mysql.php:178
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Database/Schema/SchemaDialect.php:47
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Database/Driver/Mysql.php:230
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Database/Schema/Collection.php:53
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Database/Connection.php:399
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/ORM/Table.php:508
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/ORM/Query.php:277
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/ORM/Query.php:177
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/ORM/Table.php:1679
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/ORM/Table.php:1261
- /opt/openitc/frontend/src/Command/ResetPasswordCommand.php:104
- /opt/openitc/frontend/src/Command/ResetPasswordCommand.php:78
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Console/BaseCommand.php:179
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Console/CommandRunner.php:335
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Console/CommandRunner.php:171
- /opt/openitc/frontend/bin/cake.php:12

Caused by: [PDOException] SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) in /opt/openitc/frontend/vendor/cakephp/cakephp/src/Database/Driver.php on line 132
Stack Trace:
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Database/Driver.php:132
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Core/Retry/CommandRetry.php:70
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Database/Driver.php:138
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Database/Driver/Mysql.php:178
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Database/Schema/SchemaDialect.php:47
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Database/Driver/Mysql.php:230
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Database/Schema/Collection.php:53
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Database/Connection.php:399
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/ORM/Table.php:508
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/ORM/Query.php:277
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/ORM/Query.php:177
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/ORM/Table.php:1679
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/ORM/Table.php:1261
- /opt/openitc/frontend/src/Command/ResetPasswordCommand.php:104
- /opt/openitc/frontend/src/Command/ResetPasswordCommand.php:78
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Console/BaseCommand.php:179
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Console/CommandRunner.php:335
- /opt/openitc/frontend/vendor/cakephp/cakephp/src/Console/CommandRunner.php:171
- /opt/openitc/frontend/bin/cake.php:12

**Comment by nook24** [comment]
Hi @matfil92,
is this issue still a thing or was ist just the same as in https://github.com/it-novum/openITCOCKPIT/issues/1086#issuecomment-728998358 ?
