### ISSUE TITLE
oitc agent not working (.../persistent/ is not writable)

### ISSUE THREAD

**Issue by some-git-user** [it-novum/openITCOCKPIT#1088]
Habe einen neuen Host erstellt und anschließend den Agent mittels Wizard hinzugefügt.
Bekomme jetzt folgenden Output beim Service "OITC_AGENT_ACTIVE":

Output:
`(No output on stdout) stderr: Warning Error: /opt/openitc/frontend/tmp/nagios/cache/nagios/persistent/ is not writable`

Long output:
```
In [/opt/openitc/frontend/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php, line 412]

Error: Unknown option `format`.
```

**Comment by ibering** [comment]
Hallo @some-git-user 

bitte führe folgenden Befehl  auf der Konsole aus `oitc rights`

**Comment by some-git-user** [comment]
Hallo @ibering 

hatte ich bereits versucht:
`Set filesystem permissions for user www-data to /opt/openitc/frontend/...    done!`

Anbei das Verzeichnis:
`drwxr-xr-x 2 www-data www-data 4.0K Apr 20  2020 `
`drwxr-xr-x 4 www-data www-data 4.0K Apr 20  2020 ..`
`-rw-rw-r-- 1 www-data www-data 205K Apr 20  2020 myapp_cake_core_translations.default.en_US`
`-rw-rw-r-- 1 www-data www-data 210K Apr 20  2020 myapp_cake_core_translations.oitc_console.en_US`

Und hier das Frontend:
![Screenshot_20201119_094739](https://user-images.githubusercontent.com/65288184/99642861-49dc7d80-2a4c-11eb-86b6-6621ea41a93e.png)

Hatte die Checks bereits gelöscht, neu angelegt und auch verschiedene Agent-Konfigurationen versucht.

**Comment by some-git-user** [comment]
Habe eben das Verzeichnis auf 777 gesetzt. Nun bekomme ich nur noch folgenden Output:

`Output | (No output on stdout) stderr: Error: Unknown option 'format'.`

Den Agenten habe ich auf dem Client mittlerweile beendet.

**Comment by ibering** [comment]
Hallo,

ich glaube, dass das Kommando für **Total CPU Percentage** fehlerhaft ist. Es klingt so, als ob ein Benachrichtigungskommando hinterlegt wurde. Weil es auch "format" als Parameter haben möchte (also text oder html). Welches Prüfkommando ist eingetragen, wenn man den Dienst im `edit` Modus bearbeitet?

**Comment by some-git-user** [comment]
Hatte mich auch gewundert. Habe nun wieder alle Checks gelöscht und per Wizard neu erstellt:
![Screenshot_20201119_153727](https://user-images.githubusercontent.com/65288184/99680438-5a591c00-2a7d-11eb-904a-3c9f966b66ab.png)

Nun kommt auch wieder der Service "OITC_AGENT_ACTIVE" mit der "Unknown option 'format'."-Meldung.

Anbei die Detailansicht:
![Screenshot_20201119_154036](https://user-images.githubusercontent.com/65288184/99680724-a86e1f80-2a7d-11eb-96ee-590c628f7a1b.png)

Unter "Check command" ist aber nichts eingetragen?

**Comment by ibering** [comment]
Unter Check command ist nichts eingetragen, weil da nur die Check Kommandos für Services angezeigt werden. Und wahrscheinlich ist in der Datenbank eine falsche ID (eines Benachrichtigungskommandos) eingetragen. Am besten die Servicevorlage per Hand korrigieren.

Hier die **OITC_AGENT_ACTIVE** Vorlage auf unserem Demosystem

https://demo.openitcockpit.io/#!/servicetemplates/edit/109

Leider kann ich nicht einschätzen, welche Servicevorlagen noch fehlerhaft sein könnten :/

**Comment by ibering** [comment]
```
SELECT servicetemplates.id, servicetemplates.name, commands.id, commands.command_type
FROM servicetemplates
JOIN commands ON commands.id = servicetemplates.command_id
WHERE commands.command_type !=1
;
```
Hier ein SQL Statement, welche nicht valides `Service Kommando` in einer Servicevorlage findet

**Comment by some-git-user** [comment]
Danke, das war's. Habe den Check angepasst und die Vorlage auch.
Aber keine Ahnung warum die Vorlage fehlerhaft war?

**Comment by ibering** [comment]
Schön das es geklappt hat :) Warum die Kommando-ID fehlerhaft war, weiß ich leider auch nicht :/
