### ISSUE TITLE
Event correlation disappears after editing event correlation host 

### ISSUE THREAD

**Issue by MaLi187** [it-novum/openITCOCKPIT#1091]
If you want to update the EVC Host, i.e. to change the description, the EVC disappears.

![image](https://user-images.githubusercontent.com/74232705/100341412-d226c980-2fdc-11eb-8a2c-3ad4c055e3d4.png)

It changes the template from "evc-host-template" to "host-template" and makes the host a generic host, also the evc-template is not available anymore.

Look at the demo system, and search for the host "EVC_Test" in the "not monitored" section. It is not possible to delete the host, because it is part of an EVC and at the EVC section it is not visible anymore.

Regards,
Matthias

**Comment by nook24** [comment]
Good catch. We will check this.

**Comment by ibering** [comment]
Hi @MaLi187

The bug has been fixed here: https://github.com/it-novum/openITCOCKPIT/commit/e97686fedae5bb30ca74920d57c9cd5e0da9d6fd and the patch will be rolled out with the next version.

Best regards
Irina

**Comment by MaLi187** [comment]
Great, thanks.

Regards
