### ISSUE TITLE
agent on windows hosts fails with strange docker error

### ISSUE THREAD

**Issue by exa-mk** [it-novum/openITCOCKPIT#1093]
On some windows hosts the agent checks fail regularly in different intervals with `UNKNOWN: Key xxx not found in Agent output`.
After a restart it works again (for a while).
I checked the push cache on a host in such a state which returns:
```
{
  "dockerstats": {
    "error": "Der Befehl \"docker\" ist entweder falsch geschrieben oder\r\nkonnte nicht gefunden werden.\r\nDer Befehl \"docker\" ist entweder falsch geschrieben oder\r\nkonnte nicht gefunden werden.\r\n",
    "returncode": 1
  }
}
```
As it is a windows host with no Docker installed at any point this shouldn't happen.

**Comment by nook24** [comment]
Issues related to the openITCOCKPIT Monitoring Agent should be created in the corresponding repository: https://github.com/it-novum/openitcockpit-agent/issues

Fetching status information of Docker can be disabled in the `config.cnf` of the agent.
```
# Try to check docker containers and return stats in default output
dockerstats = false
```

**Comment by nook24** [comment]
Today we launched the public beta of the openITCOCKPIT Monitoring Agent 3.0. Please see this blog post for more information:
https://openitcockpit.io/2021/2021/04/14/openitcockpit-monitoring-agent-3-0-public-beta/

Version 3.0 should resolve your issue. Please report any issues with Version 3.x into this issue: https://github.com/it-novum/openitcockpit-agent-go/issues/47
