### ISSUE TITLE
openITCockpit not working after Upgrading from Ubuntu 16.04 to 18.04

### ISSUE THREAD

**Issue by Tweak90** [it-novum/openITCOCKPIT#1103]
Hello,
we are using openITCOCKPIT for quite a while now and now I am trying to upgrade my Server from 16.04 to 18.04 to 20.04. 
And I would like to upgrade openITCOCKPIT from 3.7.3 to 4

After Upgrading from 16.04 to 18.04 I can not access openITCOCKPIT anymore.

Is there a best practice guide for upgrading distributions and openITCOCKPIT?

Regards

**Comment by nook24** [comment]
Hi @Tweak90,
of course: https://docs.it-novum.com/display/ODE/Upgrade+openITCOCKPIT+3.x+to+openITCOCKPIT+4.x 🙂

**Comment by Tweak90** [comment]
Hello @nook24,
thank you so much, worked!

Great product, great support!

**Comment by PVTGoesen** [comment]
Hi,
I encountered the same problem. But after resetting the password i can't logon: Unknown Error. 

/opt/openitc/frontend/logs/error.log
`2021-01-15 16:56:18 Error: [Cake\Core\Exception\Exception] AclNode::node() - Couldn't find Aros node identified by "Array
(
    [Aros0.model] => Usergroups
    [Aros0.foreign_key] => 1
)
" in /opt/openitc/frontend/vendor/cakephp/acl/src/Model/Table/AclNodesTable.php on line 185
Request URL: /users/login
Referer URL: https://our.domain.de/users/login
Client IP: x.x.x.x`

**Comment by ibering** [comment]
Hi @PVTGoesen ,

Please execute following statement:

UPDATE aros SET model="Usergroups";

Best regards
Irina

**Comment by PVTGoesen** [comment]
Thanks for the fast answer,
this fixes the Issue.

**Comment by ibering** [comment]
You are welcome :)
