### ISSUE TITLE
Feature Request: Option to make ACKs silent

### ISSUE THREAD

**Issue by exa-mk** [it-novum/openITCOCKPIT#1106]
Can you please add a checkbox to the ACKNOWLEDGE function to disable the notifies? Especially when ACKing multiple hosts/services the bunch of notifies is really annoying.

Additional request to ACKs (way less important):
- Add an option to add an expiry date/time to ACKs (like Icinga1 had) if possible

**Comment by nook24** [comment]
The upcoming version can delete acknowledgements and it is also possible to disable the notifications while creating an acknowledgement.

Unfortunately it is not possible to add an expire data to acknowledgements. This is an Icinga 1 specific feature.

---

Internal Issues:

- ITC-345
- ITC-1239

**Comment by nook24** [comment]
This feature is part of openITCOCKPIT 4.2.2. Please see the changelog: https://github.com/it-novum/openITCOCKPIT/releases/tag/openITCOCKPIT-4.2.2
