### ISSUE TITLE
Repo Changed?

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1112]
root@xxxx:/etc/apt/sources.list.d# curl https://packages.openitcockpit.io/repokey.txt | apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
gpg: no valid OpenPGP data found.
root@xxxxxx:/etc/apt/sources.list.d#

**Comment by nook24** [comment]
Hi @infofrs,

looks like the CA certs are missing on your system.
Works on my side:
![Bildschirmfoto 2021-02-01 um 15 20 58](https://user-images.githubusercontent.com/9019992/106470868-4ed49900-64a1-11eb-88ae-ed468d4ff978.png)

![Bildschirmfoto 2021-02-01 um 15 22 51](https://user-images.githubusercontent.com/9019992/106470911-5dbb4b80-64a1-11eb-9cfb-287e0b69ffa3.png)

What OS are you using?

**Comment by infofrs** [comment]
Ubuntu 18.04 LTS

**Comment by infofrs** [comment]
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

**Comment by nook24** [comment]
Are you behind an Proxy server? If yes that's probably the root cause of the issue.

It also works from DigitalOcean so I guess it's something in your network.
![Bildschirmfoto 2021-02-01 um 15 42 11](https://user-images.githubusercontent.com/9019992/106473511-2601d300-64a4-11eb-8115-503005f2fe89.png)

**Comment by infofrs** [comment]
Strange:
curl https://packages.openitcockpit.io/repokey.txt | head -n 5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

I will check the url in the proxy

**Comment by nook24** [comment]
Did you find anything?

**Comment by infofrs** [comment]
No. Our Proxy did not trust your server cert. Do you have the cert and keychain for me?

**Comment by nook24** [comment]
Of course: https://gist.github.com/nook24/d333f17c2d450776529efbbe160fb680
Looks like your Proxy is pretty old :)

**Comment by infofrs** [comment]
If i add the pgp key manually as descriped i get the error: " gpg: no valid OpenPGP data found"

**Comment by nook24** [comment]
Unfortunately I don't know what's going on with your system but everything works as expected on all my test systems. I bet curl outputs a HTML page generated by your proxy server with an error message inside or your system clock is wrong AF.
```
[13:31]root@vm8664:~# curl https://packages.openitcockpit.io/repokey.txt | apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3159  100  3159    0     0   8824      0 --:--:-- --:--:-- --:--:--  8799
OK
```

The gpg key is also not expired.
Just open the url https://packages.openitcockpit.io/repokey.txt with your browser and copy&paste the key manually to your system.
You can than import it like
```
cat repo.key | apt-key add -
```

**Comment by infofrs** [comment]
The key is still there.....
 apt-key list
/etc/apt/trusted.gpg
--------------------
pub   rsa4096 2016-12-07 [SC]
      8907 DBFA D2E0 2071 77D7  EFEB 8CB4 2BEF 0727 83CB
uid           [ unknown] Oliver Mueller (it-novum) <oliver.mueller@it-novum.com>
sub   rsa4096 2016-12-07 [S]
sub   rsa4096 2016-12-07 [E]

pub   rsa4096 2020-02-25 [SC] [expires: 2040-02-20]
      97B1 36CB C858 8DE3 532A  776C 5B85 1275 D463 5BA3
uid           [ unknown] it-novum GmbH <support@itsm.it-novum.com>
sub   rsa4096 2020-02-25 [E] [expires: 2040-02-20]

/etc/apt/trusted.gpg.d/ubuntu-keyring-2012-archive.gpg
------------------------------------------------------
pub   rsa4096 2012-05-11 [SC]
      790B C727 7767 219C 42C8  6F93 3B4F E6AC C0B2 1F32
uid           [ unknown] Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>

But is it valid?

**Comment by nook24** [comment]
I can't find any issue on our side 😕. I would suggest you grab a VM on DigitalOcean, Hetzner cloud or any other and the issue will be gone.

**Comment by infofrs** [comment]
Solved. Needed to import some certs from our proxy/fw environment. Works now fine.
