### ISSUE TITLE
openitcockpit-module-grafana nicht löschbar

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1113]
im Installationsablauf war die / Partition vollgelaufen und der Installer abgebrochen. Das ist gefixed. Aber die Neuinstallation schlägt fehl. Ein Remove via apt-get remove openitcockpit{,-common,-naemon,-statusengine-naemon,-message}
 funktioniert nicht da sich das module openitcockpit-module-grafana nicht entsorgen lässt.
(Reading database ... 76667 files and directories currently installed.)
Removing openitcockpit-module-grafana (3.7.3-1ubuntu18.04) ...
/var/lib/dpkg/info/openitcockpit-module-grafana.postrm: line 15: oitc: command not found
dpkg: error processing package openitcockpit-module-grafana (--remove):
 installed openitcockpit-module-grafana package post-removal script subprocess returned error exit status 127
Errors were encountered while processing:
 openitcockpit-module-grafana
E: Sub-process /usr/bin/dpkg returned an error code (1)

Der oitc ist wohl schon deinstalliert obwohl hier noch benötigt. Wie fixen?

**Comment by nook24** [comment]
Es gibt bereits ein Issue dazu #1043
Vermutlich ist es das Beste nochmal auf einer frischen Maschine zu beginnen...
