### ISSUE TITLE
Admin-Anmeldung an Grafana

### ISSUE THREAD

**Issue by Terminator81** [it-novum/openITCOCKPIT#1114]
Hallo

ich möchte mich gerne am enthaltenen Grafana anmelden als Editor oder Admin.

aktuell werde ich bei Aufruf von /grafana direkt als Viewer angemeldet

ich möchte jedoch manche Grafen noch etwas anpassen.

Danke

**Comment by nook24** [comment]
Wenn du die Grafana Oberfläche über openITCOCKPIT aufrufst, wird immer der Benutzer genommen, welcher im HTTP Header enthalten ist.
Diesen kannst du in der Nginx Config anpassen `/etc/nginx/openitc/master.conf`:

https://github.com/it-novum/openITCOCKPIT/blob/598e342f0e2ef8cf8856a331f635d30624f2dac8/system/etc/nginx/openitc/master.conf#L85-L97

`proxy_set_header X-WEBAUTH-USER viewer; `

Im Standard stehen die Bentuzer `admin` und `viewer` zur Verfügung.

**Comment by Terminator81** [comment]
funktioniert :)
