### ISSUE TITLE
check_nrpe fehlt

### ISSUE THREAD

**Issue by ssy2011** [it-novum/openITCOCKPIT#1117]
Hallo zusammen,

ich habe hier auf einem Ubuntu Server 18.04 LTS die Community Edition 4.1.4 laufen und plane gerade, unsere uralte openITcockpit-Version 1.0 abzulösen...
Da wir auf dieser einige NRPE-Checks laufen haben, die ich nachbauen muss, habe ich das "LinuxBasicMonitoringModule" installiert.
Dieses bringt aber leider "check_nrpe" nicht mit, weswegen ich hier gerade festhänge.
Ist das "by design"? Oder ein Paketfehler? Oder geht das einfach noch nicht?

Vielen Dank für Eure Tipps!

Viele Grüße
Heiko

**Comment by nook24** [comment]
Hallo @ssy2011,
ich empfehle dir unseren _Beginners guide_, dieser behandelt auch das Monitoring via NRPE:  https://openitcockpit.io/beginners/5-monitoring-through-nrpe/

openITCOCKPIT Version 1.0 klingt spannend, wäre cool wenn du ein paar Screenshots posten könntest für unser Archiv 😌

**Comment by ssy2011** [comment]
Hallo @nook24,
ah, danke, _da_ steht das :-)
Da ist mir bei mLesen aufgefallen, dass unter "Install NRPE server on target host" ein ini-Format dargestellt ist, das zumindest unter Windows mit NSClient++-Versionen ab 0.4 nicht mehr funktioniert.
Beispiel: 
`command[check_time_sync_extern]=C:\NSClient++\scripts\check_windows_time.cmd ptbtime1.ptb.de 1 5`
müsste lauten
`check_time_sync_extern=cmd /c "C:\NSClient++\scripts\check_windows_time.cmd ptbtime1.ptb.de 1 5"`
Aber das wäre nicht die einzige Änderung. Die .ini-Struktur wurde komplett umgebaut.
Wie das aktuell mit neueren Linuxen ist, kann ich noch nicht sagen.

Screenshots kann ich gerne liefern :-) welche "aus dem Leben", aber auch die aus der Original-Doku.
Wohin dann, welche?
Viele Grüße!

**Comment by ssy2011** [comment]
Hallo @nook24,
kleiner Nachtrag noch: 

Die Doku sagt ja, NRPE sei so zu konfigurieren:
`/usr/lib/nagios/plugins/check_nrpe -H $HOSTADDRESS$ -c "$ARG1$"`

Die vielen coolen Kommandovorlagen sind aber bereits so konfiguriert:
`$USER1$/check_nrpe -H $HOSTADDRESS$ -c $ARG1$`

`sudo ln -s /usr/lib/nagios/plugins/check_nrpe /opt/openitc/nagios/libexec/check_nrpe` wäre an der Stelle vielleicht eine sinnvolle Ergänzung.

**Comment by nook24** [comment]
Hallo @ssy2011,

>Da ist mir bei mLesen aufgefallen, dass unter "Install NRPE server on target host" ein ini-Format dargestellt ist, das zumindest unter Windows mit NSClient++-Versionen ab 0.4 nicht mehr funktioniert.

In meinem Link wird nur das Monitoring eines Linux-Systems mit dem `nagios-nrpe-server` gezeigt. Deshalb funktioniert die Config nicht mit einem NSClient++. Es handelt sich dabei um zwei unabhängige Tools.

>`sudo ln -s /usr/lib/nagios/plugins/check_nrpe /opt/openitc/nagios/libexec/check_nrpe` wäre in der Doku vielleicht eine sinnvolle Ergänzung.

Gute Idee! Ich habe die Anleitung angepasst.

> Screenshots kann ich gerne liefern :-) welche "aus dem Leben", aber auch die aus der Original-Doku.

Das wäre klasse! Welche _aus dem Leben_ am besten. Hostnamen, IP-Adresse etc können natürlich unkenntlich gemacht werden.
Die Screenshots kanns du hier hochladen: https://cloud.it-novum.com/s/T2tsipH9FRkw75E. Passwort: `TM7QPdMs`. Die Freigabe läuft noch bis Sonntag.

Wir freuen uns immer über neues Material, wenn wir auf Twitter mal wieder etwas in Nostalgie schwelgen.
https://twitter.com/openITCOCKPIT/status/1260888180959649794
https://twitter.com/openITCOCKPIT/status/1334516875884105735 

Viele Grüße

Daniel
