### ISSUE TITLE
check_mk Limit in Anzahl der Checks

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1119]
Gibt es ein Limit wieivele Checks via check_mk verarbeitet werden können je Host??

![image](https://user-images.githubusercontent.com/44997840/108724740-f59ed900-7525-11eb-877c-0cf58c489502.png)

Nehme ich nur 20 Checks oder 50 funktioniert alles wie gewünscht.

**Comment by ibering** [comment]
Hallo @infofrs,

tritt das Problem immer ab 50 Checks auf? Gibt es eventuell eine Fehlermeldung vom aktiven check_mk Dienst? 

Also wir setzen keine Limits für check_mk Checks.

Viele Grüße 
Irina

**Comment by infofrs** [comment]
Das Problem tritt wohl ab und an auf wenn zuviele Checks aufeinmal etabliert wurden. Lösung. Die UNAVAILABLE Checks löschen und mit dem Discovery neu anlegen. Sieht danach alles  ok aus:
![image](https://user-images.githubusercontent.com/44997840/108813811-f9783d00-75b1-11eb-9d7f-f8b77a02eec8.png)
