### ISSUE TITLE
Minor bug showing service information in hostgroups

### ISSUE THREAD

**Issue by MaLi187** [it-novum/openITCOCKPIT#1133]
Go to a hostgroup, open extended view and click on one of the service summaries. Green, yellow, red, gray doesn't matter.

The page presented looks a little bit off :)

Screenshot from your demo system
![image](https://user-images.githubusercontent.com/74232705/110590095-9d97e180-8177-11eb-8210-d7888e5815df.png)

**Comment by m4ximum** [comment]
Hi @MaLi187 
thank you for reporting this issue!
This will be resolved with the upcoming version.
