### ISSUE TITLE
Altered Service Template not recognized

### ISSUE THREAD

**Issue by some-git-user** [it-novum/openITCOCKPIT#1144]
Ändert man bei einer bestehenden Servicevorlage die Anzahl der Argumente, werden diese Änderungen nicht in bestehende Services übertragen, sprich die Anzahl der Argumente bleibt gleich.
Im Beispiel wurde bei der Vorlage ein dritter Parameter hinzugefügt, der bestehende Service kennt aber diesen neuen, dritten Parameter "TOKEN_FILE" nicht.

Geänderte Servicevorlage: 
![image](https://user-images.githubusercontent.com/65288184/112286939-22145500-8c8c-11eb-8aa6-2f069f6078f6.png)

Bestehender Service:
![image](https://user-images.githubusercontent.com/65288184/112287388-9c44d980-8c8c-11eb-9fdb-d5bf63602b9f.png)

Auch ein Export bringt keine Änderung.

**Comment by ibering** [comment]
Hallo @some-git-user,

welche openITCOCKPIT Version ist im Einsatz? 
Ich konnte das Problem auf dem [demo](https://demo.openitcockpit.io) System leider nicht nachstellen

https://demo.openitcockpit.io/#!/services/edit/234

Viele Grüße
Irina

**Comment by some-git-user** [comment]
Hallo @ibering,

Version 4.1.4, wie auf dem Demosystem. Laut apt existiert auch kein Update.

Stimmt, auf eurem Demosystem kann ich das Problem nicht reproduzieren.
Habe es eben nochmal bei uns getestet, dort funktioniert es nicht.

1. Ich füge dem "Command" ein neues Argument hinzu.
2. Prüfe nun das verknüpfte "Service Template", hier ist das neue Argument automatisch vorhanden.
3. Prüfe nun einen bestehenden Service, der zum Service Template gehört. Hier taucht das neue Argument nicht auf.
4. Wenn ich einen neuen Service, der zum Service Template gehört, anlege, dann taucht das neue Argument auf. 
    Bei bestehenden Services jedoch nicht.

Gibt es Logs die vielleicht helfen?

**Comment by ibering** [comment]
Hallo @some-git-user,

ich glaube, dass ich die Ursache für das Problem gefunden. Die Argumente vom Service wurden wahrscheinlich angepasst. Das erkennt man am roten Viereck rechts. Damit hat Service "eigene" Argumente und die aus des Vorlage werden ignoriert. Aber eigentlich, müssten die neuen Argumente dazu geladen werden. Das ist wahrscheinlich ein Bug. 

Viele Grüße
Irina

**Comment by ibering** [comment]
Hallo @some-git-user,

der Fehler wurde behoben und ist ab der nächsten Version nicht mehr vorhanden. Aktuelle Version kann mit diesem Patch korrigiert werden  #1145

Viele Grüße und noch ein schönes Wochenende
Irina

**Comment by nook24** [comment]
Fixed with openITCOCKPIT 4.2
