### ISSUE TITLE
CPAN Modul Expect

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1147]
Wie wird in OITC o.g. Perl Modul nachinstalliert wenn ein 
- perl -MCPAN -e shell
- install expect
nicht geht da der Proxy CPAN Servern nicht vertraut?

Grund: Testlauf für ein Perl Script Richtung SVC Storage Controller
https://github.com/shipik/svc-monitor

Gibt es Erfahrungen/Empfehlungen für solche Perl Modul Geschichten?

**Comment by nook24** [comment]
Mit der Installation von Perl-Modulen hat openITCOCKPIT erst einmal nichts am Hut. Dies Funktioniert wie auf jedem anderen Linux auch.
Ich würde empfehlen zu versuchen alle Abhängigkeiten über apt zu installieren. In der Regel gibt es dort fast alle cpan Abhängigkeiten, man muss nur etwas suchen.

>install expect
> nicht geht da der Proxy CPAN Servern nicht vertraut?

Klingt nach Proxy Server fixen? :) Du hattest dort in der Vergangenheit ja schon einmal Probleme mit: https://github.com/it-novum/openITCOCKPIT/issues/1112#issuecomment-772355868

**Comment by nook24** [comment]
Vermutlich suchst du: `apt-get install libexpect-perl`. Alternative gab es noch diese Module hier über apt (Ubuntu 20.04):

```
[10:09]root@agent-test/opt/openitc/receiver# apt-cache search perl | grep expect
libexpect-perl - Expect.pm - Perl Expect-Schnittstelle
libnet-scp-expect-perl - Wrapper für scp um Passwörter via Expect zu senden
libexpect-simple-perl - wrapper around the Expect module
libtest-expect-perl - module for automated driving and testing of terminal-based programs
```

**Comment by infofrs** [comment]
Ok.  Apt Package was ok. Thx
