### ISSUE TITLE
Host_Alive in GUI Rot, Auf Console grün

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1149]
Anzeigefehler oder Webserver ab und an buggy.
Auf Console: $USER1$/check_icmp -H IP -w 3000.0,80% -c 5000.0,100% -p 1 -> OK
In der GUI: RED

Server neu gestartet. Gleiches Verhalten?

Andere Hosts mit gleichem check_host_alive laufen alle ohne Probleme....

Workaround?

**Comment by ibering** [comment]
Hallo @infofrs,

wie sieht die _Command line_ Ausgabe im Host Browser (https://IP/#!/hosts/browser/ID) aus? Werden alle Argumente angezeigt (bzw. richtig ersetzt also **$ARG1$** und **$ARG2$**)?

![image](https://user-images.githubusercontent.com/9592910/113877487-08f5c300-97b9-11eb-891c-e8ecf8e1b8b6.png)

Wurde eventuell was am Kommando, Hostvorlage oder dem Host selbst an Argumenten geändert?

Viele Grüße
Irina

**Comment by infofrs** [comment]
Command line | $USER1$/check_icmp -H xxxxx -w 3000.0,80% -c 5000.0,100% -p 1
-- | --
Output | (No output returned from host check)

**Comment by ibering** [comment]
> Auf Console: $USER1$/check_icmp -H IP -w 3000.0,80% -c 5000.0,100% -p 1 -> OK

Wurde der Check mit dem **nagios** User ausgeführt?

**Comment by infofrs** [comment]
Lösung: Geduld. Heute früh ist auch dieser Host grün. Die Servicechecks waren eh alle grün.
