### ISSUE TITLE
OpenSuse OITC Agent - Richtiges Paket im WebInterface?

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1150]
Paket sieht nach falscher Plattform aus. Für welche Plattformen soll das RPM sein?

**Comment by nook24** [comment]
Das Paket ist für 64Bit Systeme (x86_64.rpm) und funktioniert in einem schnellen Test problemlos unter openSUSE 15.2
![Bildschirmfoto 2021-04-08 um 09 32 15](https://user-images.githubusercontent.com/9019992/114007151-61809b00-9861-11eb-9a27-68db2a1dd0f7.png)

PS: In ein paar Tagen startet auch die Beta für openITCOCKPIT 4.2 mit dem neuen Agent. Das Repository dafür ist sogar schon online: https://github.com/it-novum/openitcockpit-agent-go

**Comment by infofrs** [comment]
hab leider ein sles system. damit geht es dann nicht.

**Comment by nook24** [comment]
Der Agent 3.0 kann jetzt als Beta getestet werden, bestimmt interessant für dich :)

https://openitcockpit.io/2021/2021/04/14/openitcockpit-monitoring-agent-3-0-public-beta/
