### ISSUE TITLE
Service Type Anzeige

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1151]
Kann man in der Host und Serviceliste nicht das Feld "Service Type" anzeigen lassen bzw. auch "Satellite/Master". Ideal wäre es wenn man einige Spalten ab- und anwählen könnte.....

**Comment by nook24** [comment]
ITC-1105

**Comment by nook24** [comment]
Part of openITCOCKPIT 4.6.2
https://github.com/it-novum/openITCOCKPIT/releases/tag/openITCOCKPIT-4.6.2
