### ISSUE TITLE
API returns (400) Bad Request when JSON includes a umlaut

### ISSUE THREAD

**Issue by some-random-git-user** [it-novum/openITCOCKPIT#1160]
**Describe the bug**
Wenn ich ein JSON an die API sende, welches Umaute beinhaltet, bekomme ich immer einen Error: 400 Bad Request.
Über die Oberfläche kann ich aber Objekte, welche ein Umlaut beinhalten ohne Probleme ändern.

**To Reproduce**
1. JSON von einem Host via GET abfragen (/hosts/edit/{hostId}.json)
2. beim JSON z.B. bei der Description ein ä,ö,ü hinzufügen
3. das JSON wieder an den Server via Post senden  (/hosts/edit/{hostId}.json) - Webserver returns Error 400: Bad Request
5. beim JSON wieder a,ö,ü entfernen
6. das JSON wieder an den Server via Post senden - funktioniert

**Expected behavior**
Sollte keinen Error zurückliefern, über die Oberfläche kann ich auch z.B. einen Host ändern, die in der Description ein Umlaut beinhlaten.

**Versions**
* openITCOKPIT Server Version: 4.2.0
*  Operating system: Ubuntu 18.04 (bionic)

**Additional context**
Ich kann somit z.B. keine User die von LDAP importiert wurden, über die API anlegen oder editieren, wenn sie im Vorname oder Nachnamen ein Umlaut beinhalten.

**Comment by nook24** [comment]
I think is is a non UTF8 character problem. openITCOCKPIT expects everything to be UTF8 encoded. So if your script is sending another encoding than UTF8 this will cause issues like you descripe. 

I created a Python script which has no problems adding umlauts to the name and description fields:
https://gist.github.com/nook24/e5138f3e6be19a440443e3e525e906c2

![Bildschirmfoto 2021-04-23 um 10 54 38](https://user-images.githubusercontent.com/9019992/115847194-fe773280-a422-11eb-8e00-c0d37953e6c4.png)

You can use our public demo to test the script.

**Comment by some-random-git-user** [comment]
Hi,

thanks a lot. I'm using PowerShell, which uses ISO-8859-1 by default.
After finding an [article](https://social.technet.microsoft.com/Forums/ie/en-US/d795e7d2-dcf1-4323-8e06-8f06ce31a897/bug-invokerestmethod-and-utf8-data?forum=winserverpowershell) I encoded my JSON-Object to UTF-8 and I don't have problems now - it's working . :)

![working](https://user-images.githubusercontent.com/83059508/115854666-c2e06680-a42a-11eb-9013-986ba9535fa9.png)
