### ISSUE TITLE
Can not add additional arguments in new commands

### ISSUE THREAD

**Issue by MaLi187** [it-novum/openITCOCKPIT#1166]
**Describe the bug**
It is not possible to add more than one argument to a check.

**To Reproduce**
1. Go to 'Objects -> Commands'
2. Click on '+ New'
3. Create a new command and put in the command line a command with several args i.e. '$USER1$/check_nrpe -H $HOSTADDRESS$ -c $ARG1$ -a $ARG2$'
4. Click on '+Add argument' to add the them, also in the demo system it is not possible to add more than one arg

**Expected behavior**
Adding more than one argument

**Screenshots**
If applicable, add screenshots to help explain your problem. You can upload screenshots via drag and drop
![image](https://user-images.githubusercontent.com/74232705/116969055-eb335500-acb5-11eb-9294-59a3ca6e3341.png)

**Versions**
* openITCOKPIT Server Version: 4.2.0 (demo.openitcockpit.io)
*  Operating system: I don't know the OS of your demo system ;) I have the same problem on the nightly build I am using

**Comment by ibering** [comment]
Hi @MaLi187 

This issue has been resolved in new nightly version. Many thanks for your support. You can test current changes on the demo system

Best regards 
Irina

**Comment by MaLi187** [comment]
Thanks, it works.

Regards,
Matthias
