### ISSUE TITLE
How to establish a custom subsite on the satellite webui?

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1167]
i used as mentiond the custom.conf file like this:

location /cmdb {

        root /usr/share/nginx/html/cmdb;
        index index.html;
}

Config is ok and reloaded.  Testet with root /var/www/html/cmdb also.  Even an 404 error. 

I see not why a subdirectory will not work on a satellite webinterface?

**Comment by nook24** [comment]
Most likely your nginx config is wrong. Please try this config:
```
mkdir -p /var/www/html/cmdb/
echo "<h1>It works - CMDB</h1>" > /var/www/html/cmdb/index.html
```

Add to `/etc/nginx/openitc/custom.conf`:
```
location ^~/cmdb {
    root /var/www/html/;
    index index.html;
}
```

And reload nginx: `systemctl reload nginx`

Result:
![Bildschirmfoto 2021-05-05 um 17 01 30](https://user-images.githubusercontent.com/9019992/117163246-c3caae00-adc3-11eb-9e25-4158ee712d7e.png)
