### ISSUE TITLE
Whisper Storage Consumption - Sizing

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1178]
Hi,
how is the sizing if i have 3.300 Service Checks.
I have 97G for Whisper in Use:
![image](https://user-images.githubusercontent.com/44997840/119457705-44822780-bd3c-11eb-8cf5-1c57b6335489.png)
Is that normal?

Greetings
Frank

**Comment by nook24** [comment]
Hi Frank,

This depends on the used storage schema. By default openITCOCKPIT will store each metric for 365 days with a resolution of 60 seconds.  The used carbon storage schema is: `60s:365d`. This is about ~6MB per metric.
The Ping check for example has two metrics, RTA and PL which maks a total of ~12MB.

To reduce the required disk space you could change the storage schema to store less information like `60s:90d,5m:365d`. To change the storage schema please use the `System -> Config file editor` in the openITCOCKPIT Frontend and edit the file `docker-compose.yml` 

**Changing the storage schema will only affect new services!**

You can use this tool to calculate the estimated disk space:
https://m30m.github.io/whisper-calculator/

**Comment by infofrs** [comment]
Perfect. Thanks!
