### ISSUE TITLE
Show notification status in the main interface

### ISSUE THREAD

**Issue by hugleo** [it-novum/openITCOCKPIT#1179]
Show a icon if the notification is enabled/disabled for the host and service pagination list.

**Comment by ibering** [comment]
ITC-2605

**Comment by ibering** [comment]
Hi @hugleo,

This feature will be released in the next version. https://github.com/it-novum/openITCOCKPIT/pull/1216

Best regards
Irina

**Comment by nook24** [comment]
Fixed with https://github.com/it-novum/openITCOCKPIT/releases/tag/openITCOCKPIT-4.3.0
