### ISSUE TITLE
Add disable notification for host/service configuration

### ISSUE THREAD

**Issue by hugleo** [it-novum/openITCOCKPIT#1205]
I can temporarily disable notifications for host/service in the following screen 

![disable-notification](https://user-images.githubusercontent.com/4573505/127523573-21c5f147-efcf-4b7d-995e-1b9b7b801830.png)

But couldn't find where to permanent disable notification in the host/service configuration screen:

![not-found-here](https://user-images.githubusercontent.com/4573505/127524423-535b9164-e67a-4f74-ace9-3c03d9959eee.png)

**Comment by nook24** [comment]
To disable notifications you can select `none` as notification period

**Comment by hugleo** [comment]
but there aren't an easy way to see which hosts have disabled notifications. In the host overview screen we still see a green Yes box for "Notifications enable" label

**Comment by ibering** [comment]
ITC-2606

**Comment by ibering** [comment]
Hi @hugleo,

This feature will be released in the next version. https://github.com/it-novum/openITCOCKPIT/pull/1217

Best regards
Irina

**Comment by nook24** [comment]
Fixed with https://github.com/it-novum/openITCOCKPIT/releases/tag/openITCOCKPIT-4.3.0
