### ISSUE TITLE
Sorting of arguments is not correct

### ISSUE THREAD

**Issue by Cynexxde** [it-novum/openITCOCKPIT#1212]
I wanted to make a quick suggestion for an adjustment. The sorting of the arguments is not what I would expect. It looks comparable in the service template.
![unknown](https://user-images.githubusercontent.com/88704661/129151348-edecd5a0-51de-4571-ad35-30915c59f248.png)

**Comment by ibering** [comment]
ITC-2597

**Comment by ibering** [comment]
Hi @Cynexxde,

Thanks for your bug report. This problem will be fixed in the next version.

Best regards
Irina

**Comment by Cynexxde** [comment]
Now the labels within the respective service configuration no longer match those from the service template. Somehow they are now twisted and I no longer know which field is which.

Left: Service of a Host;  Right: Service template
![image](https://user-images.githubusercontent.com/88704661/144444141-7b4e0448-840b-4961-8c6e-a914715f118a.png)

**Comment by ibering** [comment]
Hi @Cynexxde,

which version of openITCOCKPIT do you have?  In my test (version 4.3.2), I cannot reproduce your problem.

Best regards
Irina

**Comment by Cynexxde** [comment]
Version 4.3.0, I will update.
