### ISSUE TITLE
Statuskarte lädt nur bei root Benutzer

### ISSUE THREAD

**Issue by Cynexxde** [it-novum/openITCOCKPIT#1218]
**Describe the bug**
Die Statuskarte lässt sich nur als root Benutzer öffnen. Bei Benutzern, die sich in einem Container befinden wird diese nicht angezeigt. In der Fehlermeldung wird darauf hingewiesen, dass manche Hosts doppelt vorhanden sind. Voraussichtlich liegt es daran, dass manche Hosts zusätzlich in einem geteilten Container dem Benutzer zugeordnet sind.

**Versions**
* openITCOCKPIT Server Version: 4.2.3
*  Operating system: Debian 10

**Additional context**
![Unbenannt](https://user-images.githubusercontent.com/88704661/130461517-0dac3e1e-01b8-408d-aa96-3b5e5f24870b.PNG)

**Comment by ibering** [comment]
ITC-2611

**Comment by ibering** [comment]
Hallo @Cynexxde,

vielen Dank für die Fehlermeldung. Das Problem wird ab der nächsten Version behoben sein. 

Viele Grüße
Irina
