### ISSUE TITLE
Popup Systemzustand Tippfehler Deutsche Übersetzung

### ISSUE THREAD

**Issue by Neephilius** [it-novum/openITCOCKPIT#1219]
**Describe the bug**
Tippfehler in der Deutschen Übersetzung im Popup Systemzustand

**Expected behavior**
In Ordung! -> In Ordnung!

**Screenshots**
![grafik](https://user-images.githubusercontent.com/89450258/130588187-580700fd-f6de-4837-8004-e0e003ed5cfc.png)

**Versions**
* openITCOCKPIT Server Version: 4.2.3
*  Operating system Ubuntu 18.04

**Comment by ibering** [comment]
Hallo @Neephilius,

der Tippfehler wurde behoben (https://github.com/it-novum/openITCOCKPIT/commit/41dcf6e0929dd3828e2e2fa03b9f98dbafeca9bf). Vielen Dank für den Hinweis

Viele Grüße
Irina

**Comment by nook24** [comment]
Resolved by https://github.com/it-novum/openITCOCKPIT/commit/41dcf6e0929dd3828e2e2fa03b9f98dbafeca9bf and will pe part of the next version
