### ISSUE TITLE
Grafana Probleme

### ISSUE THREAD

**Issue by viruz82** [it-novum/openITCOCKPIT#1232]
Moin,

in der [Doku](https://docs.it-novum.com/display/ODD/Graphing+Backend#GraphingBackend-Grafana) steht, dass sich der Grafana API Key hier befindet: `/etc/openitcockpit/grafana/api_key`. Allerdings gibt es die Datei bei mir nicht. Außerdem kann ich mich im Grafana nicht als admin anmelden. Ich habe in der master.conf den Teil `proxy_set_header X-WEBAUTH-USER viewer;` geändert in `proxy_set_header X-WEBAUTH-USER admin;` und auch nach einem Neustart werde ich immer automatisch mit viewer angemeldet.

Gruß
Kai

**Comment by ibering** [comment]
Hallo Kai,

normalerweise muss nur die Nginx Config `/etc/nginx/openitc/master.conf`: angepasst werden. Wie in #1114 beschrieben ist. Der API Key findest Du unter `/opt/openitc/etc/grafana/api_key` oder über das Frontend _**API->Grafana**_

https://github.com/it-novum/openITCOCKPIT/blob/598e342f0e2ef8cf8856a331f635d30624f2dac8/system/etc/nginx/openitc/master.conf#L85-L97

Viele Grüße
Irina

**Comment by viruz82** [comment]
Hallo Irina,

danke für deine Antwort.

Der admin Login funktioniert jetzt.

Allerdings existiert, wie ich schon geschrieben habe, die Datei `/opt/openitc/etc/grafana/api_key` tatsächlich nicht.
Ich sehe einen Grafana API Key unter APIs > Grafana in hellgrau, den habe ich dort mal eingetragen. Sobald ich ein Dashboard erstelle und anschließend mit Grafana synchronisieren will, schlägt das mit folgendem Fehler fehl: `Beim Synchronisieren ist ein Fehler aufgetreten`

**Comment by ibering** [comment]
Hallo Kai,

kann es sein, dass es nur der Platzhalter ist?

Alternativ kannst Du schauen, ob ein Eintrag für Grafana Konfiguration in der Datenbank existiert.

`SELECT * FROM grafana_configurations; `

Gibt es eine Fehlermeldung, wenn Du auf klickst?

![Bildschirmfoto 2021-09-09 um 10 27 54](https://user-images.githubusercontent.com/9592910/132651127-5c837e7a-3b3d-40e9-8381-54d06bf77332.png)

Wenn die Verbindung erfolgreich ist, wird eine success Meldung, wie diese angezeigt

![Bildschirmfoto 2021-09-09 um 10 27 06](https://user-images.githubusercontent.com/9592910/132651010-e79baaeb-8e02-4af5-b576-fb0bd48eb7a2.png)

Falls der API Key nicht mehr passt, kannst Du direkt im Grafana Dir einen neuen erstellen lassen. [Hier](https://docs.it-novum.com/display/ODE/Graphing+Backend#GraphingBackend-ConfigureexternalGrafanatouseexternalGraphite) ist es beschrieben und nachdem Du auch **admin** bist, müsste es klappen

Viele Grüße
Irina

**Comment by viruz82** [comment]
Hallo Irina,

ich habe jetzt einen neuen API Key im Grafana mit Editor Berechtigungen angelegt und diesen in openITCOCKPIT entsprechend hinterlegt. In der Datenbank steht das auch alles korrekt drin. Der Fehler bleibt aber derselbe, sobald ich auf "Synchronisiere mit Grafana" klicke.
![image](https://user-images.githubusercontent.com/19948134/132653659-48d521d2-7c67-4ea3-9acf-52e6afba52ca.png)

Gruß
Kai

**Comment by ibering** [comment]
Hallo Kai,

kannst Du bitte ein Screenshot Deiner Grafana Konfiguration posten. Den API Key kannst Du natürlich vorher entfernen. Benutzt Du eventuell ein externes Grafana?

>>P.S.: Es ist übrigens vollkommen egal, ob der API Key korrekt eingetragen ist. Es reicht, nur ein einziges Zeichen einzutragen und die Verbindung ist erfolgreich und wird gespeichert.

Das hatten wir leider noch nicht. Bei mir wird immer eine Fehlermeldung angezeigt, wenn mein API Key falsch ist.

Es ist etwas schwierig den Fehler zu finden, weil das Standard Grafana immer mit **viewer** Rolle angesprochen wird

Viele Grüße
Irina

**Comment by viruz82** [comment]
Hallo Irina,

hier der Screenshot meiner Grafana Config - ich nutze das interne.
![image](https://user-images.githubusercontent.com/19948134/132671287-203bb080-ac0a-4511-9147-b0f42d7d3773.png)

Als URL habe ich die URL zu meinem openITCOCKPIT mit /grafana eingetragen. Ist das korrekt so?

Gruß
Kai

**Comment by ibering** [comment]
Hallo Kai,

wahrscheinlich habe ich mich falsch ausgedrückt. Mit _**intern**_ meinte ich, ob Grafana vom openITCOCKPIT mitkommt , oder ein externes Grafana System verwendet wird. Bei der Standardinstallation läuft Grafana im `docker`. Bei der Grafana URL muss dann einfach `grafana.docker` eingetragen werden. 

Viele Grüße
Irina

**Comment by viruz82** [comment]
Hallo Irina,

mit `grafana.docker` als URL funktioniert es jetzt. Hab ich in der Doku überlesen, sorry. Vielen Dank für den Tipp! Ich habe im Grafana jetzt zwar mein Dashboard, allerdings keine data source. Wenn ich das richtig gelesen habe, muss dort Graphite rein. Ich sehe in der Doku allerdings nicht, wie ich Graphite dort einbinden kann. Automatisch passiert das vermutlich nicht. Wo kann ich das nachlesen?

Gruß
Kai

**Comment by ibering** [comment]
Hallo Kai,

das passiert eigentlich automatisch. [Hier](https://docs.it-novum.com/display/ODD/Graphing+Backend) ist die Doku zum Graphing Backend. Am besten schaust Du nach, was bei Dir unter  _**System->Config file editor**_ eingetragen ist. Du kannst auf der Demo Seite nachschauen, was sie Standardwerte sind. Du findest die Konfiguration unter  _**System->Config file editor**_

https://demo.openitcockpit.io/#!/ConfigurationFiles/edit/GraphingDocker 

Viele Grüße
Irina

**Comment by viruz82** [comment]
Hallo Irina,

ich habe nichts an diesen Einstellungen verändert und die Datenquelle im Grafana wurde nicht erzeugt. Ich habe die Einstellungen in `/opt/openitc/docker/container/graphing/docker-compose.yml` auch nicht verändert und gerade extra noch mal auf "Standard wiederherstellen" geklickt. Anschließens habe ich meine openITCOCKPIT VM sogar neu gestartet, aber das ändert nichts. Wie bekomme ich die Datenquelle ins Grafana?

Gruß
Kai

**Comment by ibering** [comment]
Hallo Kai,

das klingt schon mal soweit alles richtig.  Dann fällt mir nur noch ein den Befehl `openitcockpit-update`auf der Konsole einmal auszuführen und zu schauen ob dort A) Fehler kommen und es B) das Probleme behebt

Viele Grüße
Irina

**Comment by ibering** [comment]
Hallo Kai,

eigentlich macht das alle die SETUP.sh Leider darf man die nicht mehrfach ausführen :/ 

https://github.com/it-novum/openITCOCKPIT/blob/development/SETUP.sh#L203-L249

Man müsste jetzt versuchen mit einzelnen Befehlen das Ganze zu korrigieren. Ist schwierig zu sagen, was da alles schief gelaufen ist.

Viele Grüße
Irina

**Comment by viruz82** [comment]
Guten Morgen Irina,

Danke für den Link, daraus habe ich jetzt die Datenquellen manuell angelegt und es funktioniert! 👍 
Ich habe gesehen, dass mit Graphite auch noch Prometheus angelegt wird. Wofür ich die benötige, weiß ich zwar nicht, aber ich habe sie auch mal mit angelegt.
Dennoch ist es seltsam, warum das alles beim Setup nicht funktioniert hat. Meine Installation ist ganz neu, nicht mal eine Woche alt und bei der Installation gab es auch keinen einzigen Fehler. Vielen Dank für deine klasse Unterstützung! 🥇 

Gruß
Kai

**Comment by ibering** [comment]
Guten Morgen Kai,

Gern geschehen :) Leider kann man so aus der Ferne nicht sagen, was bei der Installation schief gelaufen ist. So ein Systemverhalten wurde bis jetzt auch noch nicht gemeldet. Aber schön, dass alles wieder funktioniert.

Es gibt ein Prometheus Modul für openITCOCKPIT, das kann zusätzlich zum Core installiert werden. [Hier](https://openitcockpit.io/2020/2020/10/20/openitcockpit-4-1-with-prometheus-integration/) ist eine kleine Übersicht aus unserem Blogeintrag   

Viele Grüße
Irina
