### ISSUE TITLE
Translate openITCOCKPIT in as many languages as possible

### ISSUE THREAD

**Issue by ibering** [it-novum/openITCOCKPIT#1248]
Hacktoberfest 2021
========================

Celebrate [Hacktoberfest](https://hacktoberfest.digitalocean.com/) by getting involved in the open source community.
We would like to ask you to help us translate openITCOCKPIT in as many languages as possible.

*As many as you want* - *as long as you want*

## About the project
openITCOCKPIT is a modern web interface to manage Nagios, Naemon or Prometheus based monitoring environment.

For more information please see the projects home page: https://openitcockpit.io/

## How to contribute

1. Fork this repository

2. Add a comment to this issue, which language you want to translate.

3. Clone your forked repository (replace YOUR_ACCOUNT_NAME)
```
git clone https://github.com/YOUR_ACCOUNT_NAME/openITCOCKPIT.git
cd openITCOCKPIT/
```
4.  Go to the `Locale` folder

```
cd resources/locales/

```
5. Choose a language you want to translate to

- 5.1. The language folder does not exist yet: 
Copy the template folder `en_US` and rename it like your chosen language.
   ```
   cp -r en_US it_IT
   ```
If it is done continue with step 5.2

- 5.2. The language folder already exists:
e.g.
    ```
    cd de_DE/
    ```
6. Translate the content of `default.po` file
The translation must be done line by line.
The `msgid` contains the original english content and should **not be touched**
The translated message goes to `msgstr`.
#### But before you start, please read our [Important notes](#important-notes) section!
Example:
```
msgid "Week"
msgstr "Settimana"
```

7. If done, please send a pull request

Replace **YOUR\_ACCOUNT\_NAME** with your GitHub account name.

```
git checkout -b development_translation_YOUR_ACCOUNT_NAME
git add .
git commit -m "Added translation for it_IT"
git push origin development_translation_YOUR_ACCOUNT_NAME
```

To contribute your changes, you need to send a pull request:

Please notice: You need to select **development** as `base` while you create your pull request.

---

#### Don´t translate en_US, that´s our source language :)

- Special words are not to translate
    - openITCOCKPIT, Statusengine, CakePHP, Gearman, GearmanWorker
    - LDAP, OpenLDAP, PHP, SSO, NRPE, NDO, UUID, ARO, ACO, ACL,
    - Nagios, Naemon, NPCE, NDOUtils
    - .....
- Don´t touch placeholders, escape characters, classes, values or html (style) code
    - % prefixed characters are used for replacements. (e.g. `%s` replaces a string or `%1$s`)
    - `\` escapes `"`
    - `CrudAuthorize::authorize()` is an example for an internal class. (Needed for error messages)
    - `$` prefixed words are variables (e.g. `$PATH`, `$USER1$`, `$ARG1$`)
    - use `<b>This is bold</b>` to generate bold characters
    - use `<success>Green text</success>` to generate green characters
- Keep length of strings that are using blank characters to get an uniform length

```
msgid  "User:         %s"
msgstr "Benutzer:     %s"
```

## Need help or have any question?
 - Please join our community discord server: https://discord.gg/G8KhxKuQ9G

**Comment by andrecoco** [comment]
I can translate it to pt_BR

**Comment by mantasio** [comment]
@ibering I would like to contribute with Lithuanian translation. Expect a PR within a few days

**Comment by mRuggi** [comment]
Hello, I'd like to contribute to this project i found on the Hacktoberfest 2021 reddit, i'm currently working on the Italian translation made a first PR in #1261
