### ISSUE TITLE
Manuelle Anpassung System Health Check

### ISSUE THREAD

**Issue by ppabst** [it-novum/openITCOCKPIT#1250]
Der System heakth check ist z.B. für die Disk auf Warning 80% und Critical 90% fest im Code eingestellt.
Wenn das System aber eine sehr große Festplatte hat, ist dieser Wert deutlich zu früh gewählt.

Es wäre schön wenn die Schwellwerte manuell angepasst werden könnten
https://github.com/it-novum/openITCOCKPIT/blob/development/src/itnovum/openITCOCKPIT/Core/System/Health/Disks.php#L47-L50

**Comment by ppabst** [comment]
Gibt es vielleicht etwas neues dazu

**Comment by nook24** [comment]
Wurde mit https://github.com/it-novum/openITCOCKPIT/pull/1479 implementiert.
