### ISSUE TITLE
check_mk / snmp crashing

### ISSUE THREAD

**Issue by exa-mk** [it-novum/openITCOCKPIT#1266]
**Describe the bug**
Since the update to openITC 4.3.0 all check_mk snmp check are crashing

**To Reproduce**
- Make check_mk snmp discovery
- Add one or more found checks
- Reload config
- Wait for checks to run

**Expected behavior**
check_mk snmp check working as before

**Screenshots**
![grafik](https://user-images.githubusercontent.com/69202794/138116141-c5533cf1-a64a-4e6c-93ca-4983e7e9a90d.png)

**Versions**
* openITCOKPIT Server Version: 4.3.0
*  Operating system: Ubuntu 20.04 LTS

**Additional context**
n/a

**Comment by nook24** [comment]
Have you updated your service templates as described in our latest blog post: https://openitcockpit.io/2021/2021/10/18/openitcockpit-4-3-0-released/ ?

In addition, to monitor a server only via SNMP you have to disable `Enable Checkmk agent` for the particular hosts.

Just select `Checkmk discovery` from the context menu of the host, untick the checkbox and click Execute discovery to apply your changes.


![checkmk_agent_and_snmp](https://user-images.githubusercontent.com/9019992/138247535-a5784055-fca6-4a16-b9f4-ebaec256a170.png)

**Comment by exa-mk** [comment]
ah... changing the parameters and disabling the agent helped.

why doesn't the update script do this automatically? I had to change ~70 devices and over 900 interface service checks with manual set (speed) settings. this is now very intuitive... :-/

anyway... thanks for the help. imho the ticket can be closed.
