### ISSUE TITLE
Acknowledge service status, text not getting cleared on next service to acknowledge

### ISSUE THREAD

**Issue by MaLi187** [it-novum/openITCOCKPIT#1267]
If you acknowledge i.e. a critical service status and you go to the next service to acknowledge, it has still the text of the previous acknowledged status in and you are not able to hit save. In order to acknowledge the next one you have to click cancel an click "Acknowledge service status" again, then it works.

Also tested on the demo - system, same behavior as described.

Regards
Matthias

**Comment by nook24** [comment]
This got fixed with [openITCOCKPIT 4.3.1](https://github.com/it-novum/openITCOCKPIT/releases/tag/openITCOCKPIT-4.3.1)
