### ISSUE TITLE
Enable Listview of Hosts about 50,100, ALL Hosts

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1292]
If you have more than 25 Hosts and wants to make a MASS EDIT.....it is boring to do that site by site. To display more lines or ALL would be much more confitable.

**Comment by nook24** [comment]
You can define how many records openITCOCKPIT will show per page in the user settings:
![Bildschirmfoto 2022-01-10 um 09 38 10](https://user-images.githubusercontent.com/9019992/148737849-450badb9-4b53-4c1d-8d95-55cdebf74154.png)
