### ISSUE TITLE
Display attachted Hosts in Contact_Group View

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1296]
It is very helpfull to see all configured hosts of a Contact Group in the Groups / Contact Groups section.

**Comment by ibering** [comment]
Hi @infofrs,

The "Used by" context menu of contact groups shows a list of all hosts or host templates that are using the selected contact group. In the second step, navigate to host templates and pick the corresponding host template. Again, the context menu provides the "Used by" option, which display a list of all hosts.

The same applies to services

 Best regards
Irina
