### ISSUE TITLE
Agent in PULL Modus shows green in Web UI but shows an error on Client Console

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1297]
Destination: Debian Client on ARM Device
Agent is configured in PULL Mode and working fine!
Status in WEB UI:
![image](https://user-images.githubusercontent.com/44997840/148349832-ddf22af3-ecb0-4f76-a174-66d7096d00ee.png)

BUT. The Service of the Agent shows an TLS Error!
![image](https://user-images.githubusercontent.com/44997840/148349985-9f2b7ec6-c0fa-43ea-a3e7-3a50a85a7c4d.png)

**Comment by nook24** [comment]
This is a normal phenomenon due to the port checking method which makes sure that the webserver of the agent is running.

![Completly Normal Phenomenon](https://media.tenor.com/g1zfOVi_s5AAAAAC/completly-normal-phenomenon-chernobyl.gif)
