### ISSUE TITLE
Language for Agent Checks switches

### ISSUE THREAD

**Issue by infofrs** [it-novum/openITCOCKPIT#1298]
Some Users are using the UI in GERMAN language, others in English.
If an Admin configures an Host with the Agent in English 
- the Services are displayed in english. Example: Disk usage
- The German Admin sees the same. But if he deployes a new host with agent
- the Services are displayes like: "Festplattennutzung.."

Result:
It it not possible to filter all Services for Example  Festplattennutzung vs. Disk Usage.   These are 2 Filter actions!
Please provide all services from the agent in one language (english for default).

**Comment by Cynexxde** [comment]
We have the same problem. I would definitely support the uniform naming in English. That the services are named in different languages makes it confusing for us.

**Comment by Cynexxde** [comment]
This would additionally fix a serious problem with the import module. There the services are imported twice if the applying users have set different languages. 

![image](https://user-images.githubusercontent.com/88704661/190339495-604c8ff4-aa12-41e9-8d0b-021278f996fa.png)

**Comment by nook24** [comment]
Tracked by ITC-2877
