### ISSUE TITLE
Check_icmp: Failed to obtain ICMP socket while Version update

### ISSUE THREAD

**Issue by Electricz1337** [it-novum/openITCOCKPIT#1341]
While updating openITCockit check_icmp keeps running into the issue:

check_icmp: Failed to obtain ICMP socket: Operation not permitted 

which results into spam mailing that every host is down.

OpenITCockpit is most likely installed since Version 3.x (unsure if i made a clean install with Version 4)

Updating every few Months and getting this issue over and over again.

**Comment by nook24** [comment]
I'm not entirely sure why this is happening on your installation. My guess would be that is has something todo with the very special file permissions check_icmp requires. The update of openITCOCKPIT will set the file permissions, but maybe this takes for some reason very long on system? I'm not sure. I never came across an issue like this. 

Therefore I would suggest you try a little workaround. 

Install the default monitoring plugins on your system provided by Ubuntu.
```
apt-get install monitoring-plugins
```
Change the command `check-host-alive` to use the basic plugin from Ubuntu:
```
/usr/lib/nagios/plugins/check_icmp
```
Same for `check_ping`
```
/usr/lib/nagios/plugins/check_ping
```

Hope this helps.

**Comment by Electricz1337** [comment]
Thank you for the response.

I made a new install a few weeks ago on a new ubuntu 22.04 machine and it worked fine since then.

Might be an very old issue since the first installation was in 2019 / early 2020
