### ISSUE TITLE
Instant Report shows unix timestamp

### ISSUE THREAD

**Issue by nook24** [it-novum/openITCOCKPIT#1342]
When the system sends an instem report as PDF via the cron job, the PDF shows the unix timestamp instead of an human readable date format.

![unknown (1)](https://user-images.githubusercontent.com/9019992/161977775-48b6beab-adf5-4c54-9a9a-2d4b86fa68c1.png)

This is because the cron job passes the data as unix timestamp to the view.
https://github.com/it-novum/openITCOCKPIT/blob/c9816f9ef74112f70cb8a9cefbe216880fefc1bd/src/Command/InstantReportCommand.php#L158-L159

If the instant reports get generated via the web frontend, the user defined date format gets used (as expected)

This issue got reported by @Electricz1337 via Discord.

**Comment by ibering** [comment]
ITC-2752

**Comment by nook24** [comment]
Resolved by https://github.com/it-novum/openITCOCKPIT/pull/1344
This will be part of the next release openITCOCKPIT 4.4.1
