### ISSUE TITLE
openitcockpit Agent http Error 500

### ISSUE THREAD

**Issue by cyni0s** [it-novum/openITCOCKPIT#1374]
When agent submits its stats via push. It returns a internal server error 500. As a result nothing is pushed to the montoring Server. The agent config was generated by the Agent-Wizard via OITC-Webinterface. 

OS: Ubuntu 20.04 LTS up-to-date (Proxmox LXC)

**Client:** 

> level=error msg="Push Client: unknown error during submit checkdata, http status:  500"

**Server Error log** (/opt/openitc/logs/frontend/error.log):

> 2022-06-18 16:12:08 error: [RuntimeException] Config file "/opt/openitc/receiver/etc/production.json" not found in /opt/openitc/receiver/src/itnovum/openITCOCKPIT/Checks/Receiver/CheckConfig.php on line 46
> Request URL: /agentconnector/submit_checkdata.json
> Client IP: 192.168.xx.3

192.168.xx.3 is the IP of my reverse proxy. This error occurs twice a minute every time the agent tries to submit a check.

**Comment by nook24** [comment]
Unfortunately that is a bug as descripted in https://github.com/it-novum/openITCOCKPIT/issues/1238.
At the moment it is required, to monitor at least one host in Pull Mode. My preferred workaround for this is, to monitor the openITCOCKPIT Server itself using the openITCOCKPIT Monitoring Agent in Pull Mode.

**Comment by cyni0s** [comment]
yes, this fixed the problem. Thank you so much for helping out. I did not find the duplicate.
