### ISSUE TITLE
Refresh monitoring configuration loading not stop

### ISSUE THREAD

**Issue by juniorkalvin7** [it-novum/openITCOCKPIT#1388]
Refresh monitoring configuration - loading not stop 

Refresh in progress
![Captura de Tela 2022-07-14 às 11 25 35](https://user-images.githubusercontent.com/16207790/179005940-f223fa46-81f2-419f-bf6f-d9caf296949f.png)

**Comment by nook24** [comment]
I have added a new part to our Troubleshooting documentation, which describes how to resolve the issue:

https://docs.openitcockpit.io/en/additional/troubleshooting/#refresh-monitoring-configuration-is-stucking

Hope this helps :)

**Comment by nook24** [comment]
Can we close this issue?

**Comment by juniorkalvin7** [comment]
yes

**Comment by juniorkalvin7** [comment]
Obrigado………Brazilllllllll
