### ISSUE TITLE
Support Telegram notify ?

### ISSUE THREAD

**Issue by juniorkalvin7** [it-novum/openITCOCKPIT#1391]
Support Telegram notify ?

**Comment by nook24** [comment]
There is no official support for sending notifications via Telegram.

**Comment by juniorkalvin7** [comment]
I did. code for sending via telegram but the logs do not match

Log openitcockpit 

[1658746621] SERVICE ALERT: 80a8ddf4-7d85-4b67-b853-ab3bf1aa7f40;f21a7540-9c04-441d-856c-263b27acabc9;OK;SOFT;2;OK: Disk load: 0.19%. Read IOPS: 0, Write IOPS: 1. Write request size: 0B, Total Wait: 1.3442ms


Log centreon or nagios 

[1528981346] [14078] SERVICE ALERT: scan-ports-clientes;FTi_Scan_rebocadores;UNKNOWN;SOFT;1;OK - 200.216.199.34 Portas abertas ()




Telegram Centreon or Nagios Output: 

2022-07-25 13:07:08,314 - Telegram Logger - DEBUG - Namespace(contact='-667386131', datetime=None, hostaddress=None, hostname='FCOLIVEIRA-SRVBACKUP', hoststate=None, notificationtype='PROBLEM', object_type='service', output='CRITICAL: 4 CPU(s) average usage is: 98.75%', servicedesc='Cpu', servicename=None, servicestate='CRITICAL', token='2032247812:AAEnfRZYSwTXkXR0a8pHUqrm0yGgxVH8PiE')

Telegram OpenITCockPit

[1658746775] Warning: Notification command for contact 'dcf54a75-a099-463c-94fe-24e7d4801b62' about service 'c56f329d-cf65-4ce0-a755-538509368f99;3c197411-5943-41c2-a7ab-44989d23b035' exited with exit code 2. stdout: '(empty)', stderr: 'usage: notify-telegram.py [-h] [--config CONFIG] [-t TOKEN] [--contact CONTACT] [--notificationtype NOTIFICATIONTYPE] -o
                          {host,service} [--hostname HOSTNAME] [--hostaddress HOSTADDRESS]
                          [--hoststate {UP,DOWN,UNREACHABLE}] [--servicestate {OK,WARNING,CRITICAL,UNKNOWN}]
                          [--servicedesc SERVICEDESC] [--output [OUTPUT]]

**Comment by nook24** [comment]
First of all you have leaked your API Token, so you should get a new Token ASAP
```
2032247812:AAEnfRZYSwTXkXR0a8pHUqrm0yGgxVH8PiE
```

> The token is a string along the lines of 110201543:AAHdqTcvCH1vGWJxfSeofSAs0K5PALDsaw that is required to authorize the bot and send requests to the [Bot API](https://core.telegram.org/bots/api). Keep your token secure and store it safely, it can be used by anyone to control your bot.

https://core.telegram.org/bots#creating-a-new-bot

The plugin is printing out it's usage. This means you are passing none or the wrong parameters. From the usage you need to create the folowing notification command in openITCOCKPIT:
```
/path/to/notify-telegram.py --config /path/to/config.cnf -t TOKEN --contact "$CONTACTALIAS$" --notificationtype "$NOTIFICATIONTYPE$" -o service --hostname "$HOSTDISPLAYNAME$" --hostaddress "$HOSTADDRESS$" --servicestate "$SERVICESTATE$" --servicedesc "$SERVICEDISPLAYNAME$" --output "$SERVICEOUTPUT$"
```

A list of all available macros with example values is available via the openITCOCKPIT interface
![command_macros](https://user-images.githubusercontent.com/9019992/180931508-e6340ee1-3af9-4eb7-bd9c-a0bd4cc1a078.png)

**Comment by juniorkalvin7** [comment]
The free version does not have this option HOST MACRO

**Comment by nook24** [comment]
Of course it has: https://demo.openitcockpit.io/#!/commands/add 🙂
Also all type of macros are descripted in the documentation: https://docs.openitcockpit.io/en/configuration/macros/

**Comment by juniorkalvin7** [comment]
> Of course it has: https://demo.openitcockpit.io/#!/commands/add 🙂
> Also all type of macros are descripted in the documentation: https://docs.openitcockpit.io/en/configuration/macros/


not show hostname 

X_bot, [26/07/2022 13:53]
⚠️ 624458cc-3076-43a8-9e99-ffc2b7d2dcc8/5684633c-0bcc-42d5-9a55-8548143b2b9b: WARNING: Memory usage: 4.72GB/5.88GB (80.16%). Total: 5.88GB, Available: 1.17GB, Used: 4.72GB, Free: 1.17GB,

X_bot, [26/07/2022 13:53]
✅ c6fabcd3-9a90-4e9a-ba4b-e095359d0dc5/5aecaf41-b31f-4bdf-9994-dabc3afa8e3b: OK: Memory usage: 872.55MB/1.98GB (43.12%). Total: 1.98GB, Available: 1.12GB, Used: 872.55MB, Free: 1.12GB,

X_bot, [26/07/2022 13:54]
🔥 2289d76a-7513-4f7e-95be-394ec7f82814/fb535cb0-9f98-4b3e-925b-eb8b76cd399b: CRITICAL: Memory usage: 5.3GB/5.88GB (90.17%). Total: 5.88GB, Available: 591.86MB, Used: 5.3GB, Free: 591.86MB,

X_bot, [26/07/2022 13:54]
⚠️ 2289d76a-7513-4f7e-95be-394ec7f82814/fb535cb0-9f98-4b3e-925b-eb8b76cd399b: WARNING: Memory usage: 5.27GB/5.88GB (89.63%). Total: 5.88GB, Available: 624.82MB, Used: 5.27GB, Free: 624.82MB,


![Captura de Tela 2022-07-26 às 13 53 37](https://user-images.githubusercontent.com/16207790/181065494-c4e9e6c9-b6d9-424a-ac28-520d7db77843.png)

**Comment by juniorkalvin7** [comment]
true4sec_bot, [26/07/2022 14:18]
⚠️  PROBLEM - 6ffdb286-8890-4843-a0dd-847fa941c935 - None is WARNING
Tipo de Notificaçao: PROBLEM
Service: 3a3c9152-968e-435e-b362-f2ed23aab010
Host: 6ffdb286-8890-4843-a0dd-847fa941c935
Address: None
Status: WARNING

Data/Hora: None
Informações adicionais:
WARNING: Memory usage: 8.38GB/8.81GB (95.06%). Total: 8.81GB, Available: 445.85MB, Used: 8.38GB, Free: 445.85MB,

**Comment by nook24** [comment]
As described in the documentation (and in my comment https://github.com/it-novum/openITCOCKPIT/issues/1391#issuecomment-1195027542)  you have to use the macros `$HOSTDISPLAYNAME$` and `$SERVICEDISPLAYNAME$` to get the human readable name.

The macros `$HOSTNAME$` and `$SERVICEDESC$` are containing the UUID of the corresponding object.

**Comment by juniorkalvin7** [comment]
Solved.
![Captura de Tela 2022-07-27 às 10 16 03](https://user-images.githubusercontent.com/16207790/181256243-a3144e58-d22d-4b43-9438-56adf5284548.png)

**Comment by nook24** [comment]
Always happy to help!

**Comment by juniorkalvin7** [comment]
Thank you very much.
