### ISSUE TITLE
Could not finish executing integrated checks:  context deadline exceeded

### ISSUE THREAD

**Issue by juniorkalvin7** [it-novum/openITCOCKPIT#1403]
Could not finish executing integrated checks:  context deadline exceeded

**Comment by nook24** [comment]
By the love of god. Could you please take 5 minutes of your time to create a ticket which contains more information than an error message? Thanks.

This error message belongs to the openITCOCKPIT Monitoring Agent so it belongs to this GitHub Repository https://github.com/it-novum/openitcockpit-agent-go as descripted in https://github.com/it-novum/openITCOCKPIT/issues/1094

To resolve the issue, you need to increase your intervall in the `config.ini`

https://github.com/it-novum/openitcockpit-agent-go/blob/50ef9028675b8e70a989dc07771ed8048347e960/example/config_example.ini#L64-L65
