### ISSUE TITLE
CheckMK installation error

### ISSUE THREAD

**Issue by realtarget** [it-novum/openITCOCKPIT#1406]
**Describe the bug**
Refresh monitoring configuration fails after CheckMK package installation

**To Reproduce**
* Clean openITCockpit installation
* Install CheckMK package as described:

```
sudo apt-get update && apt-get dist-upgrade && apt-get install openitcockpit-module-checkmk && echo "#########################################" && echo "Installation done. Please reload your openITCOCKPIT web interface."
```

* Click "Launch refresh"
* Enjoy the load indicator (and wait... wait... wait...)
* Take a look at the syslog

**Expected behavior**
Fast and clean reload of the monitoring configuration (with a working CheckMK package)

**Screenshot & Syslog**

![image](https://user-images.githubusercontent.com/4380964/187707485-53e36db4-517b-4f71-b467-7d9d03008a83.png)

```
Aug 31 14:29:45 monitoring dockerd[876]: time="2022-08-31T14:29:45.311765360Z" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
Aug 31 14:29:45 monitoring dockerd[876]: time="2022-08-31T14:29:45.311824583Z" level=info msg="Ignoring extra error returned from registry: unauthorized: authentication required"
```

**Versions**
* openITCOCKPIT Server Version: 4.5.1
*  Ubuntu 22.04.1 LTS

**Comment by nook24** [comment]
This error was caused by the fact that the `info` contact got renamed. The installation process of the Checkmk module checks for the presence of an `info` contact and fails otherwise.
Fun fact, the `info` contact is not used at all by the Checkmk Module - so this check needs to be removed.

**Comment by nook24** [comment]
Tracked by ITC-2843
