### ISSUE TITLE
Zeitpunkt der letzten Agent-Updates wird nicht richtig angezeigt

### ISSUE THREAD

**Issue by Cynexxde** [it-novum/openITCOCKPIT#1410]
Als Zeitpunkt der letzten Zustandsänderung wird immer der "01:00:00 - 01.01.1970" angegeben.

![3](https://user-images.githubusercontent.com/88704661/189288122-45f1ec59-b6a0-4594-91be-10ed93631bc1.PNG)

![4](https://user-images.githubusercontent.com/88704661/189288173-fd7a6aa7-45fe-4d38-a289-003b86eed84e.PNG)

Die Datenbanktabelle push_agents hat alle benötigten Spalten und die Werte sind auch aktuell:
```
id: 2
uuid: 3bb1978b-1728-4545-b29e-807fd3d5b093
agentconfig_id: 13
password: ##
hostname: #
ipaddress: 10.0.#
remote_address: 10.0.#
http_x_forwarded_for: NULL
        checkresults: {"agent":###

last_update: 2022-09-08 14:03:28
created: 2021-11-26 10:33:30
modified: 2022-09-08 14:03:28
```

**Versions**
* openITCOKPIT Server Version: 4.4.1 und 4.5.1
* openITCOKPIT Agent Version: 3.0.7 und 3.0.9

*  Operating system: Debian 10

**Comment by Cynexxde** [comment]
So wie es aussieht wird das Datum nur falsch angezeigt, wenn die Sprache auf deutsch, französisch und ukrainisch eingestellt ist.

![image](https://user-images.githubusercontent.com/88704661/190422182-b8299c90-80ce-4cb0-b6c2-bdf5a0351fbd.png)  ![image](https://user-images.githubusercontent.com/88704661/190422239-443574cb-863b-4bb1-80fc-e94e991fcae4.png)

**Comment by nook24** [comment]
Dies passiert, wenn die Oberfläche in einer anderen Sprache als Englisch genutzt wird und scheint durch das CakePHP Framework ausgelöst zu werden.
Wir schauen uns das genauer an 🕵️‍♀️
