### ISSUE TITLE
Some wizards are only available for "Administrator" user role

### ISSUE THREAD

**Issue by nook24** [it-novum/openITCOCKPIT#1427]
**Describe the bug**
Due to a limitation within the ACL-Dependency system, some of the wizards are only availalbe for users that are part of the "Administrator" user role. The issue is caused by the fact, that multiple `WizardsController` classes exists, which are getting merged into one from the ACL-Dependency system.

The "Administrator" user role has permission to any action on the system. While any other manually create user group, can only select from visible user permissions.

**To Reproduce**
1. Create a new user role at `Manage User Roles`
2. Tick all options / permissions
3. Create a new user and assigned it to the new user role
4. Login as the new user
5. Navigate to `Wizards` and try to use a wizard provided by an Module such as `Network` or `Oracle`

The Server should now respond with an 403 Forbidden error.

**Expected behavior**
Only respond with 403 Forbidden if the user really has no permission to this action :)

**Screenshots**

![Screenshot 2022-10-06 085943](https://user-images.githubusercontent.com/9019992/194235765-494395cd-c6d6-4013-b6e2-e21738261452.png)

**Versions**
* openITCOKPIT Server Version: 4.5.2
*  Operating system: Ubuntu 22.04

**Comment by ibering** [comment]
ITC-2856
