### ISSUE TITLE
[Agent] Add option to determine which field will be used for process monitoring

### ISSUE THREAD

**Issue by nook24** [it-novum/openITCOCKPIT#1429]
**Is your feature request related to a problem? Please describe.**

A community member was trying to monitor if OneDrive is running on it's Windows Server 2022 or not.
The openITCOCKPIT Monitoring Agent reported the folowing data:
```JS
{
            "pid": 9092,
            "ppid": 4140,
            "username": "",
            "name": "OneDrive.exe",
            "cpu_percent": 0,
            "memory_percent": 0.6295056982462701,
            "cmdline": " /updateInstalled /background",
            "status": null,
            "exec": "C:\Users\tasks\AppData\Local\Microsoft\OneDrive\OneDrive.exe",
            "nice_level": 0,
            "num_fds": 830,
            "Memory": {
                "working_set": 145539072,
                "working_set_private": 81072128,
                "private_bytes": 87416832
            },
            "CreateTime": 1664881663
        },
```

The issue is caused by the strange `cmdline`. It should contain the path to OneDrive.exe as well like on a different Windows 10 Test client.
```JS
        {
            "pid": 13520,
            "ppid": 9788,
            "username": "",
            "name": "OneDrive.exe",
            "cpu_percent": 0,
            "memory_percent": 0.04488421057667181,
            "cmdline": "\"C:\\Users\\foobar\\AppData\\Local\\Microsoft\\OneDrive\\OneDrive.exe\" \/background",
            "status": null,
            "exec": "C:\\Users\\foobar\\AppData\\Local\\Microsoft\\OneDrive\\OneDrive.exe",
            "nice_level": 0,
            "num_fds": 774,
            "Memory": {
                "working_set": 75468800,
                "working_set_private": 15372288,
                "private_bytes": 21655552
            },
            "CreateTime": 1665056537
        },
```

Currency, openITCOCKPIT will use the cmdline (if present) over everyting else, because cmdline was expected to be the robustest solution. From the openitcockpit-receiver code:
```php
    private function getProcessName($process) {
        $processName = $process['name'];
        if (!empty($process['exec'])) {
            $processName = $process['exec'];
        }
        if (!empty($process['cmdline'])) {
            $processName = $process['cmdline'];
        }
        return $processName;
    }
```

**Describe the solution you'd like**
It would be good if we would add an extra option to the service template `check_oitc_agent_process` to define if auto (current behavior), cmdline, exec or name should be used.

**Additional context**
This issue is only slightly related to the openITCOCKPIT Monitoring Agent. The issue itself is caused by the check receiver and the check handling of openITCOCKPIT itself. For this reason this issue is not i have **not** created this issue in the https://github.com/it-novum/openitcockpit-agent-go repo.

**Comment by michaelsage** [comment]
Just as a follow up. I've seen the same thing on Windows 7

``
{
            "pid": 612,
            "ppid": 4712,
            "username": "",
            "name": "OneDrive.exe",
            "cpu_percent": 0,
            "memory_percent": 7.569433050857158,
            "cmdline": " \/updateInstalled",
            "status": null,
            "exec": "C:\\Users\\PeterDingle\\AppData\\Local\\Microsoft\\OneDrive\\OneDrive.exe",
            "nice_level": 0,
            "num_fds": 1320,
            "Memory": {
                "working_set": 184664064,
                "working_set_private": 162516992,
                "private_bytes": 241111040
            },
            "CreateTime": 1637405796
        },``

**Comment by michaelsage** [comment]
As a further comment. It seems that monitoring cmdline works for approximately 2-3 days before erroring, I am not sure what changes on the windows box to cause this.

**Comment by nook24** [comment]
Tracked by ITC-2939

**Comment by nook24** [comment]
Pull Request for this is open: https://github.com/it-novum/openITCOCKPIT/pull/1472/files
I will close this issue as soon as the PR gets merged.

**Comment by nook24** [comment]
Part of openITCOCKPIT 4.6.2
https://github.com/it-novum/openITCOCKPIT/releases/tag/openITCOCKPIT-4.6.2

**Comment by michaelsage** [comment]
Thanks for doing this! Is there anything I need to change in existing checks? I went through the agent wizard and I didn't notice any extra options.

**Comment by nook24** [comment]
@michaelsage 

When you edit the service, there should be a new argument `identifier` and the value set to `auto` (default).
![grafik](https://user-images.githubusercontent.com/9019992/223654529-2d2896fd-0e19-4ee9-a5a8-8801ac4f9ce3.png)

Possible values are `auto`, `cmdline`, `exec`, `name` as you can see in the command definition
![grafik](https://user-images.githubusercontent.com/9019992/223654915-d9f6f433-be38-42b2-aadb-cfac955fa2c9.png)

`auto` is the new (and old) default behavior, it will use `cmdline` over `exec` over `name`

Hope this helps
