### ISSUE TITLE
Aktualisieren Sie die Überwachungskonfiguration nicht möglich

### ISSUE THREAD

**Issue by Tweak90** [it-novum/openITCOCKPIT#1435]
Hallo,
meine Kollegen machten mich darauf aufmerksam, dass es in unserer openITCockpit Installation nicht mehr möglich ist Änderungen einzuspielen. Leider kann ich nicht genau ausmachen, was dem Fehler vorausgegangen ist.

![hanging](https://user-images.githubusercontent.com/2485980/200265803-d3aaf26e-8405-4348-b84a-aa3d24f424f8.jpg)
![systemstate](https://user-images.githubusercontent.com/2485980/200266082-44c654ca-3fe9-4cbd-90bc-d60fb68e2389.jpg)
![process2](https://user-images.githubusercontent.com/2485980/200266479-c8d52b91-2c67-40f5-8aed-5c214f6efed0.jpg)

Ich habe alle Updates laufen lassen, leider ohne Erfolg. Natürlich wurde die Maschine auch neu gestartet.

Können Sie mir eventuell helfen? Ansonsten würde ich das System neu aufsetzen.

Version:4.5.3 
Monitoring Engine:Naemon Core 1.3.0

**Comment by nook24** [comment]
Hast du das hier schon gemacht? https://docs.openitcockpit.io/additional/troubleshooting/#aktualisierung-der-uberwachungskonfiguration-hangt-fest

**Comment by Tweak90** [comment]
Vielen Dank 👍
ich hab den Eintrag leider nicht gefunden gehabt 

Läuft wieder alles!
