### ISSUE TITLE
Wrong behaviour of checks with defined time period on holidays

### ISSUE THREAD

**Issue by undertstater** [it-novum/openITCOCKPIT#1515]
**Description:**
I defined a check which should be run only on working days from 10:00 to 19:00 (that's 7:00 PM). Therefore I used a time period where I defined the according time slots. This worked for some days. Means: checks on working days in that slot, no checks at all on Saturdays and Sundays. 
Now I got an alarm on that check from 0:00 in the Morning which should not occur at all. This occurs on 1of June 2023.
I found that 1 of June was defined, in the calendar connected to that time period, as holiday, but only for the year 2020!    

**To Reproduce**
1. Prepare a calendar with a holiday in a past year, but the date of tomorrow. 
2. Prepare a time period with some reduced check execution for working days, especial start the checks in the morning e.g. at 10:00.
3. Prepare a service that uses the time period for check execution. 
4. Check that the checks are working fine.
5. Wait until 10:10 tomorrow and find out when the service did start checking. 

**Expected behavior**
* Services should not start checking on holidays which have been defined for past years. Calendar should ignore holidays from past years.
* Time periods should interpret holidays like Sundays.
<br>

**Screenshots**
If applicable, add screenshots to help explain your problem. You can upload screenshots via drag and drop

https://media.discordapp.net/attachments/1060859853297426453/1113809105535115344/image.png?width=1163&height=579

https://media.discordapp.net/attachments/1060859853297426453/1113824535825887242/Bildschirmfoto_vom_2023-06-01_15-32-12_zensored.png?width=1163&height=402

https://cdn.discordapp.com/attachments/1060859853297426453/1113830430035161109/image.png

**Versions**
* openITCOKPIT Server Version: 4.6.3
*  Ubuntu Server 20.04.6 LTS

**Additional context**
As it seems to be needed to have a date change, i will reproduce the fault over the weekend. So I might add information later on.

**Comment by ibering** [comment]
Resolved by https://github.com/it-novum/openITCOCKPIT/commit/2b56e63ed0a4cf8ede0da73afed0b738fee08a27 and will be part of the next release openITCOCKPIT 4.6.4

Many thanks for your support
