### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by psmoros** [it-novum/openITCOCKPIT#1517]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@tuannq2299) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by nook24** [comment]
Hi @psmoros 

We would like you to ask to report any vulnerabilities  to `security@openitcockpit.io`.
As recommended, we have added the `SECURITY.md` file, which contains all information and contact methods for reporting any security issues. In addition, the email address is also listed in the projects `README.md` file.

We appreciate your help in making our project secure.

**Comment by psmoros** [comment]
Thanks @nook24 <3
