### ISSUE TITLE
Nginx Logrotate - RHEL

### ISSUE THREAD

**Issue by kbilev** [it-novum/openITCOCKPIT#1556]
The logrotate script for nginx `/etc/logrotate.d/openitcockpit-nginx` has a minor bug in RHEL.
The postrotate command `invoke-rc.d nginx rotate >/dev/null 2>&1` is not available under RHEL, the standard nginx command should instead be used: ``/bin/kill -USR1 `cat /run/nginx.pid 2>/dev/null 2>/dev/null` || true``

**Comment by nook24** [comment]
Good catch! I have updated the logrotate configuration for RHEL based systems as suggested. This will be available with the next stable release.

![grafik](https://github.com/it-novum/openITCOCKPIT/assets/9019992/d69f5922-508b-4de9-bc1e-019703812c3f)

Thanks for letting us know!
