### ISSUE TITLE
Downtimes nicht löschbar in /downtimes/hosts

### ISSUE THREAD

**Issue by kbilev** [it-novum/openITCOCKPIT#1564]
**Describe the bug**
User können Downtimes in der Übersicht (/downtimes/host) nicht löschen, sondern nur direkt im Host Objekt

**To Reproduce**

- Folgende User Role (vereinfacht zum reproduzieren reicht es):
  - Browsers:index
  - Downtimes: Host,service,delete
  - Hosts: index, browser, externalcommands
  - Systemdowntimes: all
- Berechtigung: /root/X
- Host auch im Container /root/x

**Expected behavior**
Der User kann jetzt seine Hosts sehen und Downtimes erstellen. Diese kann er löschen wenn er auf dem Host ist. In der Übersicht, wird der "Löschen" Button aber nicht angezeigt. Man sollte Downtimes auch in der Übersicht löschen können.

Gebe ich dem User jetzt ausserdem Rechte auf /root, wird der "Löschen" Button angezeigt.

**Screenshots**
![image](https://github.com/it-novum/openITCOCKPIT/assets/4117419/b98d2124-fc82-4fe2-b4e8-ea97cc23e6aa)

**Versions**
* openITCOKPIT Server Version: 4.6.8
*  RHEL

**Comment by ibering** [comment]
ITC-3091

**Comment by ibering** [comment]
This issue was resolved with version [4.6.9](https://github.com/it-novum/openITCOCKPIT/releases/tag/openITCOCKPIT-4.6.9) behoben
