### ISSUE TITLE
Downtime nicht löschbar in Host, wenn doppelt erstellt

### ISSUE THREAD

**Issue by kbilev** [it-novum/openITCOCKPIT#1565]
**Describe the bug**
Falls mehrere Downtimes auf einem Host erstellt wurden, und eine gelöscht, wird nachher die Downtime Info im Host falsch angezeigt.

**To Reproduce**
Man erstellt eine erste Downtime "in progress 1" auf Host X. 
Aus unbestimmten Grund erstellt man eine zweite Downtime "in progress 2" auf dem selben Host.
Jetzt löscht man Downtime "in progress 2".
Es wird korrekterweise angezeigt, dass eine Downtime besteht, jedoch die Informationen von der gelöschten Downtime.

**Expected behavior**
Nachdem löschen der Downtime "in progress 2", sollten die Informationen von "in progress 1" angzeigt werden.
Man kann jetzt auch nicht die erste Downtime "in progress 1" löschen, und wegen Issue "#1564" kann nur ein root User die Downtime löschen.

**Screenshots**
![image](https://github.com/it-novum/openITCOCKPIT/assets/4117419/bc74edf9-6ebf-4149-adce-bd8ca5360b5f)
![image](https://github.com/it-novum/openITCOCKPIT/assets/4117419/8b72cca4-2f0a-4ac1-90a8-687dde855cf5)

**Versions**
* openITCOKPIT Server Version: 4.6.8
*  Operating system

**Additional context**
Möglicherweise sollte man jede Downtime anzeigen, nicht nur die letzte?

**Comment by ibering** [comment]
ITC-3092
