### ISSUE TITLE
Host group extended view - Last Check time not available

### ISSUE THREAD

**Issue by kbilev** [it-novum/openITCOCKPIT#1596]
**Describe the bug**
In the extended Hostgroups view (/#!/hostgroups/extended/) the "Last Check" Time is displayed as "n/a" when a host is monitored via a satellite.
When viewing the host in the hosts/index view or going into the host, the "Last Check" Time is displayed correct. 

**To Reproduce**
Monitor a host via Satellite
Add the host to a hostgroup
View the extend view of the hostgroup

**Expected behavior**
In the extended hostgroup view, the "Last Check" time should be displayed. 
Maybe also the "Next Check", or an estimated "Next check"? (Next Check = +-Last Check + check intervall)

**Versions**
* openITCOKPIT Server Version: 4.6.8
* RHEL

**Comment by ibering** [comment]
ITC-3186

**Comment by ibering** [comment]
Resolved by https://github.com/it-novum/openITCOCKPIT/pull/1668 and will be part of the next release openITCOCKPIT 4.7.2

Many thanks for your support

**Comment by nook24** [comment]
Thanks for reporting, the `Last check` field was missing on some pages for passive services. We have fixed this :)
