### ISSUE TITLE
Refresh monitoring configuration slow

### ISSUE THREAD

**Issue by kbilev** [it-novum/openITCOCKPIT#1601]
**Describe the bug**
It takes up to 2 minutes to for the task "Create service configuration" to finish when refreshing the monitoring configuration.

**To Reproduce**
3061 hosts are monitored
18712 services are monitored 
Why it is in our case slow and not in others, good question

**Expected behavior**
less than 2 minutes for a config push

**Screenshots**
![addIndex](https://github.com/it-novum/openITCOCKPIT/assets/4117419/7f631d60-6b0d-43fd-8444-c818f2f5afa2)

**Versions**
* openITCOKPIT Server Version: 4.6.8

**Solution**
```create index `service_id` on servicecommandargumentvalues(`service_id`);```

**Comment by ibering** [comment]
Resolved by https://github.com/it-novum/openITCOCKPIT/pull/1603 and will be part of the next release openITCOCKPIT 4.6.10

Many thanks for your support

**Comment by ibering** [comment]
Hallo @kbilev 

Bei unseren Testsystemen war es nicht so bemerkbar. Wahrscheinlich haben unsere Testsysteme nicht so viel Last. Es kann natürlich auch an der MySQL Konfiguration liegen, dass der MySQL Server die fehlende Indizies durch die Performance ausgleicht. Ich habe aber testweise eine Abfrage gebaut, die ein System mit 88000 Services, nach Commandargumentvalues abfragt. Und die Perfomance-Steigerung war enorm. Von ~5 Minuten auf 2 Sekunden. Und das ist schon ziemlich beeindruckend. 

Vielen Dank für Dein Hinweis :)

**Comment by ibering** [comment]
Das Problem wurde in der Version [4.6.10](https://github.com/it-novum/openITCOCKPIT/releases/tag/openITCOCKPIT-4.6.10) behoben
