### ISSUE TITLE
Add/Edit User - Container Problem

### ISSUE THREAD

**Issue by kbilev** [it-novum/openITCOCKPIT#1604]
**Describe the bug**
The problem appears when trying do add or edit a LDAP User.
When a User does not match a Container Role through LDAP, we cannot add the user when not selecting a Container, even when we select a Container Role

**To Reproduce**
1. Add User through LDAP
2. User does not match a Container Role through LDAP
3. Select a Container Role for the User
4. Do not select a Container, as we want the containers managed via Container Roles
5. Save

**Expected behavior**
This should be possible, as the user has access to containers through the container Role

**Screenshots**
![ldapUser](https://github.com/it-novum/openITCOCKPIT/assets/4117419/7bf35d48-7c39-437c-9647-fc1bec2c7954)

**Versions**
* openITCOKPIT Server Version: 4.6.8

**Comment by ibering** [comment]
ITC-3120

**Comment by ibering** [comment]
Resolved by https://github.com/it-novum/openITCOCKPIT/pull/1606 and will be part of the next release openITCOCKPIT 4.6.10

Many thanks for your support

**Comment by nook24** [comment]
Resolved with https://github.com/it-novum/openITCOCKPIT/releases/tag/openITCOCKPIT-4.6.10
