### ISSUE TITLE
Tachograph - minimum value not used

### ISSUE THREAD

**Issue by kbilev** [it-novum/openITCOCKPIT#1656]
**Describe the bug**
In the Tachograph Widget (and probably also the other Widgets using minium values) the minium value is not used.
The minimum is always 0

**To Reproduce**
Create a check script and add a widget using the metric.
```
#!/bin/bash

echo "this is a bug | metric=50;20;70;10;150"
exit 0
```

**Expected behavior**
Use the provided minimum value

**Screenshots**
![image](https://github.com/it-novum/openITCOCKPIT/assets/4117419/21b44be5-ce94-4c27-ac48-466eb5ebe997)
![image](https://github.com/it-novum/openITCOCKPIT/assets/4117419/5f89789a-68b9-4ec3-98d7-9758ab144006)

**Versions**
* openITCOCKPIT Server Version: 4.7.0

**Additional context**

The Github Bug Report Template has a typo: 
* openIT**COK**PIT Server Version: 4.x.x

**Comment by Jan-Nox** [comment]
Hi kbilev,

We are aware of this bug, and we are currently working on it. [ITC-

Several small improvements to the dashboards and performance data thresholds are already in development and waiting for quality assurance right now.

So my test performance data is ``` 'value'=16.753Wh;5:25;0:30;-20:40 ```...
![grafik](https://github.com/it-novum/openITCOCKPIT/assets/49352527/86d2cc01-7a90-4bc6-b3b6-8ec36a855d9c)

... and as expected, the scale is actually working on our gages and map items as well:
![grafik](https://github.com/it-novum/openITCOCKPIT/assets/49352527/83025fea-fbbc-4e68-83df-a927d4a7c670)

![grafik](https://github.com/it-novum/openITCOCKPIT/assets/49352527/3c48343a-7c24-41c9-9624-f95a5e483b40)

I'll provide updates on this issue as soon as I have any news on the topic.

Kind regards
Jan
