### ISSUE TITLE
Permission Services:externalCommands has no effect

### ISSUE THREAD

**Issue by kbilev** [it-novum/openITCOCKPIT#1663]
**Describe the bug**
We can enable or disable the "Services:externalCommands" permission for a User. This has no effect on the Service Browser.
The "Hosts:externalCommands" seems to be used for the service browser.
I think it is a copy/paste problem in "/src/Controller/ServicesController.php#L1779"
`$canSubmitExternalCommands = $this->hasPermission('externalcommands', 'hosts');`

**To Reproduce**
Enable and disable the "Services:externalCommands" permission.

**Expected behavior**
Enable or disable the commands on the service browser page.

**Versions**
* openITCOCKPIT Server Version: 4.7.0

**Comment by kbilev** [comment]
`/src/Template/Services/index.php#L1113` seems have the same problem

**Comment by ibering** [comment]
ITC-3185

**Comment by ibering** [comment]
Resolved by https://github.com/it-novum/openITCOCKPIT/pull/1667 and will be part of the next release openITCOCKPIT 4.7.2

Many thanks for your support

**Comment by kbilev** [comment]
probably also "/src/Template/Services/service_list.php" impacted?
