### ISSUE TITLE
SLA Information not visible on Service Browser

### ISSUE THREAD

**Issue by kbilev** [it-novum/openITCOCKPIT#1671]
**Describe the bug**
On the Service Browser (/#!/services/browser/id) the SLA Button is not shown, when a SLA is defined via the Host Template.

**To Reproduce**
1. Create a Host via Hosttemplate that has a SLA associated
2. Create a Service and goto the browser.
3. You don't get the SLA button (ng-show="slaOverview")

**Expected behavior**
Display the SLA Button

**Versions**
* openITCOCKPIT Server Version: 4.7.0

**Additional context**
When a Host SLA is defined via hosttemplate, the `sla_id` field remains `null` in the host.
In the ServicesController.php public function loadSlaInformation() it is only checked if the host has an `sla_id` defined ( `$hostSlaId = $host['Host']['sla_id'];` ).
When it is null, a second check needs to be done to get the `sla_id` via the hosttemplate.

**Comment by kbilev** [comment]
to complete the bugreport: the function in the SLA plugin also only checks for the host sla_id

**Comment by ibering** [comment]
ITC-3189
