### ISSUE TITLE
"Service template groups" Permissions not working

### ISSUE THREAD

**Issue by kbilev** [it-novum/openITCOCKPIT#1695]
**Describe the bug**
A non-root user with full permissons on the "Servicetemplategroups" can only create new Service Template Groups, but afterwards not change or delete them.

**To Reproduce**
1. User with all Servicetemplategroups permissions on a container
2. create a new service template group
3. you can not delete or modify the group

**Expected behavior**
You should have the given rights

**Versions**
* openITCOCKPIT Server Version: 4.8.0

**Additional context**
The bug seems to be in `src/Controller/ServicetemplategroupsController.php` Line 91.
It seems to work as expected when changing the line from
`$servicetemplategroup['allow_edit'] = $this->isWritableContainer($servicetemplategroup['Servicetemplategroup']['container_id']);`
to
`$servicetemplategroup['allow_edit'] = $this->isWritableContainer($servicetemplategroup['container_id']);`

**Comment by nook24** [comment]
Tracked by ITC-3355
