### ISSUE TITLE
Users Edit and Delete permissions not working

### ISSUE THREAD

**Issue by kbilev** [it-novum/openITCOCKPIT#1706]
**Describe the bug**
A User with only permissions on "Users - Index, Edit, Delete" has no rights to edit users in a container where he has access via "container roles".

**To Reproduce**
1. Create container Role with container "/root/bug" r/w
2. Create user role "user edit only" with "Users - index, edit, delete"
3. Give a user the new user role and access to the container role
4. The user cannot edit himself.
5. If you add the container /root/bug to the user, he can edit himself

**Expected behavior**
The user has access to /root/bug and should be able to edit himself

**Versions**
* openITCOCKPIT Server Version: 4.8

**Comment by nook24** [comment]
Tracked by ITC-3362
