### ISSUE TITLE
Usercontainerroles - index not working

### ISSUE THREAD

**Issue by kbilev** [it-novum/openITCOCKPIT#1708]
**Describe the bug**
A user with the "Usercontainerroles - index" permission cannot see the user roles in his container

**To Reproduce**
1. Create "user role" with permissions on "Usercontainerroles - index"
2. Create a "user container role" in the container /root/bug
4. Give an user the "user role" and access to the container /root/bug
5. He is not able to see any "user container role"

**Expected behavior**
The user should see the "user container roles" that are in the container /root/bug

**Versions**
* openITCOCKPIT Server Version: 4.8

**Comment by nook24** [comment]
Tracked by ITC-3360
