### ISSUE TITLE
Service Escalation verschwindet nach "Refresh Monitoring Configuration" bei Verwendung von Service Templates in Service Gruppen

### ISSUE THREAD

**Issue by Mseegel-Lang** [it-novum/openITCOCKPIT#1733]
Description: Ich habe Schwierigkeiten, Service Escalations als Benachrichtigungen in Verbindung mit Service Templates einzurichten. Hier die genaue Beschreibung des Problems:

1. Ich habe eine neue Service Group unter "Groups" erstellt.
2. In dieser Service Group wurden sieben Service Templates vom oitc Agent hinzugefügt.
3. Aus den sieben Service Templates entstanden über 500 Service Checks, die nun in der Service Group aufgelistet sind.
4. Anschließend wurde versucht, eine Service Escalation für diese Service Group einzurichten, sodass Benachrichtigungen per E-Mail gesendet werden.
5. Nach dem Erstellen der Service Escalation und dem anschließenden Klicken auf "Refresh Monitoring Configuration" verschwindet die erstellte Service Escalation aus der Liste. Dementsprechend werden auch keine Benachrichtigungen versendet.

Problemvermutung: Ich vermute, dass OITC die Services in der Service Gruppe möglicherweise nicht korrekt erkennt, weil ich in der Service Gruppe die Service Templates und nicht direkt die einzelnen Service Checks hinzugefügt habe.

Erwartetes Verhalten:
Die Service Escalation, erstellt durch eine Service Group mit hinterlegten Service Templates, sollte auch nach dem Refresh Monitoring Configuration sichtbar und funktionsfähig bleiben.

Tatsächliches Verhalten:
Nach dem Aktualisieren der Überwachungskonfiguration verschwindet die neu erstellte Service Escalation aus der Liste.

Schritte zur Reproduktion:
Erstellen einer neuen Service Group unter Groups.
Hinzufügen von Service Templates (vom oitc Agent) zur Service Group.
Einrichten einer Service Escalation für die erstellte Service Group.
Klicken auf "Refresh Monitoring Configuration".
Prüfen, ob die Service Escalation noch in der Liste vorhanden ist (sie verschwindet).

Weitere Beobachtungen:
Wenn ich eine Service Gruppe erstelle und die Services manuell hinzufüge (anstatt über Vorlagen), funktioniert die Konfiguration und die Service Escalation bleibt nach einem Refresh bestehen.

Umgebung:
OITC 4.8.2
Server OS: Ubuntu 22.04

Weitere Fragen:
Werden Service Templates und ihre daraus abgeleiteten Service Checks von der Service Escalation nicht als gleichwertig erkannt?
Ist eine spezifische Konfiguration nötig, um Service Templates in Escalations verwenden zu können?
Gibt es bekannte Einschränkungen bei der Verwendung von Service Templates innerhalb von Service Escalations?
Vielen Dank für die Unterstützung bei diesem Problem.

![image](https://github.com/user-attachments/assets/e5c3af5d-50bb-4e30-9faf-7de346ee7daf)
![image](https://github.com/user-attachments/assets/c91aca4e-d523-4a2b-8746-11c44307415f)
![image](https://github.com/user-attachments/assets/83e8fb08-23ed-456b-a2a2-e4c475db43ff)
![image](https://github.com/user-attachments/assets/0c0858f3-46f5-42aa-9c31-afa53b869041)

**Comment by ibering** [comment]
Tracked by ITC-3397

**Comment by ibering** [comment]
Hallo @Mseegel-Lang,

der Fehler wurde in der Version 4.8.3 behoben.

Viele Grüße
Irina
