### ISSUE TITLE
Dependencies werden nicht aufgelöst

### ISSUE THREAD

**Issue by m-terlinde** [it-novum/openITCOCKPIT#183]
Hallo,

mein Ubuntu 16.04 Server kann die Dependencies nicht automatisch auflösen, wenn ichi `apt-get install openitcockpit{,-naemon,-statusengine-naemon,-npcd}` eingebe und abschicke bekomme ich die Fehlermeldung, dass "openitcockpit-commom" fehlt.
Liegt das am Paket, oder fehlt das schlicktweg in der Readme Datei?

Vielen Dank und viele Grüße,
Matthias

**Comment by m4ximum** [comment]
Hi, 
das Paket ist noch nicht für 16.04 gebaut und ist mit systemd aktuell auch noch nicht lauffähig. Bitte mal mit 14.04 probieren ;)

**Comment by m-terlinde** [comment]
Moin moin,

habe gerae noch mal Rücksprache mit meinem Kollegen gehalten, der hatte doch 14.04.4 installiert, es liegt also leider nicht am 16.04er.

Ich probiere das aber auf jeden Fall noch mal mit einem Clean Install.

Viele Grüße
Matthias

**Comment by m-terlinde** [comment]
Moin moin,

das Problem ist jetzt nicht noch einmal aufgetreten.

Ich denke das Issue kann geschlossen werden.

Vielen Dank und viele Grüße
Matthias
