### ISSUE TITLE
Monitoring engine not running

### ISSUE THREAD

**Issue by tobibe** [it-novum/openITCOCKPIT#418]
Hallo,

ich habe seit kurzem vor ca 14 Tagen ein Update des openIT-Cockpit eingespielt und seit dem bekomme ich immer die Meldung auf z.B. der Hosts-Seite, dass die Monitoring-Engine nicht laufen würde
![nagios monitoring](https://cloud.githubusercontent.com/assets/9305993/22457799/d6c6c182-e799-11e6-8795-f57b651811ab.PNG)

Laut den Debug-Informationen tut sie das aber und die einzelnen Überwachungsabfragen laufen auch
![nagios debug](https://cloud.githubusercontent.com/assets/9305993/22457821/f8e4d678-e799-11e6-9fa0-7306e23d1a6b.PNG)

Ich habe heute das neueste Update eingespielt, aber der Fehler erscheint trotzdem.

PS: ansonsten ein großes Lob für die neue Oberfläche :)

Grüße
tobibe

**Comment by nook24** [comment]
Hi tobibe,
verwendest du die stable oder nightly Pakete? Aktuell erstellen die nightlys keine Einträge in den Systemsettings...

Leider haben wir im aktuellen Release noch einen Bug, das Einträgt aus den Systemsettings  überschrieben werden.

Das ganze wurde hier https://github.com/it-novum/openITCOCKPIT/pull/414 behoben. Wir werden heute im laufe des Tages neue stable Pakete bauen, die das Problem beheben.

Sobald die neue Version veröffentlicht ist, kannst du wie folgt vorgehen:
````
apt-get update
apt-get dost-upgrade
openidtcockpit-update (hier die nachfragen mit y beantworten :))
````

Viele Grüße,

Daniel

**Comment by tobibe** [comment]
Hallo Daniel,

ich verwende die stable. 
Dann werde ich heute abend oder morgen früh mal noch ein Update anstossen :-)

Ich werde dann auch schreiben, obs geklappt hat.

Vielen Dank für die schnelle Antwort und viele Grüße
tobibe

**Comment by nook24** [comment]
Hi @tobibe,

die neue Version 3.0.10-3 ist gerade veröffentlicht worden. Du kannst dein System jetzt wie folgt aktualisieren:
````
apt-get update
apt-get dist-upgrade
openitcockpit-update (hier die nachfragen mit y beantworten :))
````

Eventuell ist danach auch gleich das Problem mit #419 gelöst.

**Comment by tobibe** [comment]
Hallo @nook24 ,

danke schön. Die Meldung mit dem nicht laufenden Monitor ist jetzt weg. 
Der Issue #419 ist aber leider noch nicht gelöst.

Grüße
tobibe
