### ISSUE TITLE
Dashboard - Graphgenerator not allowed

### ISSUE THREAD

**Issue by tobibe** [it-novum/openITCOCKPIT#419]
Hallo,

ich wollte auf dem Dashboard einen Graphen anzeigen lassen, bekomme aber immer nur die Fehlermeldung, dass die Aktion nicht erlaubt ist. Ich bin aber als Admin eingeloggt.
![nagios graph](https://cloud.githubusercontent.com/assets/9305993/22458048/094ec266-e79b-11e6-850c-719b983453f9.PNG)

Grüße
tobibe

**Comment by nook24** [comment]
Hi @tobibe,

ich vermute du hast einen Admin Account bei dir am System. Kannst du unter Administration > Manage User Roles dir über das Icon mit dem Harken nochmal alle Rechte setzen:
![bildschirmfoto 2017-01-31 um 15 12 22](https://cloud.githubusercontent.com/assets/9019992/22468218/cc6e1f7c-e7c7-11e6-822b-fb5f6730dfa8.png)

**Comment by tobibe** [comment]
Hallo @nook24,

genau das wars. Das View-Recht für die Grafen hat gefehlt.
Danke schön.

Gruß
tobibe
