### ISSUE TITLE
Cronjob Intervall Konfiguration redundant (?)

### ISSUE THREAD

**Issue by becon-cmichel** [it-novum/openITCOCKPIT#603]
Hi, 
zuerst ist mir lediglich ein Typo in den Systemsettings ins Auge gesprungen:

` app/src/itnovum/openITCOCKPIT/InitialDatabase/Systemsetting.php`
`             [`
`                  'Systemsetting' => [`
` -                    'key'      => 'CRONJOB.CLENUP_TEMPFILES',`
` +                    'key'      => 'CRONJOB.CLEANUP_TEMPFILES',`

Dort lässt sich auch ein Intervall für diesen Job definieren. 

Anschließend fiel mir aber auf, dass unter dem Menüpunkt "Administration" -> "Cron Jobs" ebenfalls ein Job mit dem Namen "CleanupTemp" vorhanden ist. Auch hier lässt sich ein Intervall einstellen - beide unabhängig voneinander.

Daher mein Frage, ob das zwei unterschiedliche Cronjobs sind, oder dieselben? Beim schnellen Überfliegen des Codes konnte ich niergendwo sehen, dass das Intervall, welches in den Systemsettings definiert wird, irgendwo verwendet wird. 

Danke und Grüße :)

**Comment by nook24** [comment]
Hi @becon-cmichel,
danke für die Info. Die Einstellungen in den Systemsettings werden nicht mehr genutzt, sondern die Cronjobs können alle über Administration -> Cron Jobs eingestellt werden:
![openitcockpit-cronjobs](https://user-images.githubusercontent.com/9019992/28010895-ba9c5716-6560-11e7-9464-afc437c60c4a.png)

Ich habe die entsprechenden Einstellungen aus dem Standard entfernt (#612).

Viele Grüße,

Daniel
