### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by becon-cmichel** [it-novum/openITCOCKPIT#604]
Hi,

unter dem Menüpunkt "Administration" -> "Registration" ist der Link auf die it-novum Webseite hinter "Please visit our homepage to get in contact." tot. 

Danke und Grüße :)

**Comment by nook24** [comment]
Hi @becon-cmichel,
danke dir, wird mit dem PR #611 dann behoben :)

Viele Grüße,
Daniel
