### ISSUE TITLE
Remove dependency to phpmyadmin

### ISSUE THREAD

**Issue by Skywalker-11** [it-novum/openITCOCKPIT#628]
Is there a reason for openitcockpit-message having a dependency to phpmyadmin? If not can you change this to a recommendation?

**Comment by oliver-mueller** [comment]
We add this dependencie because openitcockpit-message should be last package which is installed because it should show you the next steps after an installation. We moved the dependencie to recommends. We hope this will handle your issue.

**Comment by Skywalker-11** [comment]
Thanks. Did you remove it from all repositories? I just noticed that the current release in the trusty repo doesn't have it as dependency but the others repos do.

**Comment by oliver-mueller** [comment]
Yes we changed it for all repos.
