### ISSUE TITLE
Host kopieren | Zuweisung zu Satellit geht verloren

### ISSUE THREAD

**Issue by becon-cmichel** [it-novum/openITCOCKPIT#629]
Hallo,

eine kleine Unschönheit im Handling ist mir aufgefallen.
Wenn man einen Host kopiert, der einem Satelliten zugewiesen ist, dann ist der neue Host immer automatisch dem Mastersystem zugeordnet. Meiner Meinung nach wäre es richtig, wenn der kopierte Host derselben Instanz zugewiesen ist, wie sein Original.
Alternativ könnte man in der Kopiermaske - neben Hostname, Beschreibung, IP Adresse und Host URL - auch die Instanz abfragen. Eine Übernahme der Instanz des originalen Hosts für die Kopie fände ich aber besser und entspricht auch eher dem Sinn einer "Kopie". 

Danke und Grüße :)

**Comment by nook24** [comment]
Resolved with ddbbce2821b66da81a3a84917cb09e427c8d760a
