### ISSUE TITLE
Passwortanforderungen | Installation und Profil

### ISSUE THREAD

**Issue by becon-cmichel** [it-novum/openITCOCKPIT#630]
Hallo,

bei dem Setzen des Passworts sind mir ein paar Punkte aufgefallen. 

1. Bei der Installation von openITCOCKPIT wird der Benutzer aufgefordert ein Passwort einzugeben:
```
The password must consist of 6-12 alphanumeric characters and must contain at least one digit
Please enter a password for the login.  
```
Zum einen ist es unschön, dass hier keine längeren Passwörter eingeben werden können. Aus Nutzersicht gibt es keinen offensichtlichen Grund, das Passwort auf zwölf Zeichen zu beschränken. 
Zudem sollte das Passwort gemäß IT-Grundschutz mindestens acht Zeichen lang sein. 
(https://www.bsi.bund.de/DE/Themen/ITGrundschutz/ITGrundschutzKataloge/Inhalt/_content/m/m02/m02011.html). 
Zuletzt ist hier auch unschön, dass das eingegebene Passwort im Klartext auf der Kommandozeile sichtbar ist.

2. Später, in den Einstellungen des Benutzerprofils, lässt sich das Passwort dann ohne die vorherigen Beschränkung setzen - auch wenn hier dieselben Anforderungen, wie bei der Installation, angegeben werden:

![oitcv3_passwort](https://user-images.githubusercontent.com/9606222/28414537-629d90c2-6d4c-11e7-9185-b1efe9f86d57.png)

Sprich, ein Passwort mit drei Zeichen, als auch ein Passwort mit 15 Zeichen lässt sich setzen. 
Hier müsste also zum einen der Info-Text angepasst werden, desweiteren sollten hier keine Passwörter, die kürzer als acht Zeichen sind, zugelassen werden.  

Danke und Grüße :)

**Comment by jackdown** [comment]
Hi, die beschränkung auf 12 Zeichen macht tatsächlich weniger Sinn, da werden wir schauen. Die Die Kürze mit 6 Zeichen finde ich akzeptabel. Die Beschränkung auf: es muss auch eine Zahl enthalten finde ich auch obsolet und sollte entfernt werden(da diese Regel die Sicherheit verringert). Die längen Begrenzung mit 12 Zeichen ist tatsächlich idiotisch und werden wir entfernen.
Falls du die Software unter BSI Gesichtspunkten betreiben möchtest solltest du LDAP oder ein AD nutzen der wiederum eigene Regeln haben kann.

**Comment by nook24** [comment]
Noch als kurze Ergänzung,
die Länge des Passworts muss nur >= 6 Zeichen sein. Nach oben gibt es aktuell nur die Beschränkung durch das DB Feld (VARCHAR 45), bzw. durch den Hash-Algorithmus...

Der Hilfetext müsste allerdings aktualisiert werden.
Es gelten auch überall die gleichen Regeln für das Passwort. Leider wird bei den Profileinstellungen der Fehler nicht abgefangen, wenn auf Grund der Validierung das Passwort nicht geändert wurde :( 

Das das Passwort bei der initiale Installation auf der Konsole angezeigt wird, finde ich nicht weiter trage. Dort kannst du ja für die Installation erst einmal etwas simples wie `Eistee123` verwenden, und es dann sofort über die Oberfläche ändern :)

**Comment by nook24** [comment]
Die standard Passwortanforderungen ist wie folgt:

- Passwort muss mindestens sechs Zeichen lang sein
- Eines der sechs Zeichen muss eine Zahl sein

Die Passwortanforderungen werden mit https://github.com/it-novum/openITCOCKPIT/commit/0b17e480044a2ef8a0684b91b3b6a96252d35724 jetzt überall angezeigt, wo Benutzer das Passwort setzen können.
