### ISSUE TITLE
Service-state-acknowledgement: Platzhalter in Benachrichtigung nicht gefüllt

### ISSUE THREAD

**Issue by tobibe** [it-novum/openITCOCKPIT#642]
Hallo,

wenn ich in der aktuellen Version den fehlerhaften Status eines Services "acknowledge" werden in der darauffolgenden Email-Benachrichtigung die Platzhalter nicht gefüllt:

![2017-08-02 12_22_55-posteingang - becker dextratec com - microsoft outlook](https://user-images.githubusercontent.com/9305993/28869608-999210cc-777d-11e7-9b35-e2302062fea9.png)

Hier noch meine Systemdaten:
![2017-08-02 12_15_23-administrators - open source system monitoring](https://user-images.githubusercontent.com/9305993/28869556-6e38b23c-777d-11e7-9c3e-9a3ff49dfc2a.png)

Grüße
tobibe

**Comment by tobibe** [comment]
Hallo,

zusätzlich hätte ich noch die Frage, wann man dann wieder Benachrichtigungen vom System bekommt? Wenn der Service einmal wieder keinen Fehler gemeldet hat?

Grüße
tobibe

**Comment by nook24** [comment]
Hi @tobibe,
sorry dein Issue ist etwas untergegangen, hat der GitHub-Bot wohl nicht richtig weitergeleitet :(

Damit das Acknowledgement richtig angezeigt werden kann, musst du eventuell deine Nagios Kommandos, welche die Benachrichtigung verschicken, etwas anpassen.

Das Feature mit den Acknowledgements ist erst nachträglich eingebaut worden, und anscheinend wurden bei dir am System die Kommandos nicht automatisch aktualisiert.

Gehe dazu einfach nach `Basic Monitoring` -> `Commands` -> `Notifications` und ersetze ersetzte die Kommandos `host-notify-by-cake` und `service-notify-by-cake`.

Für **host-notify-by-cake** setzt du als command_line folgendes
````
/usr/share/openitcockpit/app/Console/cake nagios_notification -q --type Host --notificationtype $NOTIFICATIONTYPE$ --hostname "$HOSTNAME$" --hoststate "$HOSTSTATE$" --hostaddress "$HOSTADDRESS$" --hostoutput "$HOSTOUTPUT$" --contactmail "$CONTACTEMAIL$" --contactalias "$CONTACTALIAS$" --hostackauthor "$HOSTACKAUTHOR$" --hostackcomment "$HOSTACKCOMMENT$"
````

Für **service-notify-by-cake** setzt du als command_line:
````
/usr/share/openitcockpit/app/Console/cake nagios_notification -q --type Service --notificationtype $NOTIFICATIONTYPE$ --hostname "$HOSTNAME$" --hoststate "$HOSTSTATE$" --hostaddress "$HOSTADDRESS$" --hostoutput "$HOSTOUTPUT$" --contactmail "$CONTACTEMAIL$" --contactalias "$CONTACTALIAS$" --servicedesc "$SERVICEDESC$" --servicestate "$SERVICESTATE$" --serviceoutput "$SERVICEOUTPUT$" --serviceackauthor "$SERVICEACKAUTHOR$" --serviceackcomment "$SERVICEACKCOMMENT$"
````

Damit sollten in zukünftigen Benachrichtigungen die Informationen dann enthalten sein.
Beispiel:
![bildschirmfoto 2017-08-28 um 15 51 11](https://user-images.githubusercontent.com/9019992/29776585-56068f72-8c09-11e7-905b-2f82280dac85.png)

Zur zweiten Frage,
Wenn in deinem Kontakt, und deiner Host bzw. Server Definition die Benachrichtigungen für _ Recovery_ aktiviert sind, dann bekommst du diese sobald der Host oder Services wieder im Status Up/Ok ist, also wieder grün.

**Comment by tobibe** [comment]
Danke schön. 
Jetzt funktioniert alles :-)
