### ISSUE TITLE
Community-Version zeigt Pakete der Enterprise Version

### ISSUE THREAD

**Issue by farosch** [it-novum/openITCOCKPIT#721]
Obwohl unter _Administration_ > _Registration_ der Key der Community-Version (0dc0d951-e34e-43d0-a5a5-a690738e6a49) eingetragen ist, sind im _Package Manager_ neben **check_nrpe** auch alle nachfolgenden Enterprise-Module aufgelistet und installierbar.

**AutoreportModule
MkModule
DistributeModule
MapModule
IdoitModule
EventcorrelationModule
MassenversandDeModule
DesignModule
WMIModule
PostgresModule
NWCModule
LinuxBasicMonitoringModule
PagerdutyModule
GrafanaModule**

**Comment by cfleck** [comment]
Hallo @farosch,
vielen Dank für den Hinweis. Dies ist allerdings kein Fehler sondern gewollt denn wir haben uns entschieden fast alle Module künftig kostenfrei zur Verfügung zu stellen.

**Comment by farosch** [comment]
@cfleck Das sind ja sehr gut Nachrichten! In dem Fall - case closed
