### ISSUE TITLE
Unable to create Downtime over midnight

### ISSUE THREAD

**Issue by farosch** [it-novum/openITCOCKPIT#728]
A service downtime cannot be created over midnight as the system simply checks if the "From"-date lies before the "To"-date.
I think these time fields should be extended with a date, so that I can put for example
From: 17.12.17 23:10
To: 18.12.17 09:00

![chrome_2017-12-17_11-21-20](https://user-images.githubusercontent.com/22905106/34078725-4888cd9c-e320-11e7-8573-34c8d626ade7.png)

**Comment by m4ximum** [comment]
Yep this is truly not that well solved. The Problem here is the recurring downtime you have chosen.
 
The downtime should be from 23:50 to 00:10 the next day but 365 days a year. Adding a date field would make no sense here.
What you can do as a workaround is creating a Downtime from 23:50 to 23:59 and another downtime from 00:00 to 00:10.

**Comment by farosch** [comment]
You're right, a datetime wouldn't make much sense, but how about a checkbox or something?
I don't think recurring downtimes over midnight are something rare and a lot of people may have this issue. There should be a fix for this..
If I do what you suggested what will happen between 23:59:00 and 23:59:59? Won't the checks fire then?

**Comment by nook24** [comment]
Hi @farosch, its on our backlog to refactor the form for recurring downtimes.
I guess we will solve this with a duration field.

For example:
Start time: 23:50
Duration: 1h

**Comment by ibering** [comment]
Fixed by #744 #748 #737

**Comment by ibering** [comment]
Hello @farosch,
this issue will be fixed with #737  
![downtimes](https://user-images.githubusercontent.com/9592910/35139906-6a5fc4a4-fcf5-11e7-8a2d-f1fb997138da.png)

Thanks for the feedback.

**Comment by nook24** [comment]
Issue is resolved with current release.
