### ISSUE TITLE
Gezielteres Erstellen von Zeitperioden

### ISSUE THREAD

**Issue by Tweak90** [it-novum/openITCOCKPIT#757]
Beim Ablösen von Nagios durch openITCOCKPIT stoße ich auf folgendes Problem:
Ich habe bestimmte Sensoren, welche nur außerhalb der Arbeitszeit, an Wochenenden und an Feiertagen abgefragt werden sollen. Leider finde ich im openITCOCKPIT keine Möglichkeit für so eine Detaillierte Einstellung einer Timeperiod.

Folgende Einstellung nutze ich in Nagios, die Feiertage, die für mich relevant sind, habe ich selbst festgelegt:

define timeperiod {
  timeperiod_name                out_of_work_hours
  alias                          Zeitraeume, in denen die EDV unbesetzt ist.
  use 							 de-holidays
  monday                         00:00-07:30,12:15-13:15,16:30-24:00
  tuesday                        00:00-07:30,12:15-13:15,16:30-24:00
  wednesday                      00:00-07:30,12:15-13:15,16:30-24:00
  thursday                       00:00-07:30,12:15-13:15,16:30-24:00
  friday                         00:00-07:30,13:15-24:00
  saturday                       00:00-24:00
  sunday                         00:00-24:00
}

define timeperiod {
  name                           de-holidays
  timeperiod_name                de-holidays
  alias                          Deutsche Feiertage
  december 24                    00:00-24:00                         ; Heiligabend
  december 25                    00:00-24:00                         ; Weihnachten
  december 26                    00:00-24:00                         ; Weihnachten
  december 31                    00:00-24:00                         ; Silvester
  january 1                      00:00-24:00                         ; Neujahr
  may 1							 00:00-24:00						 ; 1. Mai
  october 3						 00:00-24:00						 ; Tag der dt. Einheit
}

**Comment by ederator** [comment]
Hi @Tweak90 

du kannst Zeitperioden auch im openITCOCKPIT Pflegen und dann in deine Kontakten hinterlegen
Hier ein Link von unserer Demo:
https://demo.openitcockpit.io/timeperiods

In deinen Kontakten kannst du dann die neu angelegte Zeitperiode einstellen:
![bildschirmfoto von 2018-01-25 16-54-52](https://user-images.githubusercontent.com/14903729/35435755-2c3c4052-028c-11e8-8a43-3c6b85024a17.png)

**Comment by nook24** [comment]
--- English version below ---

Hi @Tweak90, danke für deine Idee, wir sind immer dankbar für Input aus der Community.
Deine Idee fanden wir so gut, dass wir sie gleich in unseren aktuellen Stable-Release 3.3.0-3 eingebaut haben :)

Jetzt kannst du in der Oberfläche bei einer Timeperiod, einen Kalender hinterlegen. Alle Tage, welche im Kalender als Feiertag angelegt sind, werden dann 24/7 überwacht:
![timeperiod](https://user-images.githubusercontent.com/9019992/35446904-6ebd5b8a-02b6-11e8-8090-b8147989c812.png)

Hier noch ein Beispiel des Kalenders:
![calendar](https://user-images.githubusercontent.com/9019992/35446923-79a27918-02b6-11e8-95b2-355fe55b1ccb.png)


Die erstellte Monitoring-Konfiguration sieht dann so aus:
````
define timeperiod{
    timeperiod_name                     d0626d76-d065-45be-8723-42feaa5f5688
    alias                               Community Request
    monday                              00:00-07:30,12:15-13:15,16:30-24:00
    tuesday                             00:00-07:30,12:15-13:15,16:30-24:00
    wednesday                           00:00-07:30,12:15-13:15,16:30-24:00
    thursday                            00:00-07:30,12:15-13:15,16:30-24:00
    friday                              00:00-07:30,13:15-24:00
    saturday                            00:00-24:00
    sunday                              00:00-24:00
    december 24 00:00-24:00; Heiligabend
    december 25 00:00-24:00; Weihnachten 1
    december 26 00:00-24:00; Weihnachten 2
    december 31 00:00-24:00; Silvester
    january 1 00:00-24:00; Neujahr
    october 3 00:00-24:00; Tag der dt. Einheit
    may 1 00:00-24:00; 1. Mai
}
````
---

@Tweak90 asked use, if it's possible to extend a time period definition with additional days like holidays. 
So we used our Calendars to define special days which extend the normal time periods. Every day defined in the Calendar extends the "normal" time range with a 24/7 day.
