### ISSUE TITLE
i-doit Software-Link list Sortierung

### ISSUE THREAD

**Issue by zrhck** [it-novum/openITCOCKPIT#761]
Hallo zusammen,

die software-link list wird bei jedem Aufruf neu zusammengewürfelt, sodass man bei vielen Verlinkungen mit Strg+F suchen muss. Ein Filter oder auch nur eine feste Reihenfolge wäre hilfreich. 

![image](https://user-images.githubusercontent.com/34365002/35507701-f4c21f5c-04ed-11e8-9aa3-0feec80e1c47.png)
![image](https://user-images.githubusercontent.com/34365002/35507714-0066472a-04ee-11e8-9617-ede32d6ee4e5.png)

**Comment by nook24** [comment]
Thanks for your report. The issue will be fixed with the next version/patch release.
