### ISSUE TITLE
Search by address

### ISSUE THREAD

**Issue by zrhck** [it-novum/openITCOCKPIT#762]
Hi,

searching by address always results in a complete hosts overview.
Version: 3.3.0

Die Suche nach IP Adressen gibt immer die komplette Hosts Liste aus, egal ob komplette IP oder nur ein Teil als wildcard.

**Comment by nook24** [comment]
Issue will be resolved with the next version. If you don't want to wait, you can replace the following tow files:
https://github.com/it-novum/openITCOCKPIT/blob/29990a96d80e2ca80a6dae266db94dcfa37f19b1/app/Controller/SearchController.php
https://github.com/it-novum/openITCOCKPIT/blob/29990a96d80e2ca80a6dae266db94dcfa37f19b1/app/webroot/js/scripts/controllers/HostsIndexController.js

After you replaced the files, you need to run the command `openitcockpit-update` as user `root`
