### ISSUE TITLE
Kein Aktualisieren der Konfiguration nach restore mit Backup

### ISSUE THREAD

**Issue by farosch** [it-novum/openITCOCKPIT#777]
Ich habe kürzlich die Konfiguration meines ITC über die Backups widerhergestellt.
Nach einer Änderung der Konfiguration zeigt das ITC oben rechts folgendes an:
![chrome_2018-03-14_11-33-13](https://user-images.githubusercontent.com/22905106/37397323-9a8e0acc-277b-11e8-9fe9-7a68f50ec24d.png)
Jedoch kann ich die Konfiguration nicht aktualisieren, genau an diesem Punkt bleibe ich hängen:
![chrome_2018-03-14_11-33-22](https://user-images.githubusercontent.com/22905106/37397360-aea4aa84-277b-11e8-9fbb-187440301a6d.png)
Was kann ich hier tun?
Und wo finde ich logfiles die mir vlt weiterhelfen könnten?

**Comment by m4ximum** [comment]
Hi @farosch 

Laufen denn alle dienste bei dir korrekt (naemon, statusengine und der gearman_job_server) ? 
Dies siehst du auf der Debugging seite unter Administration -> Debugging. Dort findest du eine übersicht der einzelenen gearman queues. Wenn alles rihtig ist sollte es dort so aussehen 
(der phpNSTA läuft nur wenn ein satellit eingerichtet ist und das DistributedMonitoring modul installiert ist)

![bildschirmfoto 2018-03-14 um 11 50 41](https://user-images.githubusercontent.com/9554776/37398219-1393821a-277e-11e8-80b7-e58e697d7d84.png)

![bildschirmfoto 2018-03-14 um 11 50 11](https://user-images.githubusercontent.com/9554776/37398211-0eed6910-277e-11e8-8ee6-b1852e2858ac.png)

**Comment by farosch** [comment]
Was die Dienste angeht, sieht alles soweit gut aus:
![chrome_2018-03-14_11-56-58](https://user-images.githubusercontent.com/22905106/37398450-e07c63be-277e-11e8-89d1-0d850c60ff33.png)
![chrome_2018-03-14_11-57-07](https://user-images.githubusercontent.com/22905106/37398451-e09621d2-277e-11e8-8a75-a8adc7cba801.png)

**Comment by m4ximum** [comment]
Kannst du mal bitte auf der Konsole 'openitcockpit-update' eingeben und wenn das fertig ist nochmal ein Export starten? 
Zudem schau mal bitte ob das Backup File geschrieben wird unter "/opt/openitc/nagios/backup/". Die Datei sollte ungefähr so heissen: export_oitc_bkp_2018-03-13_114552.sql (nur mit aktuellem datum und Uhrzeit)

**Comment by farosch** [comment]
`openitcockpit-update` läuft ohne Fehler durch.
eine export_oitc_bkp_2018-03-14_XXX.sql wir nicht angelegt, dafür eine Datei namens **openitcockpit_dump_2018-03-14_14-40-41.sql**

**Comment by itnjd** [comment]
Wahrscheinlich wurde die exports Tabelle nicht geleert. Dies sollte eigentlich automatisch geschehen, wenn ein Backup über die Oberfläche wiederhergestellt wird. Am besten einfach selbst mit dem mysql Server verbinden und die Tabelle leeren:

mysql --defaults-file=/etc/openitcockpit/mysql.cnf openitcockpit
delete from exports;

Danach sollte noch der gearman worker neu gestartet werden:

service gearman_worker restart

**Comment by farosch** [comment]
@itnjd Super das war es! Vielen Dank!
