### ISSUE TITLE
LDAP import not working if the server refuses to page 900 entries

### ISSUE THREAD

**Issue by SimonBin** [it-novum/openITCOCKPIT#793]
Hi, maybe you can help me debug this?

```
Contacted LDAP server: ldap.myorg.org
Searched filter query: (&(objectClass=inetOrgPerson)(cn=*))
Searched Base DN: ou=People,dc=myorg,dc=org
```

on the command line -->
`ldapsearch -E '!pr=50' -h ldap.myorg.org -b 'ou=People,dc=myorg,dc=org' -D 'uid=monitoradmin,ou=Accounts,dc=myorg,dc=org' '(&(objectClass=inetOrgPerson)(cn=*))' -W`

get lots of results

I added a `print_r` in `/usr/share/openitcockpit/app/Model/AdldapSearch.php`  after `$entries = $this->connection->getEntries($pages[$currentPage]);`, and it gives '[count] => 0` :-(

**Comment by SimonBin** [comment]
ok I tracked this down... 

in `app/Controller/Component/LdapComponent.php`

there is a hard coded `$perPage = 900;`

however, no error handling is done. and the LDAP server happens to reply:

```
# with pagedResults critical control: size=900
#

# search result
search: 2
result: 11 Administrative limit exceeded
text: illegal pagedResults page size
```

**Comment by nook24** [comment]
Have you tried to reduce the amount of `$perPage = 900;`?

**Comment by SimonBin** [comment]
yes if I change the value, the addFromLdap magically starts to show my users :-) although the displayname is not synthesised but that's just another minor issue...

**Comment by nook24** [comment]
If openITCOCKPIT runs on >= PHP 7.1 it will use a new LDAP Lib which has no pagination issues anymore.

Feel free to open a new issue if you run into any future problems.
