### ISSUE TITLE
Host macro settings beim Hosttemplate verschwindet 

### ISSUE THREAD

**Issue by m4rv1n** [it-novum/openITCOCKPIT#806]
wenn ich in einem Hosttemplate eine Host macro erstelle und ich den wert/value beim Host bearbeite dan verschwindet die Host macro aus meinem Hosttemplate sobald ich Refresh configuration ausführe.

im host ist die variable auch grün aber nach refresh conf blau

**Comment by ibering** [comment]
Hallo @m4rv1n,

beim Editieren vom Host, werden zuerst alle Makros aus dem Hosttemplate (falls welche vorhanden sind) geladen und angezeigt. 

![bildschirmfoto 2018-05-24 um 09 03 57](https://user-images.githubusercontent.com/9592910/40469879-2b68a136-5f32-11e8-8767-7a8081264485.png)

Um zu Erkennen welche vom Host und welche vom Hosttemplate geerbt werden, werden Hostmakros in blau und Hosttemplatemakros in grün angezeigt:

![bildschirmfoto 2018-05-24 um 09 04 32](https://user-images.githubusercontent.com/9592910/40469782-e4dea53a-5f31-11e8-8df1-7e47efea3ae0.png)

Man kann die Hosttemplatesmakros natürlich mit eigenen Werten überschreiben, diese gehören dann automatisch dem Host und die Vererbung wird entfernt. Deswegen werden die vom Hosttemplate editierten Makros auch in blau angezeigt:

![bildschirmfoto 2018-05-24 um 09 03 43](https://user-images.githubusercontent.com/9592910/40469863-1e515ede-5f32-11e8-9dc1-0568608a236b.png)

Viele Grüße
Irina

**Comment by m4rv1n** [comment]
Hallo Irina,

danke für die antwort, ich habe jetzt in der demo.openitcockpit.io volgende scenarios getestet.

Ich habe im "default host" Template ein macro erstellt, einen neuen host zugefügt den wert im host bearbeitet, refresh config und das geht ohne probleme.

aber wenn ich jetzt bei einem bereits bestehenden host den wert auch bearbeite dan verschwindet der macro eintrag aus meinem Host template.

siehe screen capture 
[macro.zip](https://github.com/it-novum/openITCOCKPIT/files/2034325/macro.zip)

gruss,

Marvin

**Comment by ibering** [comment]
Hallo @m4rv1n,

ich konnte den Fehler nachstellen. Werden es zügig beheben. Vielen Dank für den Hinweise

Viele Grüße
Irina

**Comment by ibering** [comment]
Hallo @m4rv1n,

mit #808 wurde der Fehler gefixt. Im nächsten stable Release, tritt das Verhalten nicht mehr auf.

Viele Grüße
Irina
