### ISSUE TITLE
user defined macros with quotation marks

### ISSUE THREAD

**Issue by mdhms** [it-novum/openITCOCKPIT#849]
Hi,

saving user defined macros with quotation marks deletes everything after a quotation mark:

foo"bar" => foo

**Comment by m4ximum** [comment]
Hi mdhms, 
This is a View escaping problem. The macros will be saved as you have written -> like foo"bar" (you can take a look in the macros table in the database). 
This is definitly a bug and will be fixed within the next version.

**Comment by m4ximum** [comment]
#850
