### ISSUE TITLE
Notification interval is ignored by event correlations

### ISSUE THREAD

**Issue by mdhms** [it-novum/openITCOCKPIT#851]
Hi,

if you have a check/retry interval of lets say 1 minute you will get a notification every minute instead of just one single notification as your notification interval is set to 0 seconds.

I saw the same behaviour on your demo system:
![image](https://user-images.githubusercontent.com/34365002/45403869-cdc0a100-b65c-11e8-9777-21ac18a05b17.png)

Marius

**Comment by nook24** [comment]
Hi @mdhms,
unfortunately we were unable to reproduce the described issue.
The most common reason for issues like this is, that you maybe forgot to refresh the monitoring configuration:
![bildschirmfoto 2018-09-17 um 11 30 49](https://user-images.githubusercontent.com/9019992/45616859-f982c300-ba70-11e8-9b68-fdec451352e8.png)

We also created an ECV on our demo system, where the issue does not occur:
https://demo.openitcockpit.io/notifications/serviceNotification/152
![bildschirmfoto 2018-09-17 um 11 58 34](https://user-images.githubusercontent.com/9019992/45616939-1e773600-ba71-11e8-9395-7c4982865232.png)
![screenshot_2018-09-17 services - open source system monitoring](https://user-images.githubusercontent.com/9019992/45617068-7ca41900-ba71-11e8-9415-c932e249ee46.png)

Hope this helps

**Comment by mdhms** [comment]
I made an event correlation with the same settings as in my system. This behaviour occurs because the state is flapping and when you disable notifications for UNKNOWN state it always sends a new notification because of to the changed state (?)

![image](https://user-images.githubusercontent.com/34365002/45618962-e0c9db80-ba77-11e8-902a-0fc38d9c4802.png)

I don't know if this is wanted or not. Maybe it's just a board in front of my head...

**Comment by nook24** [comment]
That your correlation result is just "UNKNOWN" looks a bit strange to me. An EVC service is always a passive service, did you set this to active? Or pressed "Reset check time"?

Only the host of an EVC will get checked activity (and also correlate all services )

**Comment by mdhms** [comment]
>  An EVC service is always a passive service, did you set this to active? 
That did the trick. Thank you!
