### ISSUE TITLE
Minimaler Intervall zu hoch

### ISSUE THREAD

**Issue by Tweak90** [it-novum/openITCOCKPIT#870]
Guten Tag,
ich bin aktuell dabei unsere alte Nagios Umgebung auf openITCOCKPIT umzuziehen, was bisher auch sehr gut funktioniert.

Nun bin ich auf folgendes Problem gestoßen:
Außerhalb unserer Arbeitszeit fragen wir an wichtigen Punkten Türsensoren ab. Diese werden aktuell jede Sekunde abgefragt, so dass es niemandem möglich ist den Raum zu betreten, ohne dass es eine Aufzeichnung davon gibt.

Bei openITCOCKPIT liegt der minimale Intervall bei 30 Sekunden, was die wahrscheinlichkeit, dass ein Zutritt nicht entdeckt wird, stark erhöht.

Gibt es einen Grund für diese Einschränkung? Ich verstehe, warum es nicht mit 1000en von Hosts so gehandhabt werden sollte. Aber ein Hinweis bei Werten unter 30 Sekunden wäre deutlich weniger restriktiv und würde dem Admin mehr Freiheiten erlauben als von vorn herein ganz zu sperren.

Gibt es eine Möglichkeit dies zu umgehen? Ist es denkbar, dieses Limit in zukünftigen Versionen zu entfernen und durch eine Warnung bei zu niedrigen Werten zu ersetzen? Alternativ wäre ein öffnen dieser Grenze in den Einstellungen auch eine gute Variante.

Gruß,
Stephan

**Comment by nook24** [comment]
Hi @Tweak90,

die Min- und Maxwerte können in der Datei `/etc/openitcockpit/app/Plugin/NagiosModule/Config/config.php` gesetzt werden:
````
        'SLIDER_STEPSIZE' => 30,
        'SLIDER_MIN'      => 30,
        'SLIDER_MAX'      => 14400,
````

> Gibt es einen Grund für diese Einschränkung?
Bei Skriptsprache (php, Python, Perl, Bash, etc..) muss man dort etwas aufpassen. Wenn viele Checks mit einem sehr kleinen Checkinterval ausgeführt werden sollen, dann ist das System nur noch mit dem Parsen des Skriptes beschäftigt und die CPU-Load steigt extrem an. Bei solchen Fällen sollte man dann auf Compilersprachen zurückgreifen.

Viele Grüße,

Daniel

**Comment by Tweak90** [comment]
Perfekt, vielen Dank :)
