### ISSUE TITLE
Dienst auf Hostgruppe anwenden

### ISSUE THREAD

**Issue by Tweak90** [it-novum/openITCOCKPIT#884]
Guten Tag,
in meiner bisherigen Nagios-Installation habe ich öfters damit gearbeitet, dass ich eine Hostgruppe erstellt habe, dieser diverse Hosts zugewiesen habe und anschließend habe ich einen Dienst definiert und diesem die Hostgroup zugewiesen. Neue mitglieder der Hostgruppe haben diesen Dienst dann automatisch auch hinzugefügt bekommen.

Ist dies auch in openITcockpit möglich oder für künftige Releases angedacht?

Beispiel:
`define service {

  service_description            Uptime

  hostgroup_name                 switches_snmp

  use                            generic-service                     ; Name of service template to use

  check_command                  check_snmp_uptime!readonly

}`

`define hostgroup {

  hostgroup_name                 switches_snmp

  alias                          switches_snmp

  members                        switch1,switch2,switch3,switch4

}`

**Comment by nook24** [comment]
Hi @Tweak90,

ganz wie in Nagios geht es bei openITCOCKPIT im Moment leider nicht. Alternativ könntest du folgendes tun:

1. Erstelle eine Hostgruppe (mit allen Hosts) welche die Services bekommen sollen.
2. Erstelle eine `Service Template Group` mit allen Servicetemplates, welche auf allen Hosts vorhanden sein sollen.
3. Danach kann die Servicevorlagengruppe über eine Hostgruppe, einen Host oder eine Hostgruppe mit dem gleichen Namen (matching host group) ausgerollt werden. Dann bekommen alle Hosts die Services erstellt.
![bildschirmfoto 2018-11-13 um 14 04 27](https://user-images.githubusercontent.com/9019992/48415470-bcc00900-e74d-11e8-81a3-4f5e904fd020.png)


Hoffe das hilft dir weiter.
