### ISSUE TITLE
Dashboard funktioniert nach Update auf 3.5 nicht mehr

### ISSUE THREAD

**Issue by Tweak90** [it-novum/openITCOCKPIT#891]
Guten Tag,
ich habe heute morgen das Update auf Version 3.5 ausgeführt, wie in der Changelog angedroht sind alle Dashboardtabs gelöscht - damit komme ich gut klar ;) Leider kann ich nun auch keine neuen Dashboards anlegen.
Wenn ich auf Dashboard hinzufügen klicke kann ich einen Namen eingeben, ein Klick auf "Create new Tab" bleibt allerdings ohne Ergebnis.

Wenn ich auf Add Widget klicke zeigt er restore defaults an, auch hier bringt ein klick nichts.

Gruß,
Stephan

**Comment by nook24** [comment]
Guten Morgen @Tweak90,
kannst du bitte einmal den Befehl `openitcockpit-update --roles-admin` als root ausführen und schauen ob es danach funktioniert?

**Comment by Tweak90** [comment]
Danke,
das Problem ist damit behoben. Vielen Dank :)

Gruß,
Stephan
