### ISSUE TITLE
Tacho Widget - Warning / Critical / Maximum

### ISSUE THREAD

**Issue by Tweak90** [it-novum/openITCOCKPIT#892]
Guten Morgen nochmal,
ich bin grad dabei die Dashboards wieder einzurichten.

Bisher konnte ich beim Tacho einstellen die einzelnen Bereiche einstellen um Sichtbar zu machen was der aktuelle Wert wirklich bedeutet. Nach dem Update auf 3.5 zeigen die Tachos nur noch nach unten.

Wir haben beispielsweise mehrere 100mbit Standleitungen, welche bei 80mbit Auslastung auf Warnung (gelber Bereich) und bei Last über 90mbit Kritisch (im roten Bereich) sind.

Nun sind die Tachos nur noch grau und auf Grund des fehlenden Maximalwerts bewegt sich auch der Zeiger nicht mehr.

Gruß,
Stephan

**Comment by nook24** [comment]
Hi @Tweak90,
ab 3.5 nutzen wir komplett den Output des Plugins. Leider ist in der aktuellen Version das Feld für Performance-Daten sehr kurz in der Datenbnak. Eventuell werden die Performance-Daten also abgeschnitten und verursachen so das Problek. Dies kannst du wie folgt beheben:
```SQL
ALTER TABLE `nagios_servicestatus` CHANGE `perfdata` `perfdata` VARCHAR(2048) CHARACTER SET utf8 COLLATE utf8_swedish_ci NULL DEFAULT NULL;
```
Der Patch wird mit der kommenden Version dann auch nachgeliefert.

Sollte das Problem danach immernoch bestehen, gibt das Plugin einen falschen Output bei den Performance-Daten aus.
Diese sollten wie folgt aussehen:
`'label'=value[Unit];[Warning];[Critical];[Minimum];[Maximum]`.

Siehe auch: https://nagios-plugins.org/doc/guidelines.html#AEN200

**Comment by Tweak90** [comment]
Hallo nook24,
vielen Dank. Dann warte ich einfach mal auf den nächsten Patch. So viel Druck ist da nicht hinter ;)

Gruß,
Stephan
