### ISSUE TITLE
phpnsta service fails to start

### ISSUE THREAD

**Issue by Tampa** [it-novum/openITCOCKPIT#903]
I'm not even sure what use that is supposed to have, but evidently this system is not working or the installation through manual download and package installation is incomplete. There is a lack of documentation of what the service actually is and how to properly install and configure it.

```
Jan 17 17:47:12 operations systemd[1]: phpnsta.service: Service hold-off time over, scheduling restart.
Jan 17 17:47:12 operations systemd[1]: Stopped openITCOCKPIT phpNSTA.
-- Subject: Unit phpnsta.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit phpnsta.service has finished shutting down.
Jan 17 17:47:12 operations systemd[1]: Starting openITCOCKPIT phpNSTA...
-- Subject: Unit phpnsta.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit phpnsta.service has begun starting up.
Jan 17 17:47:12 operations systemd-preexec.php[12487]: ERROR: Private key file for SSH connection does not exists
Jan 17 17:47:12 operations systemd-preexec.php[12487]: ERROR: Public key file for SSH connection does not exists
Jan 17 17:47:12 operations systemd-preexec.php[12487]: expat reports error code 7
Jan 17 17:47:12 operations systemd-preexec.php[12487]:         description: mismatched tag
Jan 17 17:47:12 operations systemd-preexec.php[12487]:         line: 7
Jan 17 17:47:12 operations systemd-preexec.php[12487]:         column: 2
Jan 17 17:47:12 operations systemd-preexec.php[12487]:         byte index: 509
Jan 17 17:47:12 operations systemd-preexec.php[12487]:         total bytes: 0
Jan 17 17:47:12 operations systemd-preexec.php[12487]:         data beginning 10 before byte index: json">
Jan 17 17:47:12 operations systemd-preexec.php[12487]: </head>
Jan 17 17:47:12 operations systemd-preexec.php[12487]: <body>
Jan 17 17:47:12 operations systemd-preexec.php[12487]:   <script type="text/javascript">_ ERROR: Can't connect to Supervisors XML RPC API!
Jan 17 17:47:12 operations systemd-preexec.php[12487]: Notice: If you use a proxy set no_proxy="127.0.0.1" in /etc/environment and restart your SSH session
Jan 17 17:47:12 operations systemd-preexec.php[12487]: ERROR: Pre-flight check not passed. Check your configuration and file permissions
Jan 17 17:47:12 operations systemd[1]: phpnsta.service: Control process exited, code=exited status=1
Jan 17 17:47:12 operations systemd[1]: Failed to start openITCOCKPIT phpNSTA.
-- Subject: Unit phpnsta.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit phpnsta.service has failed.
--
-- The result is failed.
Jan 17 17:47:12 operations systemd[1]: phpnsta.service: Unit entered failed state.
Jan 17 17:47:12 operations systemd[1]: phpnsta.service: Failed with result 'exit-code'.
Jan 17 17:47:12 operations systemd[1]: phpnsta.service: Service hold-off time over, scheduling restart.
Jan 17 17:47:12 operations systemd[1]: Stopped openITCOCKPIT phpNSTA.
-- Subject: Unit phpnsta.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit phpnsta.service has finished shutting down.
Jan 17 17:47:12 operations systemd[1]: phpnsta.service: Start request repeated too quickly.
Jan 17 17:47:12 operations systemd[1]: Failed to start openITCOCKPIT phpNSTA.
-- Subject: Unit phpnsta.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit phpnsta.service has failed.
--
-- The result is failed.
Jan 17 17:47:12 operations systemd[1]: phpnsta.service: Unit entered failed state.
Jan 17 17:47:12 operations systemd[1]: phpnsta.service: Failed with result 'start-limit-hit'.
```

**Comment by Tampa** [comment]
The whole manual install is because you refuse to allow "anyDB" for installations. Mariadb has only been solving issues on my end that were caused my mysql being very "unmaintained" recently. It really makes no sense to me to force mysql this way. It is the reason I been manually installing and upgrading. Evidently I managed to figure out the dependencies and the correct install order as the system is back online, but what a hassle.

**Comment by nook24** [comment]
It's not per se a mistake to allow MariaDB, we just don't support it.

**Comment by Tampa** [comment]
MariaDB and MySQL, as I have said, have been entirely drop-in replacements so far. I have not heard of any reason why MariaDB would not to be set equal or better supported than MySQL. As stated in the previous ticket on this matter forcing MySQL instead of allowing any SQL provider and "recommending" MySQL this forceful use of MySQL means that any other application that uses SQL will need to use MySQL as well unless I want to run everything in docker or other crap like that. Honestly, this seems asinine to me.

**Comment by jabdr** [comment]
The problem isn't mariadb itself, we support it with debian 9. The problem is the additional required testing for the apt packages (dependencies, distribution updates, and so on). mysql is the default in the main ubuntu repositories (mariadb is only in universe), on debian the default is mariadb.

**Comment by Tampa** [comment]
Do please explain what testing that would be, because last time I checked there weren't any reports of dependency issues or grave problems that only affected MariaDB. Again, it would be fine if you at least stopped forcing MySQL specifically and instead simply required an SQL provider to be present. The requirement you set means I have to manually install packages hoping that at the end of it the system still works and the install scripts operate on the system problem. This causes more issues than MariaDB could possibly cause. Not to mention I have been running this and many more installations of openitcockpit using MariaDB without any reported problems.
