### ISSUE TITLE
Anmeldung Grafana

### ISSUE THREAD

**Issue by MaAr389** [it-novum/openITCOCKPIT#945]
Hallo,
gibt es eine Möglichkeit sich am Grafana anzumelden? 
Aufrufen der internen Seite konnte ich bereits, nur wie lautet die Anmeldung?

**Comment by nook24** [comment]
Hi @MaAr389 
ich vermute du hast deine Antwort bereits in der Doku gefunden.
Für alle anderen die das Issue über eine Suchmaschine finden:

>The username for the Grafana interface is `admin`.
>
>A random password will be generated during the installation process. It is stored at: `/etc/openitcockpit/grafana/admin_password`

GER: https://docs.it-novum.com/display/ODD/Graphing+Backend#GraphingBackend-Grafana
EN: https://docs.it-novum.com/display/ODE/Graphing+Backend#GraphingBackend-Grafana

**Comment by MaAr389** [comment]
Hi @nook24 
im Endeffekt, habe ich mir direkt die Files im Docker angeschaut. Auf die Idee der Dokumentation kam ich erst später. ;)

Trotzdem vielen Dank!
