### ISSUE TITLE
Emailversand schlägt fehl

### ISSUE THREAD

**Issue by Terminator81** [it-novum/openITCOCKPIT#946]
`Warning: Notification command for contact 'xxxxx' about host 'default host' exited with exit code 255. stdout: ' Fatal error: Constant expression contains invalid operations in /etc/openitcockpit/app/ `

in meiner Email.php ist es so eingetragen
`class EmailConfig {
    public $default = array(
        "transport" => "Smtp",
        "host" => "DNS-Name-des-mailservers-intern",
        "port" => 587,
        "username" => "smtp@domain",
        "password" => "kennwort",
    );`

was passt hier nicht?

**Comment by ibering** [comment]
Hallo @Terminator81 ,

so wie aussieht hat sich ein Syntax Fehler in die `/etc/openitcockpit/app/Config/email.php` Datei eingeschlichen. Es können mehrere Ursachen haben, wie falsche Einführungszeichen oder fehlendes` $ `Zeichen, etc.

Wir empfehlen  die Emails über Postfix zu verschicken (besonders wenn der interne Mail Server ein Microsoft Exchange Server ist). 

Hier wird genauerer erklärt, wie man den Email Versand für openITCOCKPIT einrichten kann:  

https://openitcockpit.io/beginners/7-setup-email-notifications/

Viele Grüße
Irina

**Comment by Terminator81** [comment]
habe es gerade mal ohne Authentifizierung versucht und da gehts ....ich denke mal das liegt an den Sonderzeichen im Passowort u.a. ist auch ein ":" drin :)

**Comment by ibering** [comment]
Also der ":" ist es wahrscheinlich nicht, meistens sind es Anführungszeichen sowie Backslash die escaped werden müssten. Man kann auch einfach php auf die Datei machen, dann werden die Syntax Fehler angezeigt

`php /etc/openitcockpit/app/Config/email.php`

**Comment by nook24** [comment]
@Terminator81 funktionieren die E-Mail Benachrichtigungen jetzt bei dir? Dann würde ich das issue schließe.

**Comment by Terminator81** [comment]
yes sorry
