### ISSUE TITLE
Graph ca. 2 Stunden hinterher

### ISSUE THREAD

**Issue by Terminator81** [it-novum/openITCOCKPIT#947]
![grafik](https://user-images.githubusercontent.com/16563785/61932602-18e95700-af84-11e9-950e-fda0e3717800.png)
Uhrzeit 9:00

läuft da ein Job der das aktualisiert wenn ja kann man das auf fast echtzeit reduzieren?

**Comment by nook24** [comment]
Hi @Terminator81,
vermutlich nutzt dein Server `UTC` als Zeitzone, das würde zu -2 Stunden passen.

sofern du die Serverzeit nicht ändern möchtest, kannst du einfach die passende Zeitzone in deinem Benutzerprofil setzen. Danach werden alle Uhrzeiten in der Oberfläche "umgerechnet" und du siehst zwei Uhren oben rechts. Eine mit der Serverzeit und eine mit der Zeit von deinem Benutzer:
![Bildschirmfoto 2019-07-26 um 09 04 45](https://user-images.githubusercontent.com/9019992/61932999-10455080-af85-11e9-8eef-70bf2761e695.png)

**Comment by Terminator81** [comment]
ja danke 
hab die Zeitzone entsprechend auf Berlin geändert ....war noch auf UTC :)
jetzt passts
