### ISSUE TITLE
Aufruf Grafana - Unauthorized

### ISSUE THREAD

**Issue by MaAr389** [it-novum/openITCOCKPIT#948]
Hallo,
nachdem ich in der Community Version, die ersten Grafana Dashboards gebaut habe, wollte ich mir die heute morgen anschauen. Die Graphen erscheinen nicht, stattdessen bleibt das das Dashboard weiß, einzige Meldung, die kurz danach wieder verschwindet ist - Unauthorized. 

Womit kann das zusammen liegen? - Mein Benutzer kommt per LDAP. 

Gruß
Martin

**Comment by nook24** [comment]
Hallo @MaAr389,
könntest du bitte einen Screenshot von der Fehlermeldung posten? Dann wissen wir, ob der Fehler vom openITCOCKPIT oder vom Grafana kommt.
Screenshots können einfach per drag&drop in das Issue-Textfeld gezogen werden.

Hast du eventuell etwas in der `grafana.ini` angepasst?
Du könntest einmal alle Backend Konfigurationsdateien mit den folgenden zwei Befehlen neu erstellen lassen:
````
oitc config_generator --generate --reload

openitcockpit-update
````
Beides als `root` Benutzer ausführen.

Gruß,
Daniel

**Comment by MaAr389** [comment]
Hallo @nook24 
ausgerechnet jetzt bekomme ich wieder die Dashboards als Anzeige.
Geändert wurde in der Config-Datei von Grafana nichts. 

Wenn die Fehlermeldung erneut erscheint, mache ich direkt ein Screenshot davon.

Gruß
Martin

**Comment by nook24** [comment]
🤔

Ist dies eventuell ein PC der immer die openITCOCKPIT Oberfläche anzeigen soll bzw musstest du dich neu am openITCOCKPIT anmelden und dann ging es?

Wenn ja: Für Fernseher an der Bürowand würde ich dir empfehlen, die Anmeldung über die API-Keys zu machen. Dies wird hier beschrieben:
https://openitcockpit.io/2018/05/30/openitcockpit-3-4-2-released/

**Comment by MaAr389** [comment]
Nein, es ist regulär mein Arbeitsrechner. Beim erstmaligen Anlegen heute morgen, wollte ich ein Grafana Dashboard öffnen, die Meldung erscheint kurz oben rechts in der Ecke. 

![image](https://user-images.githubusercontent.com/27082197/64512123-fc13a380-d2e5-11e9-8e72-ab89104414f6.png)

Als Beispiel, wie es aussieht. 
Danach habe ich die Grafana Seite direkt mit dem Admin aufgerufen, danach ging es.

**Comment by nook24** [comment]
Ok, die Meldung kommt also direkt vom Grafana.

> Danach habe ich die Grafana Seite direkt mit dem Admin aufgerufen, danach ging es.

Ich vermute, du hast dich im Grafana dann als Admin angemeldet? Deshalb ist die Meldung danach verschwunden.

openITCOCKPIT nutzt keine Anmeldedaten um die Grafana-Dashboards einzubinden. Schau bitte einmal in deiner `/etc/openitcockpit/grafana/grafana.ini`, ob folgender Wert gesetzt ist:
```ini
[auth.anonymous]
# enable anonymous access
enabled = true
```

**Comment by MaAr389** [comment]
In der INI-Datei ist der Wert wie oben beschrieben, gesetzt.
Vielleicht warte ich bis morgen. Wenn der Fehler kommt, müsste in irgendeiner Log, ggf. vom nginx die Fehlermeldung auftauchen. Oder?

**Comment by MaAr389** [comment]
Da haben wir die Fehlermeldung

![image](https://user-images.githubusercontent.com/27082197/64536593-a8bb4880-d319-11e9-923b-7fddf3d6f7de.png)

**Comment by nook24** [comment]
Leider schwierig zu sagen was genau das Problem ist, da der Fehler wie gesagt von Grafana kommt. Im Grafana Repositories gibt es auch ein paar Issues zu diesem Thema...

Hast du schonmal mit den Dev-Tools im Browser geschaut, welche Antwort Grafana zurück gibt? Eventuell enthält dies weitere Informationen, oder das Syslog auf dem openITOCKPIT Server.

**Comment by nook24** [comment]
Ich schließe das Issue ersteinmal. Sollte das Problem bei openITCOCKPIT 4 immernoch bestehen, würde ich dich bitten nochmal eine neues Issue dazu zu eröffnen.
