### ISSUE TITLE
Translate openITCOCKPIT in as many languages as possible

### ISSUE THREAD

**Issue by binsky08** [it-novum/openITCOCKPIT#957]
Hacktoberfest 2019
========================

Celebrate [Hacktoberfest](https://hacktoberfest.digitalocean.com/) by getting involved in the open source community.
We would like to ask you to help us translate openITCOCKPIT in as many languages as possible.

*As many as you want* - *as long as you want*

**IMPORTANT! Please make sure to clone the ORM branch!**

## About the project
openITCOCKPIT is a modern web interface to manage a Nagios or Naemon based monitoring environment.

For more information please see the projects home page: https://openitcockpit.io/

### Step 1: Fork the repository

Fork our repository into your personal GitHub account by pressing on _Fork_ in the top right corner
![Fork openITCOCKPIT repository](https://openitcockpit.io/hacktoberfest/2019/fork.png)

Wait until the fork is done. This will just take a few seconds.
![Waiting for GitHub](https://openitcockpit.io/hacktoberfest/2019/waiting.png)

Clone the repository (replace **YOUR\_ACCOUNT\_NAME**)

![Clone Code](https://openitcockpit.io/hacktoberfest/2019/clone.png)

```
git clone -b ORM https://github.com/YOUR_ACCOUNT_NAME/openITCOCKPIT
cd openITCOCKPIT/
```

### **IMPORTANT!** Please make sure to clone the **ORM** branch! 

---

### Step 2: Go to the `Locale` folder

```
cd app/Locale
```

---

#### Step 3.1: The language folder does not exist yet:

Copy the template folder `en_US` and rename it like your chosen language.

```
cp -r en_US de_DE
```

If it is done continue with step 3.2

#### Step 3.2: The language folder already exists:
e.g.

```
cd de_DE/LC_MESSAGES
```

---

### Step 4: Translate

Translate the content of `*.po` files (e.g. default.po)

The translation must be done line by line.

The `msgid` contains the original english content and should **not be touched**

The translated message goes to `msgstr`.

#### But before you start, please read our [Important notes](#important-notes) section!

Example:

```
msgid "Week"
msgstr "Woche"
```

### Step 5: Commit, push & create PR

Replace **YOUR\_ACCOUNT\_NAME** with your GitHub account name.

```
git checkout -b ORM_translation_YOUR_ACCOUNT_NAME
git add .
git commit -m "Added translation for de_DE"
git push origin ORM_translation_YOUR_ACCOUNT_NAME
```

To contribute your changes, you need to send a pull request:

![Create Pull Request](https://openitcockpit.io/hacktoberfest/2019/pull_request.png)

Please notice: You need to select **ORM** as `base` while you create your pull request.
![Set base to ORM](https://openitcockpit.io/hacktoberfest/2019/use_ORM_branch.png)

---

#### Don´t translate en_US, that´s our source language :)

- Special words are not to translate
	- openITCOCKPIT, Statusengine, CakePHP, Gearman, GearmanWorker
	- LDAP, OpenLDAP, PHP, SSO, NRPE, NDO, UUID, ARO, ACO, ACL,
	- Nagios, Naemon, NPCE, NDOUtils
	- .....
- Don´t touch placeholders, escape characters, classes, values or html (style) code
	- % prefixed characters are used for replacements. (e.g. `%s` replaces a string or `%1$s`)
	- `\` escapes `"`
	- `CrudAuthorize::authorize()` is an example for an internal class. (Needed for error messages)
	- `$` prefixed words are variables (e.g. `$PATH`, `$USER1$`, `$ARG1$`)
	- use `<b>This is bold</b>` to generate bold characters
	- use `<success>Green text</success>` to generate green characters
- Keep length of strings that are using blank characters to get an uniform length

```
msgid  "User:         %s"
msgstr "Benutzer:     %s"
```

## Need help?
* Join [#openitcockpit](http://webchat.freenode.net/?channels=openitcockpit) on freenode.net for any questions

**Comment by rferromoreno** [comment]
Can I take the translation for Spanish?

What should happen with messages with empty `msgstr` ?
For example:

```
#: Plugin/Admin/Controller/BeaconsController.php:116
msgid "Beacon was not deleted"
msgstr ""

#: Plugin/Admin/Controller/LocationsController.php:39;69;94
msgid "Invalid location"
msgstr ""
```

Should we translate the content of `msgid` into `msgstr` ?

Another one: Should we also translate files `*.pot` under App/Locale or just App/Locale/*/LC_MESSAGES ?

**Comment by binsky08** [comment]
Hallo rferromoreno,

would be nice to translate the files into spanish.
`msgid` contains the original english text and the translated content should be added to `msgstr`.
Therefore every `msgstr` is empty by default :)

Copy the en_US folder and name it `es_ES`.
Then translate the .po files in the `es_ES/LC_MESSAGES` folder.
The .pot files are template files and not to translate

**Comment by Terminator81** [comment]
can i translate the german part?

**Comment by binsky08** [comment]
@Terminator81 yes of course, feel free :)
