### ISSUE TITLE
Create a wallpaper

### ISSUE THREAD

**Issue by nook24** [it-novum/openITCOCKPIT#960]
We would like to ask you to create a wallpaper.
It would be cool if our community members could download a wallpaper from our [project website](https://openitcockpit.io/) and also to have a background image for screenshots and screen recordings.

### About the project:
openITCOCKPIT is an open source network monitoring solution. It can monitor windows, linux, macOS, network hardware, storage servers and so on. Its written in PHP and runs on Ubuntu/Debian Linux.

### openITCOCKPIT Logo as SVG:

<img src="https://repo.it-novum.com/oitc/oitc2.svg">

Download: https://repo.it-novum.com/oitc/oitc2.svg

Please send your PR to this repo: https://github.com/it-novum/openITCOCKPIT-wallpapers

**Comment by mountainash** [comment]
Not really a #hacktoberfest task (as there's not really a PR involved) but what about the attached? Keeping on brand with the website style and not too distracting.

![wallpaper-oitc-copter](https://user-images.githubusercontent.com/27637/66254354-71538680-e775-11e9-8548-a233d5a0fd0a.jpg)

**Comment by nook24** [comment]
Nice and simple. I like it!

>Not really a #hacktoberfest task (as there's not really a PR involved)

You are right! I quickly created a repository for this. Feel free to send an PR :)
https://github.com/it-novum/openITCOCKPIT-wallpapers

**Comment by mountainash** [comment]
"Please also include an open license which grant an unrestricted usage of the wallpaper" hmmm - The copter image was pulled from the source code of the website. I'm not sure what it's licensed under - would you know?

**Comment by ibering** [comment]
I don't know the license, but we got the image from our marketing team so go ahead :)
