### ISSUE TITLE
LDAP import users not working?

### ISSUE THREAD

**Issue by joaormp** [it-novum/openITCOCKPIT#973]
Hi Guys,

I have a problem, on Import Users from LDAP I don't have anything, but I have tested the ldapsearch on ubuntu 16 LTS command line and all works...

Do I have to execute some type of execution or just have to wait for the results of the LDAP query?

Thanks in advance for your help :)

I'm testing with OpenITCockpit version 3.7.2 with community license...

**Comment by nook24** [comment]
Hi @joaormp,
is your LDAP a _Microsoft Active Directory_ or some _OpenLDAP_?
Both work slightly different and require a different config.

Check your LDAP configuration in openITCOCKPIT it should look like this for a MS AD:
![Bildschirmfoto 2019-11-25 um 09 02 22](https://user-images.githubusercontent.com/9019992/69522926-e61b9380-0f62-11ea-96a4-201ad0d95e8c.png)

If you want to use TLS and don't have a valid certificate and you are using a PHP Version < 7.2 (Ubuntu Xenial, Debian 9) than you need to modify your `/etc/ldap/ldap.conf` config:
```
TLS_REQCERT never
```

See: https://stackoverflow.com/a/7586808/11885414

If you have a large LDAP with a few thousand users you should update your system to use Ubuntu Bionic or update your PHP version to 7.2. openITCOCKPIT makes use of a complete new LDAP implementation with php 7.2.

**Comment by joaormp** [comment]
Hi @nook24, thanks for your reply. :)

I'm trying to connect to MS AD and the configuration is like the one you shared, and I'm not using TLS.
I'm with PHP 7.0.33-0ubuntu0.16.04.7, and I'm not able to install the PHP 7.2 from the internet probably because of a proxy problem... no return with the command ( sudo LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php
)

The strange is that on the Ubuntu OS command-line works fine :(

**Comment by nook24** [comment]
Have you check the logfiles for details?
- `/usr/share/openitcockpit/app/tmp/logs/error.log`
- `/var/log/nginx/cake/error.log`

You can also set the proxy server to resolve the proxy issue^^
```
sudo su
export HTTP_PROXY="http://10.10.10.10:8080"
export HTTPS_PROXY="http://10.10.10.10:8080"
LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php
```
