### ISSUE TITLE
Host nach Status sortieren

### ISSUE THREAD

**Issue by Terminator81** [it-novum/openITCOCKPIT#974]
![grafik](https://user-images.githubusercontent.com/16563785/69786071-f7121200-11b9-11ea-8e0c-a58213f20cd1.png)
kann man hier einen Click drauf legen, damit man nach dem Ausgewählten sortiert?

**Comment by ibering** [comment]
Hallo @Terminator81,

man kann bereits in der aktuellen Version mit einem Klick in der Hostliste nach dem Hoststatus sortieren. Oder meinst Du eventuell eine andere Liste?

Viele Grüße
Irina

**Comment by Terminator81** [comment]
bin bei "Hosts > Overview"

**Comment by ibering** [comment]
Also  die Sortierung durch das Klicken auf "Hoststatus"  in der Hostliste  ist bereits vorhanden:

![host_status_sort](https://user-images.githubusercontent.com/9592910/69812407-60ad1300-11f0-11ea-80c2-575ee83b62f7.gif)

Um einen bestimmten (Host)Status auszublenden bzw. auszuwählen, kann man die Checkboxen "Host status" im Filter verwenden

![host_filter](https://user-images.githubusercontent.com/9592910/69812573-b2ee3400-11f0-11ea-90af-ebf35eec25d6.png)

**Comment by Terminator81** [comment]
ah ok danke
hatte auf die symbole daneben geklickt also die 5 daneben und erwartet das ich auch danach direkt sortieren kann
