### ISSUE TITLE
bei mehreren Hosts Downtime entfernen

### ISSUE THREAD

**Issue by Terminator81** [it-novum/openITCOCKPIT#975]
man kann zwar bei einer gefilterten Menge für alle eine Downtime setzen, diese jedoch wieder löschen geht nur einer nach dem anderen...

**Comment by nook24** [comment]
Welche Version von openITCOCKPIT hast du bei dir im Einsatz?
![Bildschirmfoto 2019-11-28 um 09 30 04](https://user-images.githubusercontent.com/9019992/69789937-cc2bbc00-11c1-11ea-9701-839acc29d41a.png)

**Comment by Terminator81** [comment]
eigentlich aktuell...schaue ich dann gleich mal ....dann habe ich die Funktion nicht gefunden :)

**Comment by Terminator81** [comment]
ah direkt unter den Downtimes ....war bei den Hosts da wo ich auch die Downtime gesetzt habe ..
