### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by Tampa** [it-novum/openITCOCKPIT#977]
Both for each user or globally for all a field that allows entry of custom css to override the existing css of the interface. Biggest reason for this is the compact styling I quite like to use for most sites, whitespace is really a thorn in my eye, especially with material flat design being everywhere now.

This would also allow to change or even hide certain parts that specific users don't need to see or highlight important parts.

**Comment by nook24** [comment]
Tracked by ITC-2492

**Comment by nook24** [comment]
Fixed with openITCOCKPIT 4.2
