### ISSUE TITLE
Mattermost Integration

### ISSUE THREAD

**Issue by Tampa** [it-novum/openITCOCKPIT#979]
Mattermost is a Slack compatible chat system that has a fairly simple integration system that can receive notifications via a curl command for example. As it is a replacement for Slack with more features and active development(unlike Slack who has not seen development in years despite all claims).

I switched entirely to it because it is free and integration is a lot easier to do. I don't know about sending data back from it to other systems, but I doubt that is hard either and their documentation is fairly good now too.

I wrote a plugin for it for whmcs with the following code to send the notification, it is that simple:

```
public function sendNotification(NotificationInterface $notification, $moduleSettings, $notificationSettings)
                {
                $payload = "{ \"username\": \"".$moduleSettings['displayname']."\",
                \"icon_url\": \"".$moduleSettings['iconurl']."\",
                \"text\": \"WHMCS Notification\n".$notification->getTitle()."
                \n".$notification->getMessage()."\n".$notification->getUrl()."\"}";

                $ch = curl_init();

                if ($modulesettings['ssl'] === false)
                {
                        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
                        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
                }
                curl_setopt($ch, CURLOPT_URL, $moduleSettings['webhook_url']);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
                curl_setopt($ch, CURLOPT_POST, 1);

                $headers = array();
                $headers[] = "Content-Type: application/json";
                curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

                $result = curl_exec($ch);
                if (curl_errno($ch)) {
                        echo 'Error:' . curl_error($ch);
                }
                curl_close ($ch);
    }

**Comment by lesmonds** [comment]
@Tampa did you ever get this plugin working, and if so how and where do you add this code? 

thanks Les

**Comment by Tampa** [comment]
@lesmonds It is a feature request, I have not started development on an actual plugin, if I had a sample notification plugin I could probably create one

**Comment by nook24** [comment]
Due to I'm ill at home and super bored I added a Mattermost implementation into the next major version.

EN: https://docs.it-novum.com/display/ODE/Mattermost
DE: https://docs.it-novum.com/display/ODD/Mattermost

**Comment by Tampa** [comment]
Can't wait for the next release, thanks for adding!

I just noticed, it even acknowledges them, that is really nice, I may borrow that code for my own mattermost plugins in the future cause I have not figured out how to do that properly yet, nice work, hope you get well soon :)

**Comment by Tampa** [comment]
Either my folder perms are messed up again or the module is not properly setup to read the data from the database. The two_way flag is never set when it is applied in the database, each time I open the config page for the module it is unset. I checked the code, but cakephp is not my thing so not exactly sure, seems all proper to me, maybe a typo?
