### ISSUE TITLE
Connect to external Grafana - community version

### ISSUE THREAD

**Issue by skunkr** [it-novum/openITCOCKPIT#981]
Hello everyone,
I have just have installed a fresh instance of the community version, hoping that i will be able to connect to my external grafana dashboards. Unfortunatelly, it seems that the grafana configuration menu is missing although i have installed the grafana package ( marked as enterpise ).
Is this a normal behaviour ( enterprise modules cannot be used with a community licence ) or i am doing something wrong ?
Thank you,

Leo

**Comment by nook24** [comment]
Hi @skunkr,

The GrafanaModule will get installed by the system automatically. (it's a dependency).
Don't trust the enterprise badge, this is confusing and will be removed with the next major update. :)

openITCOCKPIT uses Graphite to store performance data and Grafana to auto generate dashboards.
If you don't want to use the docker version of  Graphite and Grafana (which gets shipped and maintained by openITCOCKPIT) you can find information about how to use an external server in the docs:
https://docs.it-novum.com/display/ODE/Graphing+Backend#GraphingBackend-UseexternalGraphiteandGrafanaServer(expert)

**Comment by skunkr** [comment]
@nook24 ,
Thank you Daniel,
In documentation sais:
"Configure external Grafana to use external Graphite

Navigate to Configuration → Grafana

"

This menu item seems to be missing in my side. I already have a Grafana/Prometheus implementation, and i would like to bring the dashboards into openITCOCKPIT. 
Am i suppose to configure anything else ?
Thank you so much,

Leo

**Comment by nook24** [comment]
It should be there like it is in the demo system: https://demo.openitcockpit.io/grafana_module/grafana_configuration

Maybe your user has insufficient permissions? Cloud you please run the command `openitcockpit-update --roles --rights --roles-admin` and recheck?

> I already have a Grafana/Prometheus implementation, and i would like to bring the dashboards into openITCOCKPIT.

At the moment openITCOCKPIT will only display the automatically generated Grafana Dashboards ([like this](https://demo.openitcockpit.io/hosts/browser/12))
Or user generated Grafana Dashboards [like in this example](https://demo.openitcockpit.io/grafana_module/grafana_userdashboards/view/2)

As workaround, you could use the **Notice** Widget to add your Grafana Dashboard to the openITCOCKPIT Dashboard like so
```
<iframe id="myFrame" src="https://grafana-server.example.org" frameborder="0" allowfullscreen style="width:100%; height:500px"></iframe>
```

Hope this helps

**Comment by skunkr** [comment]
Wow, this did the trick !
Thank you so much Daniel, this really is a gorgeous project.
Keep up the good work !
Thanks,

Leo
