### ISSUE TITLE
Support for Debian 10 (buster)

### ISSUE THREAD

**Issue by Skywalker-11** [it-novum/openITCOCKPIT#983]
Is it planned to support Debian 10 alias buster?

**Comment by nook24** [comment]
Yes, Buster support will be added with the next major update.

We will release more information about the next generation of openITCOCKPIT soon in your blog.

**Comment by nook24** [comment]
openITCOCKPIT 4 (currently in beta) has now support for Debian Buster: https://openitcockpit.io/2020/2020/03/27/openitcockpit-4-beta-next-generation-monitoring/
