### ISSUE TITLE
LDAPS not working anymore after Upgrade from Ubuntu 16.04 to 18.04

### ISSUE THREAD

**Issue by dirktimmer** [it-novum/openITCOCKPIT#985]
Hi all,

LDAPS isn't working anymore after upgrade to Ubuntu 18.04. It works before the Upgrade. The normal LDAP works,
I have installed again the certificate chain from our MS Active Directory server and installed mcrypt with: pecl install mrypt-1.0.1.
Openssl is enabled in php.

Does someone have other ideas, what I can check?

Best regards,
Dirk

**Comment by ibering** [comment]
Hallo Dirk,

welche Version von openITCOCKPIT ist bei Dir im Einsatz?

Viele Grüße
Irina

**Comment by dirktimmer** [comment]
Hi Irina, 

the openITCockpit Version isn't updated. It is 3.7.2. I have now configured LDAP with port 389 and LDAP.USE_TLS=true. This works.
On Ubuntu 16.04  LDAP.USE_TLS=true didn't worked with port 389 or 636.

Best regards,
Dirk

**Comment by nook24** [comment]
Hi @dirktimmer 
If php >= 7.2 is used (which is default on Ubuntu Bionic) openITCOCKPIT makes use of an new LDAP implementation.

If an system is running with php < 7.2 (or php5) it uses the old LDAP backend which had some issues with SSL, pagination and so on

https://github.com/it-novum/openITCOCKPIT/issues/976#issuecomment-562050493

Regards
Daniel

**Comment by dirktimmer** [comment]
Hi Daniel,

i'm using php >= 7.2.and there is a problem with ldaps. Ldap with tls is working fine.
When I try to use Ldaps, I get the following error on Login Screen:
The connection to the LDAP server has been lost.

In the Error Log from openITCockpit I can see the following, when I try to add a User from Ldap:
2020-01-29 12:26:34 Error: [FreeDSx\Ldap\Exception\ConnectionException] The connection to the LDAP server has been lost.
Request URL: /users/addFromLdap
Stack Trace:
#0 [internal function]: FreeDSx\Ldap\Tcp\MessageQueue->getMessages(1)
#1 /usr/share/openitcockpit/app/vendor_freedsx_ldap/freedsx/ldap/src/FreeDSx/Ldap/Tcp/MessageQueue.php(97): Generator->current()
#2 /usr/share/openitcockpit/app/vendor_freedsx_ldap/freedsx/ldap/src/FreeDSx/Ldap/Protocol/ClientProtocolHandler.php(243): FreeDSx\Ldap\Tcp\MessageQueue->getMessage(1)
#3 /usr/share/openitcockpit/app/vendor_freedsx_ldap/freedsx/ldap/src/FreeDSx/Ldap/Protocol/ClientProtocolHandler.php(148): FreeDSx\Ldap\Protocol\ClientProtocolHandler->handleRequest(Object(FreeDSx\Ldap\Protocol\LdapMessageRequest))
#4 /usr/share/openitcockpit/app/vendor_freedsx_ldap/freedsx/ldap/src/FreeDSx/Ldap/LdapClient.php(89): FreeDSx\Ldap\Protocol\ClientProtocolHandler->send(Object(FreeDSx\Ldap\Operation\Request\SimpleBindRequest))
#5 /usr/share/openitcockpit/app/Controller/UsersController.php(487): FreeDSx\Ldap\LdapClient->bind('<ldap-user>', '<ldap password>')
#6 [internal function]: UsersController->addFromLdap()
#7 /usr/share/openitcockpit/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#8 /usr/share/openitcockpit/app/Controller/AppController.php(624): Controller->invokeAction(Object(CakeRequest))
#9 /usr/share/openitcockpit/lib/Cake/Routing/Dispatcher.php(193): AppController->invokeAction(Object(CakeRequest))
#10 /usr/share/openitcockpit/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 /usr/share/openitcockpit/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

Here are a part of my debug Page:
TLS: on
OS: Ubuntu 18.04.3 LTS 
Kernel: 4.15.0-74-generic
Architecture: x86_64
PHP version: 7.2.24-0ubuntu0.18.04.2
PHP Memory limit: 256MB
PHP Max. execution time: 30s
PHP Libraries: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gearman, gettext, iconv, igbinary, imap, json, ldap, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, redis, rrd, shmop, SimpleXML, sockets, ssh2, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

Best regards,
Dirk

**Comment by nook24** [comment]
> i'm using php >= 7.2.and there is a problem with ldaps. Ldap with tls is working fine.

LDAP with enabled TLS = `ldaps`. So... I' confused.

**Comment by jabdr** [comment]
ldaps is a deprecated protocol and unsupported by openitcockpit. Please use starttls with port 389.

FYI: https://www.openldap.org/faq/data/cache/605.html

**Comment by dirktimmer** [comment]
Hi Daniel,
LDAP over Port 389 with Transport Layer Security (LDAP over TLS/SSL/StartTLS) is working. 
LDAPS over Port 636 (LDAP Secured) is not working.

But the first option is ok for me and during I write the message I saw from jabdr, that ldaps is deprecated.

I think I can close this thread.

Best regards,
Dirk
