### ISSUE TITLE
Question: Is openITCOCKPIT compatible with MNTOS?

### ISSUE THREAD

**Issue by Patriciawa** [it-novum/openITCOCKPIT#988]
Hi,

I've just installed openITCOCKPIT and I like it very much, however can I use it with the MNTOS plugin? 

Here's the link: https://library.nagios.com/library/products/nagios-core/documentation/integrating-mntos-with-nagios/
Nagios Exchange: https://exchange.nagios.org/directory/Addons/Frontends-%28GUIs-and-CLIs%29/Web-Interfaces/MNTOS/details

Description MNTOS: 

> MNTOS (Multi-Nagios Tactical Overview System) is monitoring server aggregation tool that works with both Nagios Core and Nagios XI. MNTOS provides a central dashboard that displays a tactical overview of the status of one or more monitoring servers. MNTOS allows you to scale your monitoring environment by deploying additional Nagios servers to monitor additional hosts, services, and applications. Each Nagios server monitors a portion of the entire infrastructure, and MNTOS provides a central dashboard that allows you to quickly see the status of everything from a single page.

Regards,

Patrick

**Comment by nook24** [comment]
Hi @Patriciawa 
I'm not familiar with it MNTOS and it looks quite old.
However by default openITCOCKPIT uses [Naemon](https://github.com/naemon/naemon-core/) which don't have any HTTP/CGI files anymore.
So I guess it will not work with MNTOS out of the box.

What do you try to achieve exactly?

openITCOCKPIT supports _Distributed monitoring_ managed by one central interface. So all configuration is done on one openITCOCKPIT server and gets automatically transferred to all distributed monitoring servers (satellites).

**Comment by Patriciawa** [comment]
Hi @nook24 

It indeed looks rather old. What we're trying to accomplish here is to create for example two Nagios instances. One as a "master" server and one as a "slave" server. You install the slave server on another network which will monitor all of the hosts there and report back to the master server.

I haven't noticed it but I see now that openITCOCKPIT support Distributed monitoring, nice! Guess that's what I am looking for. Thanks for your help and hard word!

Thanks,

Patrick

**Comment by nook24** [comment]
Hi @Patriciawa,

>It indeed looks rather old. What we're trying to accomplish here is to create for example two Nagios instances. One as a "master" server and one as a "slave" server. You install the slave server on another network which will monitor all of the hosts there and report back to the master server.

Yep - that's exactly what our _Distributed monitoring_ does. openITCOCKPIT satellites also run a local read only web interface. So remote locations can always check there monitoring system even if there is an connection issue to the master server.  In case of an connection lost, the satellite will also buffer all check results for the master server for post processing.

To use Distributed monitoring an [openITCOCKPIT Subscription](https://openitcockpit.io/#Subscription) is required.

Regards,

Daniel

**Comment by Patriciawa** [comment]
@nook24 Thanks for clarifying!
