### ISSUE TITLE
import LDAP User Error

### ISSUE THREAD

**Issue by david-edc1** [it-novum/openITCOCKPIT#990]
Hello,

the following (partly censored) LDAP Query is working fine on our ad:
(&(objectCategory=person)(objectClass=user)(memberOf=CN=GROUP,OU=OU,DC=REST))
all users are being listed

Problem: when used here I only receive the half user amount of the group from the query.

example 1: group from above, only 7 out of 15 users can be selected
example 2: request of all users from the whole DC -> only 15 from the ~32 users can be selected

any help or fixed for this?

Running on Ubuntu 18.04 with the newest oitc release

**Comment by nook24** [comment]
Hi @david-edc1 what type of LDAP server are you using? Microsoft AD or OpenLDAP?

The users in the select box are lazy loaded. Did you already tried to search for a missing user in the dropdown?

There are also a few required fields every user needs to have.

Required fields openITCOCKPIT 3.x: https://github.com/it-novum/openITCOCKPIT/blob/3.x-dev/app/Controller/UsersController.php#L282-L287

Required fields openITCOCKPIT 4: https://github.com/it-novum/openITCOCKPIT/blob/development/src/itnovum/openITCOCKPIT/Ldap/LdapClient.php#L134-L139

Hope this helps

**Comment by david-edc1** [comment]
Hi @nook24, its a MS AD, searching in the dropdown only listed the ones loaded.

3.x is being used.

The field 'mail' was missing for some users, the ones with it have been listed.

Thank you for the detail, I'll correct it and it should work then.
