### ISSUE TITLE
openITCOCKPIT Agent - Powershell

### ISSUE THREAD

**Issue by MaAr389** [it-novum/openITCOCKPIT#991]
Hallo,
ich würde gerne Powershellskripte auf einen Host ausführen und mir den Return-Wert ins Monitoring-System zurückgeben lassen. Wie passt man die customchecks entsprechend an, dass das Powershellskript ausgeführt wird? 

[check_xyz]
command = cmd /c echo check_xyz.ps1; exit($lastexitcode) | powershell.exe -command -
interval = 60
timeout = 5
enabled = true

Vielen Dank im Voraus!

**Comment by support-itn** [comment]
Hallo MaAr389,

die Configdatei hierfür ist die C:\Program Files\it-novum\openitcockpit-agent\customchecks.cnf.
Falls die Datei customchecks.cnf nicht vorhanden ist, bitte manuell anlegen. 

In der config.cnf, gleiches Verzeichnis, bitte den Pfad zur customchecks.cnf anpassen.
`customchecks = C:\Program Files\it-novum\openitcockpit-agent\customchecks.cnf`


Die customchecks.cnf könnte wie folgt aussehen:

```
[default]
# max_worker_threads should be increased with increasing number of custom checks
# but consider: each thread needs (a bit) memory
max_worker_threads = 8

[check_xyz]
command = powershell "C:\Users\test\Documents\test.ps1"
interval = 60
timeout = 5
enabled = true
```

Um Powershell-Skriptdateien zu aktivieren, bitte als Administrator
`powershell Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine`
ausführen.
Und danach den Agent über die GUI oder in der Commandline neu starten:
`sc.exe stop oitcAgentSvc`
`sc.exe start oitcAgentSvc`

**Comment by MaAr389** [comment]
Hi,
vielen Dank. Nun kommt mir eine weitere Frage auf. 
Wie greift man jetzt mittels Service auf das Powershellscript zu? 
Es existiert ja "check_oitc_agent_customcheck", leider stehe ich auf dem Schlauch, weil ich mir nicht vorstellen kann, wie dieser hinzugefügt wird.  

Unter der Agent Konfiguration taucht der Command check_xyz nicht auf.

**Comment by support-itn** [comment]
Hallo,

den Host öffnen und unter "More actions" die openITCOCKPIT Agent discovery öffnen.

![Bild1](https://user-images.githubusercontent.com/62543802/79748012-f4e95500-830c-11ea-8423-32dd931279d0.jpeg)

Hier nun "Skip configuration generation" auswählen

![Bild2](https://user-images.githubusercontent.com/62543802/79748056-0af71580-830d-11ea-8735-8ce565c731be.jpeg)

und es erscheinen nun die "Customchecks".

![Bild3](https://user-images.githubusercontent.com/62543802/79748067-15191400-830d-11ea-84c8-800d89ecaa9a.jpeg)

Auf "Next" klicken und anschließend die Konfiguration refreshen.

Anmerkung:
Falls schon alle "Customchecks" importiert wurden, ist das Auswahlfeld ausgeblendet.

**Comment by MaAr389** [comment]
Hallo,
genau der Punkt "Customchecks" taucht nicht auf.

**Comment by MaAr389** [comment]
Hallo,
erledigt. Fehler gefunden.

**Comment by ibering** [comment]
Hallo @MaAr389,

Worin bestand der Fehler bzw. die Lösung? Vielleicht kommt bei anderen auch vor, dann haben sie gleich einen Lösungseinsatz :)

Viele Grüße
Irina

**Comment by MaAr389** [comment]
Hallo @ibering 
ich habe innerhalb der Config nicht aufgepasst und einmal den Parameter "customchecks = xyz" angelegt und weiter unten stand nochmals "customchecks = "

Gruß

**Comment by ibering** [comment]
Hallo @MaAr389,

ach so. Vielen Dank für die Info. Ich werde das Issue nun schließen.

Viele Grüße
Irina
