### ISSUE TITLE
fehlender Return-Wert vom Powershell Skript (Agent)

### ISSUE THREAD

**Issue by MaAr389** [it-novum/openITCOCKPIT#992]
Hallo, 
folgendes Problem, - auf unserem Exchange liegt unter C:\script\check_exchange.ps1
Den Befehl habe ich entsprechend der Dokumentation customchecks eingebaut. 

Wenn ich den Befehl per CMD ausführe, bekomme ich einen Return-Wert, leider erhält das Monitoring-System die Werte nicht. Ich bin mir nicht mehr sicher, woran das liegen könnte. 

`[check_dbqueue]
command = powershell "C:\scripts\check_exchange.ps1" -CheckType Queue ; exit($lastexitcode)"
interval = 60
timeout = 5
enabled = true`

![open_customchecks](https://user-images.githubusercontent.com/27082197/80959608-778f0b80-8e07-11ea-8ae7-a1ed8f609225.JPG)
![cmd_query](https://user-images.githubusercontent.com/27082197/80959609-7827a200-8e07-11ea-8f22-a41a4aacf8fb.JPG)

Vielen Dank im Voraus.
Gruß
MaAr

**Comment by binsky08** [comment]
Hi @MaAr389,

wir haben versucht das Szenario nachzustellen und sind zu folgendem, funktionierenden Ergebnis gekommen:

C:\hello.ps1
```
Write-Host "Hallo customcheck"
exit 1
```

customchecks.cnf
```
[check_test]
  command = powershell.exe -File "C:\hello.ps1"
  interval = 60
  timeout = 10
  enabled = true
```

Für weitere Infos über den Agent:
[https://docs.it-novum.com/display/ODD/openITCOCKPIT+Agent](https://docs.it-novum.com/display/ODD/openITCOCKPIT+Agent)

**Comment by nook24** [comment]
Das `-File` macht den Unterschied.
