### ISSUE TITLE
 Service graphs rendering issue

### ISSUE THREAD

**Issue by some-git-user** [it-novum/openITCOCKPIT#994]
Das "Rendering" des Servicegraphen ist teilweise fehlerhaft:
Beispiel ist ein und der selbe Service. Nur die "Timerange" wurde angepasst:

4 hour
![Screenshot_20200513_140300](https://user-images.githubusercontent.com/65288184/81810002-7c983d00-9522-11ea-83f0-0519da607376.png)

 8 hour
![Screenshot_20200513_140423](https://user-images.githubusercontent.com/65288184/81810114-b1a48f80-9522-11ea-8eb9-3c3dbaca2d3f.png)

1 day
![Screenshot_20200513_140458](https://user-images.githubusercontent.com/65288184/81810158-c719b980-9522-11ea-88b6-8ca947826f20.png)

Dies tritt so bei allen getesteten Servicegraphen auf.

**Comment by ibering** [comment]
Hallo @some-git-user,

vielen Dank für den Hinweis. Wir haben das Problem nachstellen können und haben diesen behoben. Der Patch wird dann beim nächsten Release dabei sein. 

Viele Grüße und noch ein schönes Wochenende
Irina
