### ISSUE TITLE
Copy service's issue

### ISSUE THREAD

**Issue by some-git-user** [it-novum/openITCOCKPIT#995]
URL: .../ng/#!/services/copy/...

Beim Kopieren bereits bestehender Services kann man im Menü "Copy service's" verschiedene Parameter wie z.B. "Service name" und  "Check command" Argumente bearbeiten.
Dies funktioniert leider bei den einzelnen $ARGx$ Argumenten nicht.
Der kopierte Service nimmt diese Änderungen nicht an, sondern behält die Argumente des originalen Services.
Wenn der kopierte Services anschließend von Hand angepasst wird, können dort die $ARGx$ Argumente ganz normal bearbeitet werden.

**Comment by m4ximum** [comment]
Hallo, 
danke für dein feedback! 
der bug ist jetzt im aktuellen development branch gefixt und im kommenden release enthalten
VG
