### ISSUE TITLE
monitoring engine not running

### ISSUE THREAD

**Issue by david-edc1** [it-novum/openITCOCKPIT#996]
this should explain everything:

![ossm-error](https://user-images.githubusercontent.com/63358936/82047629-6968a700-96b3-11ea-8b19-f6452caec9c7.PNG)
![ossm-config](https://user-images.githubusercontent.com/63358936/82047634-6e2d5b00-96b3-11ea-8864-32450c7a344d.PNG)

is there something wrong with the config? How can I fix it?
except the misspelling of "false" in the return

**Comment by nook24** [comment]
This is caused by an Ubuntu Update :(. We are working an a Patch.
https://bugs.launchpad.net/ubuntu/+source/json-c/+bug/1878738

**Comment by david-edc1** [comment]
Ok thank you for the info, thought I messed something up :)
Is there a way to know when the patch is available for updating?

**Comment by nook24** [comment]
Thanks @david-edc1 for reporting this to use.

We posted a workaround in our blog:
https://openitcockpit.io/2020/2020/05/15/monitoring-not-running-after-installing-latest-security-updates-on-ubuntu-lh-table-new-calloc-failed/

To get frequent updates about the openITCOCKPIT, you can follow us on Twitter:
https://twitter.com/openITCOCKPIT

**Comment by david-edc1** [comment]
Thanks for the fast help!
